// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface AdbUsageEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:android_studio.AdbUsageEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.android_studio.AdbUsageEvent.JdwpProcessPropertiesCollectorEvent process_properties_event = 1 [lazy = true];</code>
   * @return Whether the processPropertiesEvent field is set.
   */
  boolean hasProcessPropertiesEvent();
  /**
   * <code>.android_studio.AdbUsageEvent.JdwpProcessPropertiesCollectorEvent process_properties_event = 1 [lazy = true];</code>
   * @return The processPropertiesEvent.
   */
  com.google.wireless.android.sdk.stats.AdbUsageEvent.JdwpProcessPropertiesCollectorEvent getProcessPropertiesEvent();
  /**
   * <code>.android_studio.AdbUsageEvent.JdwpProcessPropertiesCollectorEvent process_properties_event = 1 [lazy = true];</code>
   */
  com.google.wireless.android.sdk.stats.AdbUsageEvent.JdwpProcessPropertiesCollectorEventOrBuilder getProcessPropertiesEventOrBuilder();

  /**
   * <code>.android_studio.AdbUsageEvent.AdbDeviceStateChangeEvent device_state_change_event = 2 [lazy = true];</code>
   * @return Whether the deviceStateChangeEvent field is set.
   */
  boolean hasDeviceStateChangeEvent();
  /**
   * <code>.android_studio.AdbUsageEvent.AdbDeviceStateChangeEvent device_state_change_event = 2 [lazy = true];</code>
   * @return The deviceStateChangeEvent.
   */
  com.google.wireless.android.sdk.stats.AdbUsageEvent.AdbDeviceStateChangeEvent getDeviceStateChangeEvent();
  /**
   * <code>.android_studio.AdbUsageEvent.AdbDeviceStateChangeEvent device_state_change_event = 2 [lazy = true];</code>
   */
  com.google.wireless.android.sdk.stats.AdbUsageEvent.AdbDeviceStateChangeEventOrBuilder getDeviceStateChangeEventOrBuilder();

  /**
   * <code>.android_studio.AdbUsageEvent.AppInfoProcessPropertiesCollectorEvent app_info_process_properties_event = 3 [lazy = true];</code>
   * @return Whether the appInfoProcessPropertiesEvent field is set.
   */
  boolean hasAppInfoProcessPropertiesEvent();
  /**
   * <code>.android_studio.AdbUsageEvent.AppInfoProcessPropertiesCollectorEvent app_info_process_properties_event = 3 [lazy = true];</code>
   * @return The appInfoProcessPropertiesEvent.
   */
  com.google.wireless.android.sdk.stats.AdbUsageEvent.AppInfoProcessPropertiesCollectorEvent getAppInfoProcessPropertiesEvent();
  /**
   * <code>.android_studio.AdbUsageEvent.AppInfoProcessPropertiesCollectorEvent app_info_process_properties_event = 3 [lazy = true];</code>
   */
  com.google.wireless.android.sdk.stats.AdbUsageEvent.AppInfoProcessPropertiesCollectorEventOrBuilder getAppInfoProcessPropertiesEventOrBuilder();

  /**
   * <pre>
   * Add other types of events, e.g. attaching debugger, etc
   * </pre>
   *
   * <code>.android_studio.AdbUsageEvent.AppInfoSupportEvent app_info_support_event = 4 [lazy = true];</code>
   * @return Whether the appInfoSupportEvent field is set.
   */
  boolean hasAppInfoSupportEvent();
  /**
   * <pre>
   * Add other types of events, e.g. attaching debugger, etc
   * </pre>
   *
   * <code>.android_studio.AdbUsageEvent.AppInfoSupportEvent app_info_support_event = 4 [lazy = true];</code>
   * @return The appInfoSupportEvent.
   */
  com.google.wireless.android.sdk.stats.AdbUsageEvent.AppInfoSupportEvent getAppInfoSupportEvent();
  /**
   * <pre>
   * Add other types of events, e.g. attaching debugger, etc
   * </pre>
   *
   * <code>.android_studio.AdbUsageEvent.AppInfoSupportEvent app_info_support_event = 4 [lazy = true];</code>
   */
  com.google.wireless.android.sdk.stats.AdbUsageEvent.AppInfoSupportEventOrBuilder getAppInfoSupportEventOrBuilder();

  com.google.wireless.android.sdk.stats.AdbUsageEvent.EventCase getEventCase();
}
