// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats_logged_in.proto

package com.google.wireless.android.sdk.stats;

public final class AndroidStudioStatsLoggedIn {
  private AndroidStudioStatsLoggedIn() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_AndroidStudioEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_AndroidStudioEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_UIActionStatsLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_UIActionStatsLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_AppLinksAssistantEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_AppLinksAssistantEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_AppLinksAssistantEventLoggedIn_ValidationSummary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_AppLinksAssistantEventLoggedIn_ValidationSummary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_AppLinksAssistantEventLoggedIn_IntentFilterFix_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_AppLinksAssistantEventLoggedIn_IntentFilterFix_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_AppQualityInsightsUsageEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_AppQualityInsightsUsageEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_AppQualityInsightsUsageEventLoggedIn_InsightFetchDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_AppQualityInsightsUsageEventLoggedIn_InsightFetchDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_DirectAccessUsageEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_DirectAccessUsageEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_DirectAccessUsageEventLoggedIn_ReserveDeviceDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_DirectAccessUsageEventLoggedIn_ReserveDeviceDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_DirectAccessUsageEventLoggedIn_ConnectDeviceDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_DirectAccessUsageEventLoggedIn_ConnectDeviceDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_DirectAccessUsageEventLoggedIn_StreamStartedDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_DirectAccessUsageEventLoggedIn_StreamStartedDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_TSdkUAEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_TSdkUAEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlResponseMetadataLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlResponseMetadataLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlCompletionEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlCompletionEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlCompletionEventLoggedIn_CompletionAggregateEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlCompletionEventLoggedIn_CompletionAggregateEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlTransformEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlTransformEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlTransformEventLoggedIn_TransformRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlTransformEventLoggedIn_TransformResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformShown_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlTransformEventLoggedIn_TransformShown_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformAccepted_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlTransformEventLoggedIn_TransformAccepted_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformRejected_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlTransformEventLoggedIn_TransformRejected_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlChatBotEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlChatBotEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlChatBotEventLoggedIn_BotResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlChatBotEventLoggedIn_BotResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlChatBotEventLoggedIn_ActionInvoked_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlChatBotEventLoggedIn_ActionInvoked_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlChatBotEventLoggedIn_QueryBoxEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlChatBotEventLoggedIn_QueryBoxEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlChatBotEventLoggedIn_ContextDrawerEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlChatBotEventLoggedIn_ContextDrawerEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlConfigurationEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlConfigurationEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_TestScenarioEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_TestScenarioEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_TestScenarioEventLoggedIn_TestScenarioRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_TestScenarioEventLoggedIn_TestScenarioRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_TestScenarioEventLoggedIn_TestScenarioResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_TestScenarioEventLoggedIn_TestScenarioResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_DeviceConnectedNotificationEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_DeviceConnectedNotificationEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_StudioCoreGeminiActionsEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_StudioCoreGeminiActionsEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_StudioLabsEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_StudioLabsEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_PromptLibraryEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_PromptLibraryEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_PromptLibraryEventLoggedIn_Update_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_PromptLibraryEventLoggedIn_Update_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_PromptLibraryEventLoggedIn_Invoke_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_PromptLibraryEventLoggedIn_Invoke_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_JourneyFinishedEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_JourneyFinishedEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_PlayPolicyInsightsUsageEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_PlayPolicyInsightsUsageEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_ModelProviderEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_ModelProviderEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_ModelProviderEventLoggedIn_Update_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_ModelProviderEventLoggedIn_Update_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_NextEditPredictionEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_NextEditPredictionEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_NextEditPredictionEventLoggedIn_PredictionShown_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_NextEditPredictionEventLoggedIn_PredictionShown_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_NextEditPredictionEventLoggedIn_PredictionAccepted_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_NextEditPredictionEventLoggedIn_PredictionAccepted_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_NextEditPredictionEventLoggedIn_Session_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_NextEditPredictionEventLoggedIn_Session_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_NextEditPredictionEventLoggedIn_Session_SessionEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_NextEditPredictionEventLoggedIn_Session_SessionEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SkillsEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SkillsEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SkillsEventLoggedIn_Activation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SkillsEventLoggedIn_Activation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034studio_stats_logged_in.proto\022\016android_" +
      "studio\"\274\014\n\032AndroidStudioEventLoggedIn\022B\n" +
      "\017ui_action_stats\030\" \001(\0132%.android_studio." +
      "UIActionStatsLoggedInB\002(\001\022U\n\031app_links_a" +
      "ssistant_event\030+ \001(\0132..android_studio.Ap" +
      "pLinksAssistantEventLoggedInB\002(\001\022c\n app_" +
      "quality_insights_usage_event\030\223\001 \001(\01324.an" +
      "droid_studio.AppQualityInsightsUsageEven" +
      "tLoggedInB\002(\001\022V\n\031direct_access_usage_eve" +
      "nt\030\236\001 \001(\0132..android_studio.DirectAccessU" +
      "sageEventLoggedInB\002(\001\022?\n\rtsdk_ua_event\030\240" +
      "\001 \001(\0132#.android_studio.TSdkUAEventLogged" +
      "InB\002(\001\022M\n\024sml_completion_event\030\247\001 \001(\0132*." +
      "android_studio.SmlCompletionEventLoggedI" +
      "nB\002(\001\022K\n\023sml_transform_event\030\250\001 \001(\0132).an" +
      "droid_studio.SmlTransformEventLoggedInB\002" +
      "(\001\022H\n\022sml_chat_bot_event\030\251\001 \001(\0132\'.androi" +
      "d_studio.SmlChatBotEventLoggedInB\002(\001\022S\n\027" +
      "sml_configuration_event\030\252\001 \001(\0132-.android" +
      "_studio.SmlConfigurationEventLoggedInB\002(" +
      "\001\022W\n\020device_connected\030\277\001 \001(\01328.android_s" +
      "tudio.DeviceConnectedNotificationEventLo" +
      "ggedInB\002(\001\022K\n\023test_scenario_event\030\301\001 \001(\013" +
      "2).android_studio.TestScenarioEventLogge" +
      "dInB\002(\001\022k\n(android_studio_core_gemini_ac" +
      "tions_event\030\317\001 \001(\01324.android_studio.Stud" +
      "ioCoreGeminiActionsEventLoggedInB\002(\001\022G\n\021" +
      "studio_labs_event\030\323\001 \001(\0132\'.android_studi" +
      "o.StudioLabsEventLoggedInB\002(\001\022M\n\024prompt_" +
      "library_event\030\324\001 \001(\0132*.android_studio.Pr" +
      "omptLibraryEventLoggedInB\002(\001\022Q\n\026journey_" +
      "finished_event\030\343\001 \001(\0132,.android_studio.J" +
      "ourneyFinishedEventLoggedInB\002(\001\022c\n play_" +
      "policy_insights_usage_event\030\354\001 \001(\01324.and" +
      "roid_studio.PlayPolicyInsightsUsageEvent" +
      "LoggedInB\002(\001\022M\n\024model_provider_event\030\355\001 " +
      "\001(\0132*.android_studio.ModelProviderEventL" +
      "oggedInB\002(\001\022X\n\032next_edit_prediction_even" +
      "t\030\361\001 \001(\0132/.android_studio.NextEditPredic" +
      "tionEventLoggedInB\002(\001\022>\n\014skills_event\030\371\001" +
      " \001(\0132#.android_studio.SkillsEventLoggedI" +
      "nB\002(\001\"2\n\025UIActionStatsLoggedIn\022\031\n\021action" +
      "_class_name\030\001 \001(\t\"\300\003\n\036AppLinksAssistantE" +
      "ventLoggedIn\022P\n\014event_source\030\003 \001(\0162:.and" +
      "roid_studio.AppLinksAssistantEventLogged" +
      "In.EventSource\022`\n\022validation_summary\030\013 \001" +
      "(\0132@.android_studio.AppLinksAssistantEve" +
      "ntLoggedIn.ValidationSummaryB\002(\001\022]\n\021inte" +
      "nt_filter_fix\030\014 \001(\0132>.android_studio.App" +
      "LinksAssistantEventLoggedIn.IntentFilter" +
      "FixB\002(\001\032\023\n\021ValidationSummary\032\021\n\017IntentFi" +
      "lterFix\"c\n\013EventSource\022\022\n\016UNKNOWN_SOURCE" +
      "\020\000\022 \n\034NEW_LINK_CREATION_SIDE_PANEL\020\024\022\036\n\032" +
      "LAUNCH_APP_LINKS_ASSISTANT\020(\"\362\002\n$AppQual" +
      "ityInsightsUsageEventLoggedIn\022k\n\025insight" +
      "_fetch_details\030\022 \001(\0132H.android_studio.Ap" +
      "pQualityInsightsUsageEventLoggedIn.Insig" +
      "htFetchDetailsB\002(\001\032k\n\023InsightFetchDetail" +
      "s\022T\n\006source\030\004 \001(\0162D.android_studio.AppQu" +
      "alityInsightsUsageEventLoggedIn.AiInsigh" +
      "tSource\"p\n\017AiInsightSource\022\022\n\016UNKNOWN_SO" +
      "URCE\020\000\022 \n\034AI_INSIGHT_SOURCE_STUDIO_BOT\020\001" +
      "\022\'\n#AI_INSIGHT_SOURCE_CRASHLYTICS_TITAN\020" +
      "\002\"\216\006\n\036DirectAccessUsageEventLoggedIn\022W\n\004" +
      "type\030\001 \001(\0162I.android_studio.DirectAccess" +
      "UsageEventLoggedIn.DirectAccessUsageEven" +
      "tType\022g\n\026reserve_device_details\030\003 \001(\0132C." +
      "android_studio.DirectAccessUsageEventLog" +
      "gedIn.ReserveDeviceDetailsB\002(\001\022g\n\026connec" +
      "t_device_details\030\004 \001(\0132C.android_studio." +
      "DirectAccessUsageEventLoggedIn.ConnectDe" +
      "viceDetailsB\002(\001\022g\n\026stream_started_detail" +
      "s\030\005 \001(\0132C.android_studio.DirectAccessUsa" +
      "geEventLoggedIn.StreamStartedDetailsB\002(\001" +
      "\032\'\n\024ReserveDeviceDetails\022\017\n\007success\030\001 \001(" +
      "\010\032\'\n\024ConnectDeviceDetails\022\017\n\007success\030\001 \001" +
      "(\010\032\'\n\024StreamStartedDetails\022\017\n\007success\030\001 " +
      "\001(\010\"\334\001\n\032DirectAccessUsageEventType\022\021\n\rUN" +
      "KNOWN_EVENT\020\000\022\022\n\016RESERVE_DEVICE\020\001\022\022\n\016CON" +
      "NECT_DEVICE\020\002\022\022\n\016STREAM_STARTED\020\003\022\026\n\022EXT" +
      "END_RESERVATION\020\004\022\023\n\017END_RESERVATION\020\005\022\025" +
      "\n\021DISCONNECT_DEVICE\020\006\022\027\n\023SERVICE_DEPRECA" +
      "TION\020\007\022\022\n\016OEM_LAB_DIALOG\020\010\"\025\n\023TSdkUAEven" +
      "tLoggedIn\"\323\002\n\033SmlResponseMetadataLoggedI" +
      "n\022\031\n\021model_provider_id\030\004 \001(\t\022\020\n\010model_id" +
      "\030\005 \001(\t\022T\n\nagent_type\030\007 \001(\0162@.android_stu" +
      "dio.SmlResponseMetadataLoggedIn.SmlAgent" +
      "TypeLoggedIn\"\260\001\n\024SmlAgentTypeLoggedIn\022\032\n" +
      "\026AGENT_TYPE_UNSPECIFIED\020\000\022\026\n\022AGENT_TYPE_" +
      "GENERIC\020\001\022\034\n\030AGENT_TYPE_UPGRADE_AGENT\020\002\022" +
      " \n\034AGENT_TYPE_NEW_PROJECT_AGENT\020\003\022$\n AGE" +
      "NT_TYPE_DEEP_LINK_LOGIC_AGENT\020\004\"\335\001\n\032SmlC" +
      "ompletionEventLoggedIn\022\\\n\taggregate\030\005 \001(" +
      "\0132C.android_studio.SmlCompletionEventLog" +
      "gedIn.CompletionAggregateEventB\002(\001H\000\032S\n\030" +
      "CompletionAggregateEvent\022\031\n\021completions_" +
      "shown\030\004 \001(\005\022\034\n\024completions_accepted\030\005 \001(" +
      "\005B\014\n\ncompletion\"\305\005\n\031SmlTransformEventLog" +
      "gedIn\022Q\n\007request\030\001 \001(\0132:.android_studio." +
      "SmlTransformEventLoggedIn.TransformReque" +
      "stB\002(\001H\000\022S\n\010response\030\002 \001(\0132;.android_stu" +
      "dio.SmlTransformEventLoggedIn.TransformR" +
      "esponseB\002(\001H\000\022M\n\005shown\030\003 \001(\01328.android_s" +
      "tudio.SmlTransformEventLoggedIn.Transfor" +
      "mShownB\002(\001H\000\022S\n\010accepted\030\004 \001(\0132;.android" +
      "_studio.SmlTransformEventLoggedIn.Transf" +
      "ormAcceptedB\002(\001H\000\022O\n\016transform_kind\030\005 \001(" +
      "\01627.android_studio.SmlTransformEventLogg" +
      "edIn.TransformKind\032\022\n\020TransformRequest\032\023" +
      "\n\021TransformResponse\032\020\n\016TransformShown\032\023\n" +
      "\021TransformAccepted\032\023\n\021TransformRejected\"" +
      "\230\001\n\rTransformKind\022\013\n\007UNKNOWN\020\000\022\n\n\006CUSTOM" +
      "\020\001\022\014\n\010DOCUMENT\020\002\022\036\n\032MULTIMODAL_COMPOSE_P" +
      "REVIEW\020\003\022\034\n\030GENERATE_COMPOSE_PREVIEW\020\004\022\"" +
      "\n\036GENERATE_INSIGHT_SUGGESTED_FIX\020\005B\013\n\ttr" +
      "ansform\"\277\n\n\027SmlChatBotEventLoggedIn\022K\n\010r" +
      "esponse\030\001 \001(\01323.android_studio.SmlChatBo" +
      "tEventLoggedIn.BotResponseB\002(\001H\000\022S\n\016acti" +
      "on_invoked\030\003 \001(\01325.android_studio.SmlCha" +
      "tBotEventLoggedIn.ActionInvokedB\002(\001H\000\022T\n" +
      "\017query_box_event\030\n \001(\01325.android_studio." +
      "SmlChatBotEventLoggedIn.QueryBoxEventB\002(" +
      "\001H\000\022^\n\024context_drawer_event\030\013 \001(\0132:.andr" +
      "oid_studio.SmlChatBotEventLoggedIn.Conte" +
      "xtDrawerEventB\002(\001H\000\032\225\001\n\013BotResponse\022A\n\010m" +
      "etadata\030\001 \001(\0132+.android_studio.SmlRespon" +
      "seMetadataLoggedInB\002(\001\022C\n\tchat_mode\030\004 \001(" +
      "\01620.android_studio.SmlChatBotEventLogged" +
      "In.ChatMode\032O\n\rActionInvoked\022>\n\006action\030\002" +
      " \001(\0162..android_studio.SmlChatBotEventLog" +
      "gedIn.Action\032^\n\rQueryBoxEvent\022M\n\nevent_t" +
      "ype\030\001 \001(\01629.android_studio.SmlChatBotEve" +
      "ntLoggedIn.QueryBoxEventType\032\024\n\022ContextD" +
      "rawerEvent\"m\n\010ChatMode\022\016\n\nOTHER_MODE\020\000\022\010" +
      "\n\004CHAT\020\001\022\016\n\nAGENT_MODE\020\002\022\031\n\025VERSION_UPGR" +
      "ADE_AGENT\020\003\022\016\n\nQUICK_EDIT\020\004\022\014\n\010PLANNING\020" +
      "\005\"\222\002\n\006Action\022\013\n\007INVALID\020\000\022\022\n\016MOVE_TO_EDI" +
      "TOR\020\001\022\021\n\rMOVE_TO_CARET\020\002\022\024\n\020MOVE_TO_NEW_" +
      "FILE\020\003\022\022\n\016ADD_DEPENDENCY\020\004\022\020\n\014BROWSE_TOP" +
      "IC\020\005\022\031\n\025EXPLORE_IN_PLAYGROUND\020\006\022\022\n\016MERGE" +
      "_MANIFEST\020\007\022\024\n\020MERGE_SUGGESTION\020\t\022\024\n\020INS" +
      "ERT_RESOURCES\020\n\022\033\n\027INSERT_NAME_SUGGESTIO" +
      "NS\020\013\022\017\n\013COPY_BUTTON\020\014\022\017\n\013COPY_MANUAL\020\r\"\335" +
      "\001\n\021QueryBoxEventType\022\023\n\017QUERY_BOX_OTHER\020" +
      "\000\022\026\n\022COMPLETION_STARTED\020\001\022\027\n\023COMPLETION_" +
      "ACCEPTED\020\002\022\030\n\024COMPLETION_DISMISSED\020\003\022 \n\034" +
      "QUERY_WITH_CONTEXT_SUBMITTED\020\004\022\025\n\021REFERE" +
      "NCE_DELETED\020\005\022\034\n\030IMAGE_ATTACHMENT_CLICKE" +
      "D\020\006\022\021\n\rQUERY_STOPPED\020\007B\t\n\007content\"\252\004\n\035Sm" +
      "lConfigurationEventLoggedIn\022\025\n\rsml_avail" +
      "able\030\001 \001(\010\022\036\n\026bot_onboarding_started\030\004 \001" +
      "(\010\022 \n\030bot_onboarding_completed\030\005 \001(\010\022\032\n\022" +
      "completion_enabled\030\002 \001(\010\022\031\n\021transform_en" +
      "abled\030\003 \001(\010\022\037\n\027project_context_enabled\030\006" +
      " \001(\010\022X\n\017product_variant\030\007 \001(\0162?.android_" +
      "studio.SmlConfigurationEventLoggedIn.Sml" +
      "ProductVariant\022!\n\031agent_auto_accept_enab" +
      "led\030\010 \001(\010\"\332\001\n\021SmlProductVariant\022\033\n\027PRODU" +
      "CT_VARIANT_UNKNOWN\020\000\022\030\n\024PRODUCT_VARIANT_" +
      "FREE\020\001\022\034\n\030PRODUCT_VARIANT_BUSINESS\020\002\022*\n\"" +
      "PRODUCT_VARIANT_DASHER_USER_CHOICE\020\003\032\002\010\001" +
      "\022\037\n\033PRODUCT_VARIANT_DASHER_FREE\020\004\022#\n\037PRO" +
      "DUCT_VARIANT_DASHER_BUSINESS\020\005\"\201\004\n\031TestS" +
      "cenarioEventLoggedIn\022T\n\007request\030\001 \001(\0132=." +
      "android_studio.TestScenarioEventLoggedIn" +
      ".TestScenarioRequestB\002(\001H\000\022`\n\024test_scena" +
      "rio_result\030\003 \001(\0132<.android_studio.TestSc" +
      "enarioEventLoggedIn.TestScenarioResultB\002" +
      "(\001H\000\032\025\n\023TestScenarioRequest\032\265\001\n\022TestScen" +
      "arioResult\022#\n\033misformatted_response_coun" +
      "t\030\001 \001(\005\022Q\n\017generation_type\030\002 \001(\01628.andro" +
      "id_studio.TestScenarioEventLoggedIn.Gene" +
      "rationType\022\022\n\nnum_accept\030\003 \001(\005\022\023\n\013num_de" +
      "cline\030\004 \001(\005\"P\n\016GenerationType\022\035\n\031GENERAT" +
      "ION_TYPE_UNDEFINED\020\000\022\014\n\010NEW_FILE\020\001\022\021\n\rEX" +
      "ISTING_FILE\020\002B\013\n\ttransform\"*\n(DeviceConn" +
      "ectedNotificationEventLoggedIn\"\205\002\n$Studi" +
      "oCoreGeminiActionsEventLoggedIn\022K\n\006actio" +
      "n\030\001 \001(\0162;.android_studio.StudioCoreGemin" +
      "iActionsEventLoggedIn.Action\022\025\n\rresults_" +
      "count\030\005 \001(\005\022\025\n\rresults_taken\030\006 \001(\005\"b\n\006Ac" +
      "tion\022\013\n\007UNKNOWN\020\000\022\023\n\017RENAME_VARIABLE\020\001\022\032" +
      "\n\026RETHINK_VARIABLE_NAMES\020\002\022\032\n\026SUGGEST_CO" +
      "MMIT_MESSAGE\020\003\"\361\001\n\027StudioLabsEventLogged" +
      "In\022Q\n\020page_interaction\030\002 \001(\01627.android_s" +
      "tudio.StudioLabsEventLoggedIn.PageIntera" +
      "ction\"\202\001\n\017PageInteraction\022\027\n\023UNKNOWN_INT" +
      "ERACTION\020\000\022\n\n\006OPENED\020\001\022\030\n\024APPLY_BUTTON_C" +
      "LICKED\020\002\022\031\n\025CANCEL_BUTTON_CLICKED\020\003\022\025\n\021O" +
      "K_BUTTON_CLICKED\020\004\"\245\002\n\032PromptLibraryEven" +
      "tLoggedIn\022A\n\006update\030\001 \001(\01321.android_stud" +
      "io.PromptLibraryEventLoggedIn.Update\022A\n\006" +
      "invoke\030\002 \001(\01321.android_studio.PromptLibr" +
      "aryEventLoggedIn.Invoke\032w\n\006Update\022\032\n\022pro" +
      "mpts_in_library\030\001 \001(\005\022\023\n\013rules_count\030\002 \001" +
      "(\005\022 \n\030builtins_overrides_count\030\003 \001(\005\022\032\n\022" +
      "user_prompts_count\030\004 \001(\005\032\010\n\006Invoke\"\272\001\n\034J" +
      "ourneyFinishedEventLoggedIn\022L\n\013test_resu" +
      "lt\030\001 \001(\01627.android_studio.JourneyFinishe" +
      "dEventLoggedIn.TestResult\"L\n\nTestResult\022" +
      "\013\n\007UNKNOWN\020\000\022\n\n\006PASSED\020\001\022\n\n\006FAILED\020\002\022\013\n\007" +
      "ABORTED\020\003\022\014\n\010CANCELED\020\004\"\361\001\n$PlayPolicyIn" +
      "sightsUsageEventLoggedIn\022c\n\004type\030\001 \001(\0162U" +
      ".android_studio.PlayPolicyInsightsUsageE" +
      "ventLoggedIn.PlayPolicyInsightsUsageEven" +
      "tType\"d\n PlayPolicyInsightsUsageEventTyp" +
      "e\022\021\n\rUNKNOWN_EVENT\020\000\022\027\n\023SERVICE_DEPRECAT" +
      "ION\020\001\022\024\n\020BATCH_INSPECTION\020\002\"\332\001\n\032ModelPro" +
      "viderEventLoggedIn\022A\n\006update\030\001 \001(\01321.and" +
      "roid_studio.ModelProviderEventLoggedIn.U" +
      "pdate\032y\n\006Update\022#\n\033local_model_providers" +
      "_count\030\001 \001(\005\022$\n\034remote_model_providers_c" +
      "ount\030\002 \001(\005\022$\n\034gemini_model_providers_cou" +
      "nt\030\003 \001(\005\"\352\006\n\037NextEditPredictionEventLogg" +
      "edIn\022T\n\005shown\030\001 \001(\0132?.android_studio.Nex" +
      "tEditPredictionEventLoggedIn.PredictionS" +
      "hownB\002(\001H\000\022Z\n\010accepted\030\002 \001(\0132B.android_s" +
      "tudio.NextEditPredictionEventLoggedIn.Pr" +
      "edictionAcceptedB\002(\001H\000\022N\n\007session\030\006 \001(\0132" +
      "7.android_studio.NextEditPredictionEvent" +
      "LoggedIn.SessionB\002(\001H\000\032\021\n\017PredictionShow" +
      "n\032\024\n\022PredictionAccepted\032\203\004\n\007Session\022T\n\006e" +
      "vents\030\005 \003(\0132D.android_studio.NextEditPre" +
      "dictionEventLoggedIn.Session.SessionEven" +
      "t\032\241\003\n\014SessionEvent\022\\\n\004type\030\001 \001(\0162N.andro" +
      "id_studio.NextEditPredictionEventLoggedI" +
      "n.Session.SessionEvent.EventType\"\262\002\n\tEve" +
      "ntType\022\026\n\022UNKNOWN_EVENT_TYPE\020\000\022\020\n\014REQUES" +
      "T_SENT\020\001\022\025\n\021RESPONSE_RECEIVED\020\002\022\024\n\020PREDI" +
      "CTION_SHOWN\020\003\022\027\n\023PREDICTION_ACCEPTED\020\004\022\027" +
      "\n\023PREDICTION_REJECTED\020\005\022\025\n\021SESSION_CANCE" +
      "LLED\020\006\022\021\n\rCONTROL_SHOWN\020\007\022\024\n\020CONTROL_ACC" +
      "EPTED\020\010\022\024\n\020CONTROL_REJECTED\020\t\022\022\n\016CONTROL" +
      "_HIDDEN\020\n\022\025\n\021PREDICTION_FAILED\020\013\022\033\n\027CONT" +
      "ROL_DISPOSED_UNSEEN\020\014B\026\n\024next_edit_predi" +
      "ction\"\261\002\n\023SkillsEventLoggedIn\022A\n\010metadat" +
      "a\030\001 \001(\0132+.android_studio.SmlResponseMeta" +
      "dataLoggedInB\002(\001\022H\n\nactivation\030\002 \001(\0132..a" +
      "ndroid_studio.SkillsEventLoggedIn.Activa" +
      "tionB\002(\001H\000\032I\n\nActivation\022;\n\004type\030\001 \001(\0162-" +
      ".android_studio.SkillsEventLoggedIn.Skil" +
      "lType\"9\n\tSkillType\022\013\n\007UNKNOWN\020\000\022\r\n\tPRE_B" +
      "UILT\020\001\022\020\n\014USER_DEFINED\020\002B\007\n\005eventBE\n%com" +
      ".google.wireless.android.sdk.statsB\032Andr" +
      "oidStudioStatsLoggedInP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_android_studio_AndroidStudioEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_android_studio_AndroidStudioEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_AndroidStudioEventLoggedIn_descriptor,
        new java.lang.String[] { "UiActionStats", "AppLinksAssistantEvent", "AppQualityInsightsUsageEvent", "DirectAccessUsageEvent", "TsdkUaEvent", "SmlCompletionEvent", "SmlTransformEvent", "SmlChatBotEvent", "SmlConfigurationEvent", "DeviceConnected", "TestScenarioEvent", "AndroidStudioCoreGeminiActionsEvent", "StudioLabsEvent", "PromptLibraryEvent", "JourneyFinishedEvent", "PlayPolicyInsightsUsageEvent", "ModelProviderEvent", "NextEditPredictionEvent", "SkillsEvent", });
    internal_static_android_studio_UIActionStatsLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_android_studio_UIActionStatsLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_UIActionStatsLoggedIn_descriptor,
        new java.lang.String[] { "ActionClassName", });
    internal_static_android_studio_AppLinksAssistantEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_android_studio_AppLinksAssistantEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_AppLinksAssistantEventLoggedIn_descriptor,
        new java.lang.String[] { "EventSource", "ValidationSummary", "IntentFilterFix", });
    internal_static_android_studio_AppLinksAssistantEventLoggedIn_ValidationSummary_descriptor =
      internal_static_android_studio_AppLinksAssistantEventLoggedIn_descriptor.getNestedTypes().get(0);
    internal_static_android_studio_AppLinksAssistantEventLoggedIn_ValidationSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_AppLinksAssistantEventLoggedIn_ValidationSummary_descriptor,
        new java.lang.String[] { });
    internal_static_android_studio_AppLinksAssistantEventLoggedIn_IntentFilterFix_descriptor =
      internal_static_android_studio_AppLinksAssistantEventLoggedIn_descriptor.getNestedTypes().get(1);
    internal_static_android_studio_AppLinksAssistantEventLoggedIn_IntentFilterFix_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_AppLinksAssistantEventLoggedIn_IntentFilterFix_descriptor,
        new java.lang.String[] { });
    internal_static_android_studio_AppQualityInsightsUsageEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_android_studio_AppQualityInsightsUsageEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_AppQualityInsightsUsageEventLoggedIn_descriptor,
        new java.lang.String[] { "InsightFetchDetails", });
    internal_static_android_studio_AppQualityInsightsUsageEventLoggedIn_InsightFetchDetails_descriptor =
      internal_static_android_studio_AppQualityInsightsUsageEventLoggedIn_descriptor.getNestedTypes().get(0);
    internal_static_android_studio_AppQualityInsightsUsageEventLoggedIn_InsightFetchDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_AppQualityInsightsUsageEventLoggedIn_InsightFetchDetails_descriptor,
        new java.lang.String[] { "Source", });
    internal_static_android_studio_DirectAccessUsageEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_android_studio_DirectAccessUsageEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_DirectAccessUsageEventLoggedIn_descriptor,
        new java.lang.String[] { "Type", "ReserveDeviceDetails", "ConnectDeviceDetails", "StreamStartedDetails", });
    internal_static_android_studio_DirectAccessUsageEventLoggedIn_ReserveDeviceDetails_descriptor =
      internal_static_android_studio_DirectAccessUsageEventLoggedIn_descriptor.getNestedTypes().get(0);
    internal_static_android_studio_DirectAccessUsageEventLoggedIn_ReserveDeviceDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_DirectAccessUsageEventLoggedIn_ReserveDeviceDetails_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_android_studio_DirectAccessUsageEventLoggedIn_ConnectDeviceDetails_descriptor =
      internal_static_android_studio_DirectAccessUsageEventLoggedIn_descriptor.getNestedTypes().get(1);
    internal_static_android_studio_DirectAccessUsageEventLoggedIn_ConnectDeviceDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_DirectAccessUsageEventLoggedIn_ConnectDeviceDetails_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_android_studio_DirectAccessUsageEventLoggedIn_StreamStartedDetails_descriptor =
      internal_static_android_studio_DirectAccessUsageEventLoggedIn_descriptor.getNestedTypes().get(2);
    internal_static_android_studio_DirectAccessUsageEventLoggedIn_StreamStartedDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_DirectAccessUsageEventLoggedIn_StreamStartedDetails_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_android_studio_TSdkUAEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_android_studio_TSdkUAEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_TSdkUAEventLoggedIn_descriptor,
        new java.lang.String[] { });
    internal_static_android_studio_SmlResponseMetadataLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_android_studio_SmlResponseMetadataLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlResponseMetadataLoggedIn_descriptor,
        new java.lang.String[] { "ModelProviderId", "ModelId", "AgentType", });
    internal_static_android_studio_SmlCompletionEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_android_studio_SmlCompletionEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlCompletionEventLoggedIn_descriptor,
        new java.lang.String[] { "Aggregate", "Completion", });
    internal_static_android_studio_SmlCompletionEventLoggedIn_CompletionAggregateEvent_descriptor =
      internal_static_android_studio_SmlCompletionEventLoggedIn_descriptor.getNestedTypes().get(0);
    internal_static_android_studio_SmlCompletionEventLoggedIn_CompletionAggregateEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlCompletionEventLoggedIn_CompletionAggregateEvent_descriptor,
        new java.lang.String[] { "CompletionsShown", "CompletionsAccepted", });
    internal_static_android_studio_SmlTransformEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_android_studio_SmlTransformEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlTransformEventLoggedIn_descriptor,
        new java.lang.String[] { "Request", "Response", "Shown", "Accepted", "TransformKind", "Transform", });
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformRequest_descriptor =
      internal_static_android_studio_SmlTransformEventLoggedIn_descriptor.getNestedTypes().get(0);
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlTransformEventLoggedIn_TransformRequest_descriptor,
        new java.lang.String[] { });
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformResponse_descriptor =
      internal_static_android_studio_SmlTransformEventLoggedIn_descriptor.getNestedTypes().get(1);
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlTransformEventLoggedIn_TransformResponse_descriptor,
        new java.lang.String[] { });
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformShown_descriptor =
      internal_static_android_studio_SmlTransformEventLoggedIn_descriptor.getNestedTypes().get(2);
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformShown_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlTransformEventLoggedIn_TransformShown_descriptor,
        new java.lang.String[] { });
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformAccepted_descriptor =
      internal_static_android_studio_SmlTransformEventLoggedIn_descriptor.getNestedTypes().get(3);
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformAccepted_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlTransformEventLoggedIn_TransformAccepted_descriptor,
        new java.lang.String[] { });
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformRejected_descriptor =
      internal_static_android_studio_SmlTransformEventLoggedIn_descriptor.getNestedTypes().get(4);
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformRejected_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlTransformEventLoggedIn_TransformRejected_descriptor,
        new java.lang.String[] { });
    internal_static_android_studio_SmlChatBotEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_android_studio_SmlChatBotEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlChatBotEventLoggedIn_descriptor,
        new java.lang.String[] { "Response", "ActionInvoked", "QueryBoxEvent", "ContextDrawerEvent", "Content", });
    internal_static_android_studio_SmlChatBotEventLoggedIn_BotResponse_descriptor =
      internal_static_android_studio_SmlChatBotEventLoggedIn_descriptor.getNestedTypes().get(0);
    internal_static_android_studio_SmlChatBotEventLoggedIn_BotResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlChatBotEventLoggedIn_BotResponse_descriptor,
        new java.lang.String[] { "Metadata", "ChatMode", });
    internal_static_android_studio_SmlChatBotEventLoggedIn_ActionInvoked_descriptor =
      internal_static_android_studio_SmlChatBotEventLoggedIn_descriptor.getNestedTypes().get(1);
    internal_static_android_studio_SmlChatBotEventLoggedIn_ActionInvoked_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlChatBotEventLoggedIn_ActionInvoked_descriptor,
        new java.lang.String[] { "Action", });
    internal_static_android_studio_SmlChatBotEventLoggedIn_QueryBoxEvent_descriptor =
      internal_static_android_studio_SmlChatBotEventLoggedIn_descriptor.getNestedTypes().get(2);
    internal_static_android_studio_SmlChatBotEventLoggedIn_QueryBoxEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlChatBotEventLoggedIn_QueryBoxEvent_descriptor,
        new java.lang.String[] { "EventType", });
    internal_static_android_studio_SmlChatBotEventLoggedIn_ContextDrawerEvent_descriptor =
      internal_static_android_studio_SmlChatBotEventLoggedIn_descriptor.getNestedTypes().get(3);
    internal_static_android_studio_SmlChatBotEventLoggedIn_ContextDrawerEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlChatBotEventLoggedIn_ContextDrawerEvent_descriptor,
        new java.lang.String[] { });
    internal_static_android_studio_SmlConfigurationEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_android_studio_SmlConfigurationEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlConfigurationEventLoggedIn_descriptor,
        new java.lang.String[] { "SmlAvailable", "BotOnboardingStarted", "BotOnboardingCompleted", "CompletionEnabled", "TransformEnabled", "ProjectContextEnabled", "ProductVariant", "AgentAutoAcceptEnabled", });
    internal_static_android_studio_TestScenarioEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_android_studio_TestScenarioEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_TestScenarioEventLoggedIn_descriptor,
        new java.lang.String[] { "Request", "TestScenarioResult", "Transform", });
    internal_static_android_studio_TestScenarioEventLoggedIn_TestScenarioRequest_descriptor =
      internal_static_android_studio_TestScenarioEventLoggedIn_descriptor.getNestedTypes().get(0);
    internal_static_android_studio_TestScenarioEventLoggedIn_TestScenarioRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_TestScenarioEventLoggedIn_TestScenarioRequest_descriptor,
        new java.lang.String[] { });
    internal_static_android_studio_TestScenarioEventLoggedIn_TestScenarioResult_descriptor =
      internal_static_android_studio_TestScenarioEventLoggedIn_descriptor.getNestedTypes().get(1);
    internal_static_android_studio_TestScenarioEventLoggedIn_TestScenarioResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_TestScenarioEventLoggedIn_TestScenarioResult_descriptor,
        new java.lang.String[] { "MisformattedResponseCount", "GenerationType", "NumAccept", "NumDecline", });
    internal_static_android_studio_DeviceConnectedNotificationEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_android_studio_DeviceConnectedNotificationEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_DeviceConnectedNotificationEventLoggedIn_descriptor,
        new java.lang.String[] { });
    internal_static_android_studio_StudioCoreGeminiActionsEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_android_studio_StudioCoreGeminiActionsEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_StudioCoreGeminiActionsEventLoggedIn_descriptor,
        new java.lang.String[] { "Action", "ResultsCount", "ResultsTaken", });
    internal_static_android_studio_StudioLabsEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_android_studio_StudioLabsEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_StudioLabsEventLoggedIn_descriptor,
        new java.lang.String[] { "PageInteraction", });
    internal_static_android_studio_PromptLibraryEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_android_studio_PromptLibraryEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_PromptLibraryEventLoggedIn_descriptor,
        new java.lang.String[] { "Update", "Invoke", });
    internal_static_android_studio_PromptLibraryEventLoggedIn_Update_descriptor =
      internal_static_android_studio_PromptLibraryEventLoggedIn_descriptor.getNestedTypes().get(0);
    internal_static_android_studio_PromptLibraryEventLoggedIn_Update_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_PromptLibraryEventLoggedIn_Update_descriptor,
        new java.lang.String[] { "PromptsInLibrary", "RulesCount", "BuiltinsOverridesCount", "UserPromptsCount", });
    internal_static_android_studio_PromptLibraryEventLoggedIn_Invoke_descriptor =
      internal_static_android_studio_PromptLibraryEventLoggedIn_descriptor.getNestedTypes().get(1);
    internal_static_android_studio_PromptLibraryEventLoggedIn_Invoke_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_PromptLibraryEventLoggedIn_Invoke_descriptor,
        new java.lang.String[] { });
    internal_static_android_studio_JourneyFinishedEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_android_studio_JourneyFinishedEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_JourneyFinishedEventLoggedIn_descriptor,
        new java.lang.String[] { "TestResult", });
    internal_static_android_studio_PlayPolicyInsightsUsageEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_android_studio_PlayPolicyInsightsUsageEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_PlayPolicyInsightsUsageEventLoggedIn_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_android_studio_ModelProviderEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_android_studio_ModelProviderEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_ModelProviderEventLoggedIn_descriptor,
        new java.lang.String[] { "Update", });
    internal_static_android_studio_ModelProviderEventLoggedIn_Update_descriptor =
      internal_static_android_studio_ModelProviderEventLoggedIn_descriptor.getNestedTypes().get(0);
    internal_static_android_studio_ModelProviderEventLoggedIn_Update_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_ModelProviderEventLoggedIn_Update_descriptor,
        new java.lang.String[] { "LocalModelProvidersCount", "RemoteModelProvidersCount", "GeminiModelProvidersCount", });
    internal_static_android_studio_NextEditPredictionEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_android_studio_NextEditPredictionEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_NextEditPredictionEventLoggedIn_descriptor,
        new java.lang.String[] { "Shown", "Accepted", "Session", "NextEditPrediction", });
    internal_static_android_studio_NextEditPredictionEventLoggedIn_PredictionShown_descriptor =
      internal_static_android_studio_NextEditPredictionEventLoggedIn_descriptor.getNestedTypes().get(0);
    internal_static_android_studio_NextEditPredictionEventLoggedIn_PredictionShown_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_NextEditPredictionEventLoggedIn_PredictionShown_descriptor,
        new java.lang.String[] { });
    internal_static_android_studio_NextEditPredictionEventLoggedIn_PredictionAccepted_descriptor =
      internal_static_android_studio_NextEditPredictionEventLoggedIn_descriptor.getNestedTypes().get(1);
    internal_static_android_studio_NextEditPredictionEventLoggedIn_PredictionAccepted_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_NextEditPredictionEventLoggedIn_PredictionAccepted_descriptor,
        new java.lang.String[] { });
    internal_static_android_studio_NextEditPredictionEventLoggedIn_Session_descriptor =
      internal_static_android_studio_NextEditPredictionEventLoggedIn_descriptor.getNestedTypes().get(2);
    internal_static_android_studio_NextEditPredictionEventLoggedIn_Session_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_NextEditPredictionEventLoggedIn_Session_descriptor,
        new java.lang.String[] { "Events", });
    internal_static_android_studio_NextEditPredictionEventLoggedIn_Session_SessionEvent_descriptor =
      internal_static_android_studio_NextEditPredictionEventLoggedIn_Session_descriptor.getNestedTypes().get(0);
    internal_static_android_studio_NextEditPredictionEventLoggedIn_Session_SessionEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_NextEditPredictionEventLoggedIn_Session_SessionEvent_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_android_studio_SkillsEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_android_studio_SkillsEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SkillsEventLoggedIn_descriptor,
        new java.lang.String[] { "Metadata", "Activation", "Event", });
    internal_static_android_studio_SkillsEventLoggedIn_Activation_descriptor =
      internal_static_android_studio_SkillsEventLoggedIn_descriptor.getNestedTypes().get(0);
    internal_static_android_studio_SkillsEventLoggedIn_Activation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SkillsEventLoggedIn_Activation_descriptor,
        new java.lang.String[] { "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
