// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats_logged_in.proto

package com.google.wireless.android.sdk.stats;

public final class AndroidStudioStatsLoggedIn {
  private AndroidStudioStatsLoggedIn() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_AndroidStudioEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_AndroidStudioEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_UIActionStatsLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_UIActionStatsLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_AppLinksAssistantEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_AppLinksAssistantEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_AppLinksAssistantEventLoggedIn_ValidationSummary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_AppLinksAssistantEventLoggedIn_ValidationSummary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_AppLinksAssistantEventLoggedIn_IntentFilterFix_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_AppLinksAssistantEventLoggedIn_IntentFilterFix_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_AppQualityInsightsUsageEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_AppQualityInsightsUsageEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_AppQualityInsightsUsageEventLoggedIn_InsightFetchDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_AppQualityInsightsUsageEventLoggedIn_InsightFetchDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_GoogleLoginPluginEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_GoogleLoginPluginEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_DirectAccessUsageEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_DirectAccessUsageEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_DirectAccessUsageEventLoggedIn_ReserveDeviceDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_DirectAccessUsageEventLoggedIn_ReserveDeviceDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_DirectAccessUsageEventLoggedIn_ConnectDeviceDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_DirectAccessUsageEventLoggedIn_ConnectDeviceDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_DirectAccessUsageEventLoggedIn_StreamStartedDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_DirectAccessUsageEventLoggedIn_StreamStartedDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_TSdkUAEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_TSdkUAEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlResponseMetadataLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlResponseMetadataLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlCompletionEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlCompletionEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlCompletionEventLoggedIn_CompletionAggregateEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlCompletionEventLoggedIn_CompletionAggregateEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlTransformEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlTransformEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlTransformEventLoggedIn_TransformRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlTransformEventLoggedIn_TransformResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformShown_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlTransformEventLoggedIn_TransformShown_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformAccepted_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlTransformEventLoggedIn_TransformAccepted_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformRejected_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlTransformEventLoggedIn_TransformRejected_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlChatBotEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlChatBotEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlChatBotEventLoggedIn_BotResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlChatBotEventLoggedIn_BotResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlChatBotEventLoggedIn_ActionInvoked_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlChatBotEventLoggedIn_ActionInvoked_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlChatBotEventLoggedIn_QueryBoxEventMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlChatBotEventLoggedIn_QueryBoxEventMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlChatBotEventLoggedIn_QueryBoxEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlChatBotEventLoggedIn_QueryBoxEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlChatBotEventLoggedIn_ContextDrawerEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlChatBotEventLoggedIn_ContextDrawerEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SmlConfigurationEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SmlConfigurationEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_TestScenarioEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_TestScenarioEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_TestScenarioEventLoggedIn_TestScenarioRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_TestScenarioEventLoggedIn_TestScenarioRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_TestScenarioEventLoggedIn_TestScenarioResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_TestScenarioEventLoggedIn_TestScenarioResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_DeviceConnectedNotificationEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_DeviceConnectedNotificationEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_StudioCoreGeminiActionsEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_StudioCoreGeminiActionsEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_StudioLabsEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_StudioLabsEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_PromptLibraryEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_PromptLibraryEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_PromptLibraryEventLoggedIn_Update_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_PromptLibraryEventLoggedIn_Update_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_PromptLibraryEventLoggedIn_Invoke_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_PromptLibraryEventLoggedIn_Invoke_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_JourneyFinishedEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_JourneyFinishedEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_PlayPolicyInsightsUsageEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_PlayPolicyInsightsUsageEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_ModelProviderEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_ModelProviderEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_ModelProviderEventLoggedIn_Update_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_ModelProviderEventLoggedIn_Update_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_NextEditPredictionEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_NextEditPredictionEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_NextEditPredictionEventLoggedIn_PredictionShown_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_NextEditPredictionEventLoggedIn_PredictionShown_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_NextEditPredictionEventLoggedIn_PredictionAccepted_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_NextEditPredictionEventLoggedIn_PredictionAccepted_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_NextEditPredictionEventLoggedIn_Session_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_NextEditPredictionEventLoggedIn_Session_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_NextEditPredictionEventLoggedIn_Session_SessionEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_NextEditPredictionEventLoggedIn_Session_SessionEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SkillsEventLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SkillsEventLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_SkillsEventLoggedIn_Activation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_studio_SkillsEventLoggedIn_Activation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034studio_stats_logged_in.proto\022\016android_" +
      "studio\"\215\r\n\032AndroidStudioEventLoggedIn\022B\n" +
      "\017ui_action_stats\030\" \001(\0132%.android_studio." +
      "UIActionStatsLoggedInB\002(\001\022U\n\031app_links_a" +
      "ssistant_event\030+ \001(\0132..android_studio.Ap" +
      "pLinksAssistantEventLoggedInB\002(\001\022c\n app_" +
      "quality_insights_usage_event\030\223\001 \001(\01324.an" +
      "droid_studio.AppQualityInsightsUsageEven" +
      "tLoggedInB\002(\001\022O\n\022google_login_event\030\224\001 \001" +
      "(\0132..android_studio.GoogleLoginPluginEve" +
      "ntLoggedInB\002(\001\022V\n\031direct_access_usage_ev" +
      "ent\030\236\001 \001(\0132..android_studio.DirectAccess" +
      "UsageEventLoggedInB\002(\001\022?\n\rtsdk_ua_event\030" +
      "\240\001 \001(\0132#.android_studio.TSdkUAEventLogge" +
      "dInB\002(\001\022M\n\024sml_completion_event\030\247\001 \001(\0132*" +
      ".android_studio.SmlCompletionEventLogged" +
      "InB\002(\001\022K\n\023sml_transform_event\030\250\001 \001(\0132).a" +
      "ndroid_studio.SmlTransformEventLoggedInB" +
      "\002(\001\022H\n\022sml_chat_bot_event\030\251\001 \001(\0132\'.andro" +
      "id_studio.SmlChatBotEventLoggedInB\002(\001\022S\n" +
      "\027sml_configuration_event\030\252\001 \001(\0132-.androi" +
      "d_studio.SmlConfigurationEventLoggedInB\002" +
      "(\001\022W\n\020device_connected\030\277\001 \001(\01328.android_" +
      "studio.DeviceConnectedNotificationEventL" +
      "oggedInB\002(\001\022K\n\023test_scenario_event\030\301\001 \001(" +
      "\0132).android_studio.TestScenarioEventLogg" +
      "edInB\002(\001\022k\n(android_studio_core_gemini_a" +
      "ctions_event\030\317\001 \001(\01324.android_studio.Stu" +
      "dioCoreGeminiActionsEventLoggedInB\002(\001\022G\n" +
      "\021studio_labs_event\030\323\001 \001(\0132\'.android_stud" +
      "io.StudioLabsEventLoggedInB\002(\001\022M\n\024prompt" +
      "_library_event\030\324\001 \001(\0132*.android_studio.P" +
      "romptLibraryEventLoggedInB\002(\001\022Q\n\026journey" +
      "_finished_event\030\343\001 \001(\0132,.android_studio." +
      "JourneyFinishedEventLoggedInB\002(\001\022c\n play" +
      "_policy_insights_usage_event\030\354\001 \001(\01324.an" +
      "droid_studio.PlayPolicyInsightsUsageEven" +
      "tLoggedInB\002(\001\022M\n\024model_provider_event\030\355\001" +
      " \001(\0132*.android_studio.ModelProviderEvent" +
      "LoggedInB\002(\001\022X\n\032next_edit_prediction_eve" +
      "nt\030\361\001 \001(\0132/.android_studio.NextEditPredi" +
      "ctionEventLoggedInB\002(\001\022>\n\014skills_event\030\371" +
      "\001 \001(\0132#.android_studio.SkillsEventLogged" +
      "InB\002(\001\"2\n\025UIActionStatsLoggedIn\022\031\n\021actio" +
      "n_class_name\030\001 \001(\t\"\300\003\n\036AppLinksAssistant" +
      "EventLoggedIn\022P\n\014event_source\030\003 \001(\0162:.an" +
      "droid_studio.AppLinksAssistantEventLogge" +
      "dIn.EventSource\022`\n\022validation_summary\030\013 " +
      "\001(\0132@.android_studio.AppLinksAssistantEv" +
      "entLoggedIn.ValidationSummaryB\002(\001\022]\n\021int" +
      "ent_filter_fix\030\014 \001(\0132>.android_studio.Ap" +
      "pLinksAssistantEventLoggedIn.IntentFilte" +
      "rFixB\002(\001\032\023\n\021ValidationSummary\032\021\n\017IntentF" +
      "ilterFix\"c\n\013EventSource\022\022\n\016UNKNOWN_SOURC" +
      "E\020\000\022 \n\034NEW_LINK_CREATION_SIDE_PANEL\020\024\022\036\n" +
      "\032LAUNCH_APP_LINKS_ASSISTANT\020(\"\362\002\n$AppQua" +
      "lityInsightsUsageEventLoggedIn\022k\n\025insigh" +
      "t_fetch_details\030\022 \001(\0132H.android_studio.A" +
      "ppQualityInsightsUsageEventLoggedIn.Insi" +
      "ghtFetchDetailsB\002(\001\032k\n\023InsightFetchDetai" +
      "ls\022T\n\006source\030\004 \001(\0162D.android_studio.AppQ" +
      "ualityInsightsUsageEventLoggedIn.AiInsig" +
      "htSource\"p\n\017AiInsightSource\022\022\n\016UNKNOWN_S" +
      "OURCE\020\000\022 \n\034AI_INSIGHT_SOURCE_STUDIO_BOT\020" +
      "\001\022\'\n#AI_INSIGHT_SOURCE_CRASHLYTICS_TITAN" +
      "\020\002\"\234\004\n\036GoogleLoginPluginEventLoggedIn\022G\n" +
      "\005event\030\001 \001(\01628.android_studio.GoogleLogi" +
      "nPluginEventLoggedIn.EventKind\022L\n\nlogin_" +
      "type\030\003 \001(\01628.android_studio.GoogleLoginP" +
      "luginEventLoggedIn.LoginType\"\327\001\n\tEventKi" +
      "nd\022\026\n\022UNKNOWN_EVENT_TYPE\020\000\022\026\n\022LOGIN_WITH" +
      "_SUCCESS\020\001\022\026\n\022LOGIN_WITH_FAILURE\020\002\022\020\n\014FO" +
      "RCE_LOGOUT\020\003\022\027\n\023LOGOUT_WITH_SUCCESS\020\005\022\027\n" +
      "\023LOGOUT_WITH_FAILURE\020\006\022\035\n\031LOGGED_IN_ON_S" +
      "TUDIO_START\020\007\022\037\n\033STARTUP_SIGNIN_DIALOG_S" +
      "HOWN\020\010\"\210\001\n\tLoginType\022\020\n\014UNKNOWN_TYPE\020\000\022\022" +
      "\n\016COMBINED_LOGIN\020\001\022\021\n\rFEATURE_LOGIN\020\002\022!\n" +
      "\035AUTH_ERROR_NOTIFICATION_LOGIN\020\003\022\037\n\033STAR" +
      "TUP_SIGNIN_DIALOG_LOGIN\020\004\"\216\006\n\036DirectAcce" +
      "ssUsageEventLoggedIn\022W\n\004type\030\001 \001(\0162I.and" +
      "roid_studio.DirectAccessUsageEventLogged" +
      "In.DirectAccessUsageEventType\022g\n\026reserve" +
      "_device_details\030\003 \001(\0132C.android_studio.D" +
      "irectAccessUsageEventLoggedIn.ReserveDev" +
      "iceDetailsB\002(\001\022g\n\026connect_device_details" +
      "\030\004 \001(\0132C.android_studio.DirectAccessUsag" +
      "eEventLoggedIn.ConnectDeviceDetailsB\002(\001\022" +
      "g\n\026stream_started_details\030\005 \001(\0132C.androi" +
      "d_studio.DirectAccessUsageEventLoggedIn." +
      "StreamStartedDetailsB\002(\001\032\'\n\024ReserveDevic" +
      "eDetails\022\017\n\007success\030\001 \001(\010\032\'\n\024ConnectDevi" +
      "ceDetails\022\017\n\007success\030\001 \001(\010\032\'\n\024StreamStar" +
      "tedDetails\022\017\n\007success\030\001 \001(\010\"\334\001\n\032DirectAc" +
      "cessUsageEventType\022\021\n\rUNKNOWN_EVENT\020\000\022\022\n" +
      "\016RESERVE_DEVICE\020\001\022\022\n\016CONNECT_DEVICE\020\002\022\022\n" +
      "\016STREAM_STARTED\020\003\022\026\n\022EXTEND_RESERVATION\020" +
      "\004\022\023\n\017END_RESERVATION\020\005\022\025\n\021DISCONNECT_DEV" +
      "ICE\020\006\022\027\n\023SERVICE_DEPRECATION\020\007\022\022\n\016OEM_LA" +
      "B_DIALOG\020\010\"\025\n\023TSdkUAEventLoggedIn\"\323\002\n\033Sm" +
      "lResponseMetadataLoggedIn\022\031\n\021model_provi" +
      "der_id\030\004 \001(\t\022\020\n\010model_id\030\005 \001(\t\022T\n\nagent_" +
      "type\030\007 \001(\0162@.android_studio.SmlResponseM" +
      "etadataLoggedIn.SmlAgentTypeLoggedIn\"\260\001\n" +
      "\024SmlAgentTypeLoggedIn\022\032\n\026AGENT_TYPE_UNSP" +
      "ECIFIED\020\000\022\026\n\022AGENT_TYPE_GENERIC\020\001\022\034\n\030AGE" +
      "NT_TYPE_UPGRADE_AGENT\020\002\022 \n\034AGENT_TYPE_NE" +
      "W_PROJECT_AGENT\020\003\022$\n AGENT_TYPE_DEEP_LIN" +
      "K_LOGIC_AGENT\020\004\"\335\001\n\032SmlCompletionEventLo" +
      "ggedIn\022\\\n\taggregate\030\005 \001(\0132C.android_stud" +
      "io.SmlCompletionEventLoggedIn.Completion" +
      "AggregateEventB\002(\001H\000\032S\n\030CompletionAggreg" +
      "ateEvent\022\031\n\021completions_shown\030\004 \001(\005\022\034\n\024c" +
      "ompletions_accepted\030\005 \001(\005B\014\n\ncompletion\"" +
      "\305\005\n\031SmlTransformEventLoggedIn\022Q\n\007request" +
      "\030\001 \001(\0132:.android_studio.SmlTransformEven" +
      "tLoggedIn.TransformRequestB\002(\001H\000\022S\n\010resp" +
      "onse\030\002 \001(\0132;.android_studio.SmlTransform" +
      "EventLoggedIn.TransformResponseB\002(\001H\000\022M\n" +
      "\005shown\030\003 \001(\01328.android_studio.SmlTransfo" +
      "rmEventLoggedIn.TransformShownB\002(\001H\000\022S\n\010" +
      "accepted\030\004 \001(\0132;.android_studio.SmlTrans" +
      "formEventLoggedIn.TransformAcceptedB\002(\001H" +
      "\000\022O\n\016transform_kind\030\005 \001(\01627.android_stud" +
      "io.SmlTransformEventLoggedIn.TransformKi" +
      "nd\032\022\n\020TransformRequest\032\023\n\021TransformRespo" +
      "nse\032\020\n\016TransformShown\032\023\n\021TransformAccept" +
      "ed\032\023\n\021TransformRejected\"\230\001\n\rTransformKin" +
      "d\022\013\n\007UNKNOWN\020\000\022\n\n\006CUSTOM\020\001\022\014\n\010DOCUMENT\020\002" +
      "\022\036\n\032MULTIMODAL_COMPOSE_PREVIEW\020\003\022\034\n\030GENE" +
      "RATE_COMPOSE_PREVIEW\020\004\022\"\n\036GENERATE_INSIG" +
      "HT_SUGGESTED_FIX\020\005B\013\n\ttransform\"\216\r\n\027SmlC" +
      "hatBotEventLoggedIn\022K\n\010response\030\001 \001(\01323." +
      "android_studio.SmlChatBotEventLoggedIn.B" +
      "otResponseB\002(\001H\000\022S\n\016action_invoked\030\003 \001(\013" +
      "25.android_studio.SmlChatBotEventLoggedI" +
      "n.ActionInvokedB\002(\001H\000\022T\n\017query_box_event" +
      "\030\n \001(\01325.android_studio.SmlChatBotEventL" +
      "oggedIn.QueryBoxEventB\002(\001H\000\022^\n\024context_d" +
      "rawer_event\030\013 \001(\0132:.android_studio.SmlCh" +
      "atBotEventLoggedIn.ContextDrawerEventB\002(" +
      "\001H\000\032\225\001\n\013BotResponse\022A\n\010metadata\030\001 \001(\0132+." +
      "android_studio.SmlResponseMetadataLogged" +
      "InB\002(\001\022C\n\tchat_mode\030\004 \001(\01620.android_stud" +
      "io.SmlChatBotEventLoggedIn.ChatMode\032O\n\rA" +
      "ctionInvoked\022>\n\006action\030\002 \001(\0162..android_s" +
      "tudio.SmlChatBotEventLoggedIn.Action\032\364\001\n" +
      "\025QueryBoxEventMetadata\022e\n\017attachment_typ" +
      "e\030\001 \001(\0162L.android_studio.SmlChatBotEvent" +
      "LoggedIn.QueryBoxEventMetadata.Attachmen" +
      "tType\"t\n\016AttachmentType\022\013\n\007UNKNOWN\020\000\022\t\n\005" +
      "FILES\020\001\022\013\n\007FOLDERS\020\002\022\t\n\005TOOLS\020\003\022\022\n\016PROMP" +
      "T_LIBRARY\020\004\022\022\n\016REMOTE_CONTEXT\020\005\022\n\n\006SKILL" +
      "S\020\006\032\265\001\n\rQueryBoxEvent\022M\n\nevent_type\030\001 \001(" +
      "\01629.android_studio.SmlChatBotEventLogged" +
      "In.QueryBoxEventType\022U\n\016event_metadata\030\002" +
      " \001(\0132=.android_studio.SmlChatBotEventLog" +
      "gedIn.QueryBoxEventMetadata\032\024\n\022ContextDr" +
      "awerEvent\"m\n\010ChatMode\022\016\n\nOTHER_MODE\020\000\022\010\n" +
      "\004CHAT\020\001\022\016\n\nAGENT_MODE\020\002\022\031\n\025VERSION_UPGRA" +
      "DE_AGENT\020\003\022\016\n\nQUICK_EDIT\020\004\022\014\n\010PLANNING\020\005" +
      "\"\222\002\n\006Action\022\013\n\007INVALID\020\000\022\022\n\016MOVE_TO_EDIT" +
      "OR\020\001\022\021\n\rMOVE_TO_CARET\020\002\022\024\n\020MOVE_TO_NEW_F" +
      "ILE\020\003\022\022\n\016ADD_DEPENDENCY\020\004\022\020\n\014BROWSE_TOPI" +
      "C\020\005\022\031\n\025EXPLORE_IN_PLAYGROUND\020\006\022\022\n\016MERGE_" +
      "MANIFEST\020\007\022\024\n\020MERGE_SUGGESTION\020\t\022\024\n\020INSE" +
      "RT_RESOURCES\020\n\022\033\n\027INSERT_NAME_SUGGESTION" +
      "S\020\013\022\017\n\013COPY_BUTTON\020\014\022\017\n\013COPY_MANUAL\020\r\"\335\001" +
      "\n\021QueryBoxEventType\022\023\n\017QUERY_BOX_OTHER\020\000" +
      "\022\026\n\022COMPLETION_STARTED\020\001\022\027\n\023COMPLETION_A" +
      "CCEPTED\020\002\022\030\n\024COMPLETION_DISMISSED\020\003\022 \n\034Q" +
      "UERY_WITH_CONTEXT_SUBMITTED\020\004\022\025\n\021REFEREN" +
      "CE_DELETED\020\005\022\034\n\030IMAGE_ATTACHMENT_CLICKED" +
      "\020\006\022\021\n\rQUERY_STOPPED\020\007B\t\n\007content\"\252\004\n\035Sml" +
      "ConfigurationEventLoggedIn\022\025\n\rsml_availa" +
      "ble\030\001 \001(\010\022\036\n\026bot_onboarding_started\030\004 \001(" +
      "\010\022 \n\030bot_onboarding_completed\030\005 \001(\010\022\032\n\022c" +
      "ompletion_enabled\030\002 \001(\010\022\031\n\021transform_ena" +
      "bled\030\003 \001(\010\022\037\n\027project_context_enabled\030\006 " +
      "\001(\010\022X\n\017product_variant\030\007 \001(\0162?.android_s" +
      "tudio.SmlConfigurationEventLoggedIn.SmlP" +
      "roductVariant\022!\n\031agent_auto_accept_enabl" +
      "ed\030\010 \001(\010\"\332\001\n\021SmlProductVariant\022\033\n\027PRODUC" +
      "T_VARIANT_UNKNOWN\020\000\022\030\n\024PRODUCT_VARIANT_F" +
      "REE\020\001\022\034\n\030PRODUCT_VARIANT_BUSINESS\020\002\022*\n\"P" +
      "RODUCT_VARIANT_DASHER_USER_CHOICE\020\003\032\002\010\001\022" +
      "\037\n\033PRODUCT_VARIANT_DASHER_FREE\020\004\022#\n\037PROD" +
      "UCT_VARIANT_DASHER_BUSINESS\020\005\"\201\004\n\031TestSc" +
      "enarioEventLoggedIn\022T\n\007request\030\001 \001(\0132=.a" +
      "ndroid_studio.TestScenarioEventLoggedIn." +
      "TestScenarioRequestB\002(\001H\000\022`\n\024test_scenar" +
      "io_result\030\003 \001(\0132<.android_studio.TestSce" +
      "narioEventLoggedIn.TestScenarioResultB\002(" +
      "\001H\000\032\025\n\023TestScenarioRequest\032\265\001\n\022TestScena" +
      "rioResult\022#\n\033misformatted_response_count" +
      "\030\001 \001(\005\022Q\n\017generation_type\030\002 \001(\01628.androi" +
      "d_studio.TestScenarioEventLoggedIn.Gener" +
      "ationType\022\022\n\nnum_accept\030\003 \001(\005\022\023\n\013num_dec" +
      "line\030\004 \001(\005\"P\n\016GenerationType\022\035\n\031GENERATI" +
      "ON_TYPE_UNDEFINED\020\000\022\014\n\010NEW_FILE\020\001\022\021\n\rEXI" +
      "STING_FILE\020\002B\013\n\ttransform\"*\n(DeviceConne" +
      "ctedNotificationEventLoggedIn\"\205\002\n$Studio" +
      "CoreGeminiActionsEventLoggedIn\022K\n\006action" +
      "\030\001 \001(\0162;.android_studio.StudioCoreGemini" +
      "ActionsEventLoggedIn.Action\022\025\n\rresults_c" +
      "ount\030\005 \001(\005\022\025\n\rresults_taken\030\006 \001(\005\"b\n\006Act" +
      "ion\022\013\n\007UNKNOWN\020\000\022\023\n\017RENAME_VARIABLE\020\001\022\032\n" +
      "\026RETHINK_VARIABLE_NAMES\020\002\022\032\n\026SUGGEST_COM" +
      "MIT_MESSAGE\020\003\"\361\001\n\027StudioLabsEventLoggedI" +
      "n\022Q\n\020page_interaction\030\002 \001(\01627.android_st" +
      "udio.StudioLabsEventLoggedIn.PageInterac" +
      "tion\"\202\001\n\017PageInteraction\022\027\n\023UNKNOWN_INTE" +
      "RACTION\020\000\022\n\n\006OPENED\020\001\022\030\n\024APPLY_BUTTON_CL" +
      "ICKED\020\002\022\031\n\025CANCEL_BUTTON_CLICKED\020\003\022\025\n\021OK" +
      "_BUTTON_CLICKED\020\004\"\245\002\n\032PromptLibraryEvent" +
      "LoggedIn\022A\n\006update\030\001 \001(\01321.android_studi" +
      "o.PromptLibraryEventLoggedIn.Update\022A\n\006i" +
      "nvoke\030\002 \001(\01321.android_studio.PromptLibra" +
      "ryEventLoggedIn.Invoke\032w\n\006Update\022\032\n\022prom" +
      "pts_in_library\030\001 \001(\005\022\023\n\013rules_count\030\002 \001(" +
      "\005\022 \n\030builtins_overrides_count\030\003 \001(\005\022\032\n\022u" +
      "ser_prompts_count\030\004 \001(\005\032\010\n\006Invoke\"\272\001\n\034Jo" +
      "urneyFinishedEventLoggedIn\022L\n\013test_resul" +
      "t\030\001 \001(\01627.android_studio.JourneyFinished" +
      "EventLoggedIn.TestResult\"L\n\nTestResult\022\013" +
      "\n\007UNKNOWN\020\000\022\n\n\006PASSED\020\001\022\n\n\006FAILED\020\002\022\013\n\007A" +
      "BORTED\020\003\022\014\n\010CANCELED\020\004\"\361\001\n$PlayPolicyIns" +
      "ightsUsageEventLoggedIn\022c\n\004type\030\001 \001(\0162U." +
      "android_studio.PlayPolicyInsightsUsageEv" +
      "entLoggedIn.PlayPolicyInsightsUsageEvent" +
      "Type\"d\n PlayPolicyInsightsUsageEventType" +
      "\022\021\n\rUNKNOWN_EVENT\020\000\022\027\n\023SERVICE_DEPRECATI" +
      "ON\020\001\022\024\n\020BATCH_INSPECTION\020\002\"\332\001\n\032ModelProv" +
      "iderEventLoggedIn\022A\n\006update\030\001 \001(\01321.andr" +
      "oid_studio.ModelProviderEventLoggedIn.Up" +
      "date\032y\n\006Update\022#\n\033local_model_providers_" +
      "count\030\001 \001(\005\022$\n\034remote_model_providers_co" +
      "unt\030\002 \001(\005\022$\n\034gemini_model_providers_coun" +
      "t\030\003 \001(\005\"\352\006\n\037NextEditPredictionEventLogge" +
      "dIn\022T\n\005shown\030\001 \001(\0132?.android_studio.Next" +
      "EditPredictionEventLoggedIn.PredictionSh" +
      "ownB\002(\001H\000\022Z\n\010accepted\030\002 \001(\0132B.android_st" +
      "udio.NextEditPredictionEventLoggedIn.Pre" +
      "dictionAcceptedB\002(\001H\000\022N\n\007session\030\006 \001(\01327" +
      ".android_studio.NextEditPredictionEventL" +
      "oggedIn.SessionB\002(\001H\000\032\021\n\017PredictionShown" +
      "\032\024\n\022PredictionAccepted\032\203\004\n\007Session\022T\n\006ev" +
      "ents\030\005 \003(\0132D.android_studio.NextEditPred" +
      "ictionEventLoggedIn.Session.SessionEvent" +
      "\032\241\003\n\014SessionEvent\022\\\n\004type\030\001 \001(\0162N.androi" +
      "d_studio.NextEditPredictionEventLoggedIn" +
      ".Session.SessionEvent.EventType\"\262\002\n\tEven" +
      "tType\022\026\n\022UNKNOWN_EVENT_TYPE\020\000\022\020\n\014REQUEST" +
      "_SENT\020\001\022\025\n\021RESPONSE_RECEIVED\020\002\022\024\n\020PREDIC" +
      "TION_SHOWN\020\003\022\027\n\023PREDICTION_ACCEPTED\020\004\022\027\n" +
      "\023PREDICTION_REJECTED\020\005\022\025\n\021SESSION_CANCEL" +
      "LED\020\006\022\021\n\rCONTROL_SHOWN\020\007\022\024\n\020CONTROL_ACCE" +
      "PTED\020\010\022\024\n\020CONTROL_REJECTED\020\t\022\022\n\016CONTROL_" +
      "HIDDEN\020\n\022\025\n\021PREDICTION_FAILED\020\013\022\033\n\027CONTR" +
      "OL_DISPOSED_UNSEEN\020\014B\026\n\024next_edit_predic" +
      "tion\"\261\002\n\023SkillsEventLoggedIn\022A\n\010metadata" +
      "\030\001 \001(\0132+.android_studio.SmlResponseMetad" +
      "ataLoggedInB\002(\001\022H\n\nactivation\030\002 \001(\0132..an" +
      "droid_studio.SkillsEventLoggedIn.Activat" +
      "ionB\002(\001H\000\032I\n\nActivation\022;\n\004type\030\001 \001(\0162-." +
      "android_studio.SkillsEventLoggedIn.Skill" +
      "Type\"9\n\tSkillType\022\013\n\007UNKNOWN\020\000\022\r\n\tPRE_BU" +
      "ILT\020\001\022\020\n\014USER_DEFINED\020\002B\007\n\005eventBE\n%com." +
      "google.wireless.android.sdk.statsB\032Andro" +
      "idStudioStatsLoggedInP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_android_studio_AndroidStudioEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_android_studio_AndroidStudioEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_AndroidStudioEventLoggedIn_descriptor,
        new java.lang.String[] { "UiActionStats", "AppLinksAssistantEvent", "AppQualityInsightsUsageEvent", "GoogleLoginEvent", "DirectAccessUsageEvent", "TsdkUaEvent", "SmlCompletionEvent", "SmlTransformEvent", "SmlChatBotEvent", "SmlConfigurationEvent", "DeviceConnected", "TestScenarioEvent", "AndroidStudioCoreGeminiActionsEvent", "StudioLabsEvent", "PromptLibraryEvent", "JourneyFinishedEvent", "PlayPolicyInsightsUsageEvent", "ModelProviderEvent", "NextEditPredictionEvent", "SkillsEvent", });
    internal_static_android_studio_UIActionStatsLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_android_studio_UIActionStatsLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_UIActionStatsLoggedIn_descriptor,
        new java.lang.String[] { "ActionClassName", });
    internal_static_android_studio_AppLinksAssistantEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_android_studio_AppLinksAssistantEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_AppLinksAssistantEventLoggedIn_descriptor,
        new java.lang.String[] { "EventSource", "ValidationSummary", "IntentFilterFix", });
    internal_static_android_studio_AppLinksAssistantEventLoggedIn_ValidationSummary_descriptor =
      internal_static_android_studio_AppLinksAssistantEventLoggedIn_descriptor.getNestedTypes().get(0);
    internal_static_android_studio_AppLinksAssistantEventLoggedIn_ValidationSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_AppLinksAssistantEventLoggedIn_ValidationSummary_descriptor,
        new java.lang.String[] { });
    internal_static_android_studio_AppLinksAssistantEventLoggedIn_IntentFilterFix_descriptor =
      internal_static_android_studio_AppLinksAssistantEventLoggedIn_descriptor.getNestedTypes().get(1);
    internal_static_android_studio_AppLinksAssistantEventLoggedIn_IntentFilterFix_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_AppLinksAssistantEventLoggedIn_IntentFilterFix_descriptor,
        new java.lang.String[] { });
    internal_static_android_studio_AppQualityInsightsUsageEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_android_studio_AppQualityInsightsUsageEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_AppQualityInsightsUsageEventLoggedIn_descriptor,
        new java.lang.String[] { "InsightFetchDetails", });
    internal_static_android_studio_AppQualityInsightsUsageEventLoggedIn_InsightFetchDetails_descriptor =
      internal_static_android_studio_AppQualityInsightsUsageEventLoggedIn_descriptor.getNestedTypes().get(0);
    internal_static_android_studio_AppQualityInsightsUsageEventLoggedIn_InsightFetchDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_AppQualityInsightsUsageEventLoggedIn_InsightFetchDetails_descriptor,
        new java.lang.String[] { "Source", });
    internal_static_android_studio_GoogleLoginPluginEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_android_studio_GoogleLoginPluginEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_GoogleLoginPluginEventLoggedIn_descriptor,
        new java.lang.String[] { "Event", "LoginType", });
    internal_static_android_studio_DirectAccessUsageEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_android_studio_DirectAccessUsageEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_DirectAccessUsageEventLoggedIn_descriptor,
        new java.lang.String[] { "Type", "ReserveDeviceDetails", "ConnectDeviceDetails", "StreamStartedDetails", });
    internal_static_android_studio_DirectAccessUsageEventLoggedIn_ReserveDeviceDetails_descriptor =
      internal_static_android_studio_DirectAccessUsageEventLoggedIn_descriptor.getNestedTypes().get(0);
    internal_static_android_studio_DirectAccessUsageEventLoggedIn_ReserveDeviceDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_DirectAccessUsageEventLoggedIn_ReserveDeviceDetails_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_android_studio_DirectAccessUsageEventLoggedIn_ConnectDeviceDetails_descriptor =
      internal_static_android_studio_DirectAccessUsageEventLoggedIn_descriptor.getNestedTypes().get(1);
    internal_static_android_studio_DirectAccessUsageEventLoggedIn_ConnectDeviceDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_DirectAccessUsageEventLoggedIn_ConnectDeviceDetails_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_android_studio_DirectAccessUsageEventLoggedIn_StreamStartedDetails_descriptor =
      internal_static_android_studio_DirectAccessUsageEventLoggedIn_descriptor.getNestedTypes().get(2);
    internal_static_android_studio_DirectAccessUsageEventLoggedIn_StreamStartedDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_DirectAccessUsageEventLoggedIn_StreamStartedDetails_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_android_studio_TSdkUAEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_android_studio_TSdkUAEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_TSdkUAEventLoggedIn_descriptor,
        new java.lang.String[] { });
    internal_static_android_studio_SmlResponseMetadataLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_android_studio_SmlResponseMetadataLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlResponseMetadataLoggedIn_descriptor,
        new java.lang.String[] { "ModelProviderId", "ModelId", "AgentType", });
    internal_static_android_studio_SmlCompletionEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_android_studio_SmlCompletionEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlCompletionEventLoggedIn_descriptor,
        new java.lang.String[] { "Aggregate", "Completion", });
    internal_static_android_studio_SmlCompletionEventLoggedIn_CompletionAggregateEvent_descriptor =
      internal_static_android_studio_SmlCompletionEventLoggedIn_descriptor.getNestedTypes().get(0);
    internal_static_android_studio_SmlCompletionEventLoggedIn_CompletionAggregateEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlCompletionEventLoggedIn_CompletionAggregateEvent_descriptor,
        new java.lang.String[] { "CompletionsShown", "CompletionsAccepted", });
    internal_static_android_studio_SmlTransformEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_android_studio_SmlTransformEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlTransformEventLoggedIn_descriptor,
        new java.lang.String[] { "Request", "Response", "Shown", "Accepted", "TransformKind", "Transform", });
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformRequest_descriptor =
      internal_static_android_studio_SmlTransformEventLoggedIn_descriptor.getNestedTypes().get(0);
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlTransformEventLoggedIn_TransformRequest_descriptor,
        new java.lang.String[] { });
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformResponse_descriptor =
      internal_static_android_studio_SmlTransformEventLoggedIn_descriptor.getNestedTypes().get(1);
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlTransformEventLoggedIn_TransformResponse_descriptor,
        new java.lang.String[] { });
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformShown_descriptor =
      internal_static_android_studio_SmlTransformEventLoggedIn_descriptor.getNestedTypes().get(2);
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformShown_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlTransformEventLoggedIn_TransformShown_descriptor,
        new java.lang.String[] { });
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformAccepted_descriptor =
      internal_static_android_studio_SmlTransformEventLoggedIn_descriptor.getNestedTypes().get(3);
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformAccepted_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlTransformEventLoggedIn_TransformAccepted_descriptor,
        new java.lang.String[] { });
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformRejected_descriptor =
      internal_static_android_studio_SmlTransformEventLoggedIn_descriptor.getNestedTypes().get(4);
    internal_static_android_studio_SmlTransformEventLoggedIn_TransformRejected_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlTransformEventLoggedIn_TransformRejected_descriptor,
        new java.lang.String[] { });
    internal_static_android_studio_SmlChatBotEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_android_studio_SmlChatBotEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlChatBotEventLoggedIn_descriptor,
        new java.lang.String[] { "Response", "ActionInvoked", "QueryBoxEvent", "ContextDrawerEvent", "Content", });
    internal_static_android_studio_SmlChatBotEventLoggedIn_BotResponse_descriptor =
      internal_static_android_studio_SmlChatBotEventLoggedIn_descriptor.getNestedTypes().get(0);
    internal_static_android_studio_SmlChatBotEventLoggedIn_BotResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlChatBotEventLoggedIn_BotResponse_descriptor,
        new java.lang.String[] { "Metadata", "ChatMode", });
    internal_static_android_studio_SmlChatBotEventLoggedIn_ActionInvoked_descriptor =
      internal_static_android_studio_SmlChatBotEventLoggedIn_descriptor.getNestedTypes().get(1);
    internal_static_android_studio_SmlChatBotEventLoggedIn_ActionInvoked_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlChatBotEventLoggedIn_ActionInvoked_descriptor,
        new java.lang.String[] { "Action", });
    internal_static_android_studio_SmlChatBotEventLoggedIn_QueryBoxEventMetadata_descriptor =
      internal_static_android_studio_SmlChatBotEventLoggedIn_descriptor.getNestedTypes().get(2);
    internal_static_android_studio_SmlChatBotEventLoggedIn_QueryBoxEventMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlChatBotEventLoggedIn_QueryBoxEventMetadata_descriptor,
        new java.lang.String[] { "AttachmentType", });
    internal_static_android_studio_SmlChatBotEventLoggedIn_QueryBoxEvent_descriptor =
      internal_static_android_studio_SmlChatBotEventLoggedIn_descriptor.getNestedTypes().get(3);
    internal_static_android_studio_SmlChatBotEventLoggedIn_QueryBoxEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlChatBotEventLoggedIn_QueryBoxEvent_descriptor,
        new java.lang.String[] { "EventType", "EventMetadata", });
    internal_static_android_studio_SmlChatBotEventLoggedIn_ContextDrawerEvent_descriptor =
      internal_static_android_studio_SmlChatBotEventLoggedIn_descriptor.getNestedTypes().get(4);
    internal_static_android_studio_SmlChatBotEventLoggedIn_ContextDrawerEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlChatBotEventLoggedIn_ContextDrawerEvent_descriptor,
        new java.lang.String[] { });
    internal_static_android_studio_SmlConfigurationEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_android_studio_SmlConfigurationEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SmlConfigurationEventLoggedIn_descriptor,
        new java.lang.String[] { "SmlAvailable", "BotOnboardingStarted", "BotOnboardingCompleted", "CompletionEnabled", "TransformEnabled", "ProjectContextEnabled", "ProductVariant", "AgentAutoAcceptEnabled", });
    internal_static_android_studio_TestScenarioEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_android_studio_TestScenarioEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_TestScenarioEventLoggedIn_descriptor,
        new java.lang.String[] { "Request", "TestScenarioResult", "Transform", });
    internal_static_android_studio_TestScenarioEventLoggedIn_TestScenarioRequest_descriptor =
      internal_static_android_studio_TestScenarioEventLoggedIn_descriptor.getNestedTypes().get(0);
    internal_static_android_studio_TestScenarioEventLoggedIn_TestScenarioRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_TestScenarioEventLoggedIn_TestScenarioRequest_descriptor,
        new java.lang.String[] { });
    internal_static_android_studio_TestScenarioEventLoggedIn_TestScenarioResult_descriptor =
      internal_static_android_studio_TestScenarioEventLoggedIn_descriptor.getNestedTypes().get(1);
    internal_static_android_studio_TestScenarioEventLoggedIn_TestScenarioResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_TestScenarioEventLoggedIn_TestScenarioResult_descriptor,
        new java.lang.String[] { "MisformattedResponseCount", "GenerationType", "NumAccept", "NumDecline", });
    internal_static_android_studio_DeviceConnectedNotificationEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_android_studio_DeviceConnectedNotificationEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_DeviceConnectedNotificationEventLoggedIn_descriptor,
        new java.lang.String[] { });
    internal_static_android_studio_StudioCoreGeminiActionsEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_android_studio_StudioCoreGeminiActionsEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_StudioCoreGeminiActionsEventLoggedIn_descriptor,
        new java.lang.String[] { "Action", "ResultsCount", "ResultsTaken", });
    internal_static_android_studio_StudioLabsEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_android_studio_StudioLabsEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_StudioLabsEventLoggedIn_descriptor,
        new java.lang.String[] { "PageInteraction", });
    internal_static_android_studio_PromptLibraryEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_android_studio_PromptLibraryEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_PromptLibraryEventLoggedIn_descriptor,
        new java.lang.String[] { "Update", "Invoke", });
    internal_static_android_studio_PromptLibraryEventLoggedIn_Update_descriptor =
      internal_static_android_studio_PromptLibraryEventLoggedIn_descriptor.getNestedTypes().get(0);
    internal_static_android_studio_PromptLibraryEventLoggedIn_Update_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_PromptLibraryEventLoggedIn_Update_descriptor,
        new java.lang.String[] { "PromptsInLibrary", "RulesCount", "BuiltinsOverridesCount", "UserPromptsCount", });
    internal_static_android_studio_PromptLibraryEventLoggedIn_Invoke_descriptor =
      internal_static_android_studio_PromptLibraryEventLoggedIn_descriptor.getNestedTypes().get(1);
    internal_static_android_studio_PromptLibraryEventLoggedIn_Invoke_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_PromptLibraryEventLoggedIn_Invoke_descriptor,
        new java.lang.String[] { });
    internal_static_android_studio_JourneyFinishedEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_android_studio_JourneyFinishedEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_JourneyFinishedEventLoggedIn_descriptor,
        new java.lang.String[] { "TestResult", });
    internal_static_android_studio_PlayPolicyInsightsUsageEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_android_studio_PlayPolicyInsightsUsageEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_PlayPolicyInsightsUsageEventLoggedIn_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_android_studio_ModelProviderEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_android_studio_ModelProviderEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_ModelProviderEventLoggedIn_descriptor,
        new java.lang.String[] { "Update", });
    internal_static_android_studio_ModelProviderEventLoggedIn_Update_descriptor =
      internal_static_android_studio_ModelProviderEventLoggedIn_descriptor.getNestedTypes().get(0);
    internal_static_android_studio_ModelProviderEventLoggedIn_Update_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_ModelProviderEventLoggedIn_Update_descriptor,
        new java.lang.String[] { "LocalModelProvidersCount", "RemoteModelProvidersCount", "GeminiModelProvidersCount", });
    internal_static_android_studio_NextEditPredictionEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_android_studio_NextEditPredictionEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_NextEditPredictionEventLoggedIn_descriptor,
        new java.lang.String[] { "Shown", "Accepted", "Session", "NextEditPrediction", });
    internal_static_android_studio_NextEditPredictionEventLoggedIn_PredictionShown_descriptor =
      internal_static_android_studio_NextEditPredictionEventLoggedIn_descriptor.getNestedTypes().get(0);
    internal_static_android_studio_NextEditPredictionEventLoggedIn_PredictionShown_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_NextEditPredictionEventLoggedIn_PredictionShown_descriptor,
        new java.lang.String[] { });
    internal_static_android_studio_NextEditPredictionEventLoggedIn_PredictionAccepted_descriptor =
      internal_static_android_studio_NextEditPredictionEventLoggedIn_descriptor.getNestedTypes().get(1);
    internal_static_android_studio_NextEditPredictionEventLoggedIn_PredictionAccepted_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_NextEditPredictionEventLoggedIn_PredictionAccepted_descriptor,
        new java.lang.String[] { });
    internal_static_android_studio_NextEditPredictionEventLoggedIn_Session_descriptor =
      internal_static_android_studio_NextEditPredictionEventLoggedIn_descriptor.getNestedTypes().get(2);
    internal_static_android_studio_NextEditPredictionEventLoggedIn_Session_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_NextEditPredictionEventLoggedIn_Session_descriptor,
        new java.lang.String[] { "Events", });
    internal_static_android_studio_NextEditPredictionEventLoggedIn_Session_SessionEvent_descriptor =
      internal_static_android_studio_NextEditPredictionEventLoggedIn_Session_descriptor.getNestedTypes().get(0);
    internal_static_android_studio_NextEditPredictionEventLoggedIn_Session_SessionEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_NextEditPredictionEventLoggedIn_Session_SessionEvent_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_android_studio_SkillsEventLoggedIn_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_android_studio_SkillsEventLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SkillsEventLoggedIn_descriptor,
        new java.lang.String[] { "Metadata", "Activation", "Event", });
    internal_static_android_studio_SkillsEventLoggedIn_Activation_descriptor =
      internal_static_android_studio_SkillsEventLoggedIn_descriptor.getNestedTypes().get(0);
    internal_static_android_studio_SkillsEventLoggedIn_Activation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_studio_SkillsEventLoggedIn_Activation_descriptor,
        new java.lang.String[] { "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
