// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats_logged_in.proto

package com.google.wireless.android.sdk.stats;

public interface GoogleLoginPluginEventLoggedInOrBuilder extends
    // @@protoc_insertion_point(interface_extends:android_studio.GoogleLoginPluginEventLoggedIn)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .android_studio.GoogleLoginPluginEventLoggedIn.EventKind event = 1;</code>
   * @return Whether the event field is set.
   */
  boolean hasEvent();
  /**
   * <code>optional .android_studio.GoogleLoginPluginEventLoggedIn.EventKind event = 1;</code>
   * @return The event.
   */
  com.google.wireless.android.sdk.stats.GoogleLoginPluginEventLoggedIn.EventKind getEvent();

  /**
   * <code>optional .android_studio.GoogleLoginPluginEventLoggedIn.LoginType login_type = 3;</code>
   * @return Whether the loginType field is set.
   */
  boolean hasLoginType();
  /**
   * <code>optional .android_studio.GoogleLoginPluginEventLoggedIn.LoginType login_type = 3;</code>
   * @return The loginType.
   */
  com.google.wireless.android.sdk.stats.GoogleLoginPluginEventLoggedIn.LoginType getLoginType();
}
