// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface ImportProjectEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:android_studio.ImportProjectEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .android_studio.ImportProjectEvent.EventType event_type = 1;</code>
   * @return Whether the eventType field is set.
   */
  boolean hasEventType();
  /**
   * <code>optional .android_studio.ImportProjectEvent.EventType event_type = 1;</code>
   * @return The eventType.
   */
  com.google.wireless.android.sdk.stats.ImportProjectEvent.EventType getEventType();

  /**
   * <code>optional .android_studio.ImportProjectEvent.SourceProjectType source_project_type = 2;</code>
   * @return Whether the sourceProjectType field is set.
   */
  boolean hasSourceProjectType();
  /**
   * <code>optional .android_studio.ImportProjectEvent.SourceProjectType source_project_type = 2;</code>
   * @return The sourceProjectType.
   */
  com.google.wireless.android.sdk.stats.ImportProjectEvent.SourceProjectType getSourceProjectType();

  /**
   * <code>optional .android_studio.ImportProjectEvent.TargetProjectType target_project_type = 3;</code>
   * @return Whether the targetProjectType field is set.
   */
  boolean hasTargetProjectType();
  /**
   * <code>optional .android_studio.ImportProjectEvent.TargetProjectType target_project_type = 3;</code>
   * @return The targetProjectType.
   */
  com.google.wireless.android.sdk.stats.ImportProjectEvent.TargetProjectType getTargetProjectType();

  /**
   * <code>optional .android_studio.ImportProjectEvent.InteractivityMode interactivity_mode = 4;</code>
   * @return Whether the interactivityMode field is set.
   */
  boolean hasInteractivityMode();
  /**
   * <code>optional .android_studio.ImportProjectEvent.InteractivityMode interactivity_mode = 4;</code>
   * @return The interactivityMode.
   */
  com.google.wireless.android.sdk.stats.ImportProjectEvent.InteractivityMode getInteractivityMode();

  /**
   * <code>optional .android_studio.ImportProjectEvent.ValidationStrategy validation_strategy = 5;</code>
   * @return Whether the validationStrategy field is set.
   */
  boolean hasValidationStrategy();
  /**
   * <code>optional .android_studio.ImportProjectEvent.ValidationStrategy validation_strategy = 5;</code>
   * @return The validationStrategy.
   */
  com.google.wireless.android.sdk.stats.ImportProjectEvent.ValidationStrategy getValidationStrategy();

  /**
   * <code>optional bool is_journeys_enabled = 6;</code>
   * @return Whether the isJourneysEnabled field is set.
   */
  boolean hasIsJourneysEnabled();
  /**
   * <code>optional bool is_journeys_enabled = 6;</code>
   * @return The isJourneysEnabled.
   */
  boolean getIsJourneysEnabled();

  /**
   * <code>optional string session_id = 7;</code>
   * @return Whether the sessionId field is set.
   */
  boolean hasSessionId();
  /**
   * <code>optional string session_id = 7;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>optional string session_id = 7;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>optional string model_id = 8;</code>
   * @return Whether the modelId field is set.
   */
  boolean hasModelId();
  /**
   * <code>optional string model_id = 8;</code>
   * @return The modelId.
   */
  java.lang.String getModelId();
  /**
   * <code>optional string model_id = 8;</code>
   * @return The bytes for modelId.
   */
  com.google.protobuf.ByteString
      getModelIdBytes();
}
