// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

// Protobuf Java Version: 3.25.5
package com.google.wireless.android.sdk.stats;

public interface ImportProjectEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:android_studio.ImportProjectEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .android_studio.ImportProjectEvent.EventType event_type = 1;</code>
   * @return Whether the eventType field is set.
   */
  boolean hasEventType();
  /**
   * <code>optional .android_studio.ImportProjectEvent.EventType event_type = 1;</code>
   * @return The eventType.
   */
  com.google.wireless.android.sdk.stats.ImportProjectEvent.EventType getEventType();

  /**
   * <code>optional .android_studio.ImportProjectEvent.SourceProjectType source_project_type = 2;</code>
   * @return Whether the sourceProjectType field is set.
   */
  boolean hasSourceProjectType();
  /**
   * <code>optional .android_studio.ImportProjectEvent.SourceProjectType source_project_type = 2;</code>
   * @return The sourceProjectType.
   */
  com.google.wireless.android.sdk.stats.ImportProjectEvent.SourceProjectType getSourceProjectType();

  /**
   * <code>optional .android_studio.ImportProjectEvent.TargetProjectType target_project_type = 3;</code>
   * @return Whether the targetProjectType field is set.
   */
  boolean hasTargetProjectType();
  /**
   * <code>optional .android_studio.ImportProjectEvent.TargetProjectType target_project_type = 3;</code>
   * @return The targetProjectType.
   */
  com.google.wireless.android.sdk.stats.ImportProjectEvent.TargetProjectType getTargetProjectType();

  /**
   * <code>optional .android_studio.ImportProjectEvent.InteractivityMode interactivity_mode = 4;</code>
   * @return Whether the interactivityMode field is set.
   */
  boolean hasInteractivityMode();
  /**
   * <code>optional .android_studio.ImportProjectEvent.InteractivityMode interactivity_mode = 4;</code>
   * @return The interactivityMode.
   */
  com.google.wireless.android.sdk.stats.ImportProjectEvent.InteractivityMode getInteractivityMode();

  /**
   * <code>optional .android_studio.ImportProjectEvent.ValidationStrategy validation_strategy = 5;</code>
   * @return Whether the validationStrategy field is set.
   */
  boolean hasValidationStrategy();
  /**
   * <code>optional .android_studio.ImportProjectEvent.ValidationStrategy validation_strategy = 5;</code>
   * @return The validationStrategy.
   */
  com.google.wireless.android.sdk.stats.ImportProjectEvent.ValidationStrategy getValidationStrategy();

  /**
   * <pre>
   * ID of the agent conversation. Set for IMPORT_STARTED and IMPORT_RESUMED.
   * Same as GeminiTelemetryEvent.EventEnvelope.root_trajectory_id, which
   * links the tool and skill usage of the import.
   * </pre>
   *
   * <code>optional string conversation_id = 6;</code>
   * @return Whether the conversationId field is set.
   */
  boolean hasConversationId();
  /**
   * <pre>
   * ID of the agent conversation. Set for IMPORT_STARTED and IMPORT_RESUMED.
   * Same as GeminiTelemetryEvent.EventEnvelope.root_trajectory_id, which
   * links the tool and skill usage of the import.
   * </pre>
   *
   * <code>optional string conversation_id = 6;</code>
   * @return The conversationId.
   */
  java.lang.String getConversationId();
  /**
   * <pre>
   * ID of the agent conversation. Set for IMPORT_STARTED and IMPORT_RESUMED.
   * Same as GeminiTelemetryEvent.EventEnvelope.root_trajectory_id, which
   * links the tool and skill usage of the import.
   * </pre>
   *
   * <code>optional string conversation_id = 6;</code>
   * @return The bytes for conversationId.
   */
  com.google.protobuf.ByteString
      getConversationIdBytes();

  /**
   * <pre>
   * Random ID of one New Project wizard instance. Set for ENTRY_SHOWN,
   * SOURCE_DETECTED, SOURCE_DETECTION_FAILED, IMPORT_STARTED and
   * IMPORT_START_FAILED, so that the events of one wizard can be joined.
   * </pre>
   *
   * <code>optional string wizard_session_id = 7;</code>
   * @return Whether the wizardSessionId field is set.
   */
  boolean hasWizardSessionId();
  /**
   * <pre>
   * Random ID of one New Project wizard instance. Set for ENTRY_SHOWN,
   * SOURCE_DETECTED, SOURCE_DETECTION_FAILED, IMPORT_STARTED and
   * IMPORT_START_FAILED, so that the events of one wizard can be joined.
   * </pre>
   *
   * <code>optional string wizard_session_id = 7;</code>
   * @return The wizardSessionId.
   */
  java.lang.String getWizardSessionId();
  /**
   * <pre>
   * Random ID of one New Project wizard instance. Set for ENTRY_SHOWN,
   * SOURCE_DETECTED, SOURCE_DETECTION_FAILED, IMPORT_STARTED and
   * IMPORT_START_FAILED, so that the events of one wizard can be joined.
   * </pre>
   *
   * <code>optional string wizard_session_id = 7;</code>
   * @return The bytes for wizardSessionId.
   */
  com.google.protobuf.ByteString
      getWizardSessionIdBytes();

  /**
   * <code>optional string model_id = 8;</code>
   * @return Whether the modelId field is set.
   */
  boolean hasModelId();
  /**
   * <code>optional string model_id = 8;</code>
   * @return The modelId.
   */
  java.lang.String getModelId();
  /**
   * <code>optional string model_id = 8;</code>
   * @return The bytes for modelId.
   */
  com.google.protobuf.ByteString
      getModelIdBytes();

  /**
   * <pre>
   * Set when event_type = SOURCE_DETECTION_FAILED.
   * </pre>
   *
   * <code>optional .android_studio.ImportProjectEvent.DetectionFailureReason detection_failure_reason = 9;</code>
   * @return Whether the detectionFailureReason field is set.
   */
  boolean hasDetectionFailureReason();
  /**
   * <pre>
   * Set when event_type = SOURCE_DETECTION_FAILED.
   * </pre>
   *
   * <code>optional .android_studio.ImportProjectEvent.DetectionFailureReason detection_failure_reason = 9;</code>
   * @return The detectionFailureReason.
   */
  com.google.wireless.android.sdk.stats.ImportProjectEvent.DetectionFailureReason getDetectionFailureReason();

  /**
   * <pre>
   * Set when event_type = IMPORT_START_FAILED.
   * </pre>
   *
   * <code>optional .android_studio.ImportProjectEvent.StartFailureReason start_failure_reason = 10;</code>
   * @return Whether the startFailureReason field is set.
   */
  boolean hasStartFailureReason();
  /**
   * <pre>
   * Set when event_type = IMPORT_START_FAILED.
   * </pre>
   *
   * <code>optional .android_studio.ImportProjectEvent.StartFailureReason start_failure_reason = 10;</code>
   * @return The startFailureReason.
   */
  com.google.wireless.android.sdk.stats.ImportProjectEvent.StartFailureReason getStartFailureReason();

  /**
   * <pre>
   * Set when event_type = IMPORT_RESUMED. The conversation_id of the
   * IMPORT_STARTED event of the import that is resumed.
   * </pre>
   *
   * <code>optional string resumed_from_conversation_id = 11;</code>
   * @return Whether the resumedFromConversationId field is set.
   */
  boolean hasResumedFromConversationId();
  /**
   * <pre>
   * Set when event_type = IMPORT_RESUMED. The conversation_id of the
   * IMPORT_STARTED event of the import that is resumed.
   * </pre>
   *
   * <code>optional string resumed_from_conversation_id = 11;</code>
   * @return The resumedFromConversationId.
   */
  java.lang.String getResumedFromConversationId();
  /**
   * <pre>
   * Set when event_type = IMPORT_RESUMED. The conversation_id of the
   * IMPORT_STARTED event of the import that is resumed.
   * </pre>
   *
   * <code>optional string resumed_from_conversation_id = 11;</code>
   * @return The bytes for resumedFromConversationId.
   */
  com.google.protobuf.ByteString
      getResumedFromConversationIdBytes();

  /**
   * <pre>
   * Set when event_type = IMPORT_STARTED. Whether the user gave custom
   * instructions. Their content is never logged.
   * </pre>
   *
   * <code>optional bool has_custom_instructions = 12;</code>
   * @return Whether the hasCustomInstructions field is set.
   */
  boolean hasHasCustomInstructions();
  /**
   * <pre>
   * Set when event_type = IMPORT_STARTED. Whether the user gave custom
   * instructions. Their content is never logged.
   * </pre>
   *
   * <code>optional bool has_custom_instructions = 12;</code>
   * @return The hasCustomInstructions.
   */
  boolean getHasCustomInstructions();

  /**
   * <pre>
   * Set when event_type = IMPORT_STARTED. Number of attached images.
   * </pre>
   *
   * <code>optional int32 image_attachment_count = 13;</code>
   * @return Whether the imageAttachmentCount field is set.
   */
  boolean hasImageAttachmentCount();
  /**
   * <pre>
   * Set when event_type = IMPORT_STARTED. Number of attached images.
   * </pre>
   *
   * <code>optional int32 image_attachment_count = 13;</code>
   * @return The imageAttachmentCount.
   */
  int getImageAttachmentCount();

  /**
   * <pre>
   * Set when event_type = IMPORT_STARTED. Number of attached user skills
   * (SKILL.md files).
   * </pre>
   *
   * <code>optional int32 user_skill_count = 14;</code>
   * @return Whether the userSkillCount field is set.
   */
  boolean hasUserSkillCount();
  /**
   * <pre>
   * Set when event_type = IMPORT_STARTED. Number of attached user skills
   * (SKILL.md files).
   * </pre>
   *
   * <code>optional int32 user_skill_count = 14;</code>
   * @return The userSkillCount.
   */
  int getUserSkillCount();
}
