// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

/**
 * <pre>
 * Event related to Import Project Agent (e.g. from iOS, React Native, Flutter
 * to Android / KMP)
 * </pre>
 *
 * Protobuf type {@code android_studio.ImportProjectEvent}
 */
public final class ImportProjectEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:android_studio.ImportProjectEvent)
    ImportProjectEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ImportProjectEvent.newBuilder() to construct.
  private ImportProjectEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ImportProjectEvent() {
    eventType_ = 0;
    sourceProjectType_ = 0;
    targetProjectType_ = 0;
    interactivityMode_ = 0;
    validationStrategy_ = 0;
    sessionId_ = "";
    modelId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ImportProjectEvent();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_ImportProjectEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_ImportProjectEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.wireless.android.sdk.stats.ImportProjectEvent.class, com.google.wireless.android.sdk.stats.ImportProjectEvent.Builder.class);
  }

  /**
   * Protobuf enum {@code android_studio.ImportProjectEvent.EventType}
   */
  public enum EventType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_EVENT_TYPE = 0;</code>
     */
    UNKNOWN_EVENT_TYPE(0),
    /**
     * <code>IMPORT_STARTED = 1;</code>
     */
    IMPORT_STARTED(1),
    ;

    /**
     * <code>UNKNOWN_EVENT_TYPE = 0;</code>
     */
    public static final int UNKNOWN_EVENT_TYPE_VALUE = 0;
    /**
     * <code>IMPORT_STARTED = 1;</code>
     */
    public static final int IMPORT_STARTED_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EventType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EventType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_EVENT_TYPE;
        case 1: return IMPORT_STARTED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EventType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EventType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
            public EventType findValueByNumber(int number) {
              return EventType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.ImportProjectEvent.getDescriptor().getEnumTypes().get(0);
    }

    private static final EventType[] VALUES = values();

    public static EventType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EventType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:android_studio.ImportProjectEvent.EventType)
  }

  /**
   * Protobuf enum {@code android_studio.ImportProjectEvent.SourceProjectType}
   */
  public enum SourceProjectType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_SOURCE_PROJECT_TYPE = 0;</code>
     */
    UNKNOWN_SOURCE_PROJECT_TYPE(0),
    /**
     * <code>IOS = 1;</code>
     */
    IOS(1),
    /**
     * <code>REACT_NATIVE = 2;</code>
     */
    REACT_NATIVE(2),
    /**
     * <code>FLUTTER = 3;</code>
     */
    FLUTTER(3),
    ;

    /**
     * <code>UNKNOWN_SOURCE_PROJECT_TYPE = 0;</code>
     */
    public static final int UNKNOWN_SOURCE_PROJECT_TYPE_VALUE = 0;
    /**
     * <code>IOS = 1;</code>
     */
    public static final int IOS_VALUE = 1;
    /**
     * <code>REACT_NATIVE = 2;</code>
     */
    public static final int REACT_NATIVE_VALUE = 2;
    /**
     * <code>FLUTTER = 3;</code>
     */
    public static final int FLUTTER_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SourceProjectType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static SourceProjectType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_SOURCE_PROJECT_TYPE;
        case 1: return IOS;
        case 2: return REACT_NATIVE;
        case 3: return FLUTTER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SourceProjectType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SourceProjectType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SourceProjectType>() {
            public SourceProjectType findValueByNumber(int number) {
              return SourceProjectType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.ImportProjectEvent.getDescriptor().getEnumTypes().get(1);
    }

    private static final SourceProjectType[] VALUES = values();

    public static SourceProjectType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SourceProjectType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:android_studio.ImportProjectEvent.SourceProjectType)
  }

  /**
   * Protobuf enum {@code android_studio.ImportProjectEvent.TargetProjectType}
   */
  public enum TargetProjectType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_TARGET_PROJECT_TYPE = 0;</code>
     */
    UNKNOWN_TARGET_PROJECT_TYPE(0),
    /**
     * <code>ANDROID = 1;</code>
     */
    ANDROID(1),
    /**
     * <code>KMP = 2;</code>
     */
    KMP(2),
    ;

    /**
     * <code>UNKNOWN_TARGET_PROJECT_TYPE = 0;</code>
     */
    public static final int UNKNOWN_TARGET_PROJECT_TYPE_VALUE = 0;
    /**
     * <code>ANDROID = 1;</code>
     */
    public static final int ANDROID_VALUE = 1;
    /**
     * <code>KMP = 2;</code>
     */
    public static final int KMP_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TargetProjectType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static TargetProjectType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_TARGET_PROJECT_TYPE;
        case 1: return ANDROID;
        case 2: return KMP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TargetProjectType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TargetProjectType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TargetProjectType>() {
            public TargetProjectType findValueByNumber(int number) {
              return TargetProjectType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.ImportProjectEvent.getDescriptor().getEnumTypes().get(2);
    }

    private static final TargetProjectType[] VALUES = values();

    public static TargetProjectType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TargetProjectType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:android_studio.ImportProjectEvent.TargetProjectType)
  }

  /**
   * Protobuf enum {@code android_studio.ImportProjectEvent.InteractivityMode}
   */
  public enum InteractivityMode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_MODE = 0;</code>
     */
    UNKNOWN_MODE(0),
    /**
     * <code>AUTONOMOUS = 1;</code>
     */
    AUTONOMOUS(1),
    /**
     * <code>GUIDED = 2;</code>
     */
    GUIDED(2),
    ;

    /**
     * <code>UNKNOWN_MODE = 0;</code>
     */
    public static final int UNKNOWN_MODE_VALUE = 0;
    /**
     * <code>AUTONOMOUS = 1;</code>
     */
    public static final int AUTONOMOUS_VALUE = 1;
    /**
     * <code>GUIDED = 2;</code>
     */
    public static final int GUIDED_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static InteractivityMode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static InteractivityMode forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_MODE;
        case 1: return AUTONOMOUS;
        case 2: return GUIDED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<InteractivityMode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        InteractivityMode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<InteractivityMode>() {
            public InteractivityMode findValueByNumber(int number) {
              return InteractivityMode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.ImportProjectEvent.getDescriptor().getEnumTypes().get(3);
    }

    private static final InteractivityMode[] VALUES = values();

    public static InteractivityMode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private InteractivityMode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:android_studio.ImportProjectEvent.InteractivityMode)
  }

  /**
   * Protobuf enum {@code android_studio.ImportProjectEvent.ValidationStrategy}
   */
  public enum ValidationStrategy
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_STRATEGY = 0;</code>
     */
    UNKNOWN_STRATEGY(0),
    /**
     * <code>JOURNEYS = 1;</code>
     */
    JOURNEYS(1),
    /**
     * <code>MANUAL = 2;</code>
     */
    MANUAL(2),
    ;

    /**
     * <code>UNKNOWN_STRATEGY = 0;</code>
     */
    public static final int UNKNOWN_STRATEGY_VALUE = 0;
    /**
     * <code>JOURNEYS = 1;</code>
     */
    public static final int JOURNEYS_VALUE = 1;
    /**
     * <code>MANUAL = 2;</code>
     */
    public static final int MANUAL_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ValidationStrategy valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ValidationStrategy forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_STRATEGY;
        case 1: return JOURNEYS;
        case 2: return MANUAL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ValidationStrategy>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ValidationStrategy> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ValidationStrategy>() {
            public ValidationStrategy findValueByNumber(int number) {
              return ValidationStrategy.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.ImportProjectEvent.getDescriptor().getEnumTypes().get(4);
    }

    private static final ValidationStrategy[] VALUES = values();

    public static ValidationStrategy valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ValidationStrategy(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:android_studio.ImportProjectEvent.ValidationStrategy)
  }

  private int bitField0_;
  public static final int EVENT_TYPE_FIELD_NUMBER = 1;
  private int eventType_ = 0;
  /**
   * <code>optional .android_studio.ImportProjectEvent.EventType event_type = 1;</code>
   * @return Whether the eventType field is set.
   */
  @java.lang.Override public boolean hasEventType() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .android_studio.ImportProjectEvent.EventType event_type = 1;</code>
   * @return The eventType.
   */
  @java.lang.Override public com.google.wireless.android.sdk.stats.ImportProjectEvent.EventType getEventType() {
    com.google.wireless.android.sdk.stats.ImportProjectEvent.EventType result = com.google.wireless.android.sdk.stats.ImportProjectEvent.EventType.forNumber(eventType_);
    return result == null ? com.google.wireless.android.sdk.stats.ImportProjectEvent.EventType.UNKNOWN_EVENT_TYPE : result;
  }

  public static final int SOURCE_PROJECT_TYPE_FIELD_NUMBER = 2;
  private int sourceProjectType_ = 0;
  /**
   * <code>optional .android_studio.ImportProjectEvent.SourceProjectType source_project_type = 2;</code>
   * @return Whether the sourceProjectType field is set.
   */
  @java.lang.Override public boolean hasSourceProjectType() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .android_studio.ImportProjectEvent.SourceProjectType source_project_type = 2;</code>
   * @return The sourceProjectType.
   */
  @java.lang.Override public com.google.wireless.android.sdk.stats.ImportProjectEvent.SourceProjectType getSourceProjectType() {
    com.google.wireless.android.sdk.stats.ImportProjectEvent.SourceProjectType result = com.google.wireless.android.sdk.stats.ImportProjectEvent.SourceProjectType.forNumber(sourceProjectType_);
    return result == null ? com.google.wireless.android.sdk.stats.ImportProjectEvent.SourceProjectType.UNKNOWN_SOURCE_PROJECT_TYPE : result;
  }

  public static final int TARGET_PROJECT_TYPE_FIELD_NUMBER = 3;
  private int targetProjectType_ = 0;
  /**
   * <code>optional .android_studio.ImportProjectEvent.TargetProjectType target_project_type = 3;</code>
   * @return Whether the targetProjectType field is set.
   */
  @java.lang.Override public boolean hasTargetProjectType() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .android_studio.ImportProjectEvent.TargetProjectType target_project_type = 3;</code>
   * @return The targetProjectType.
   */
  @java.lang.Override public com.google.wireless.android.sdk.stats.ImportProjectEvent.TargetProjectType getTargetProjectType() {
    com.google.wireless.android.sdk.stats.ImportProjectEvent.TargetProjectType result = com.google.wireless.android.sdk.stats.ImportProjectEvent.TargetProjectType.forNumber(targetProjectType_);
    return result == null ? com.google.wireless.android.sdk.stats.ImportProjectEvent.TargetProjectType.UNKNOWN_TARGET_PROJECT_TYPE : result;
  }

  public static final int INTERACTIVITY_MODE_FIELD_NUMBER = 4;
  private int interactivityMode_ = 0;
  /**
   * <code>optional .android_studio.ImportProjectEvent.InteractivityMode interactivity_mode = 4;</code>
   * @return Whether the interactivityMode field is set.
   */
  @java.lang.Override public boolean hasInteractivityMode() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional .android_studio.ImportProjectEvent.InteractivityMode interactivity_mode = 4;</code>
   * @return The interactivityMode.
   */
  @java.lang.Override public com.google.wireless.android.sdk.stats.ImportProjectEvent.InteractivityMode getInteractivityMode() {
    com.google.wireless.android.sdk.stats.ImportProjectEvent.InteractivityMode result = com.google.wireless.android.sdk.stats.ImportProjectEvent.InteractivityMode.forNumber(interactivityMode_);
    return result == null ? com.google.wireless.android.sdk.stats.ImportProjectEvent.InteractivityMode.UNKNOWN_MODE : result;
  }

  public static final int VALIDATION_STRATEGY_FIELD_NUMBER = 5;
  private int validationStrategy_ = 0;
  /**
   * <code>optional .android_studio.ImportProjectEvent.ValidationStrategy validation_strategy = 5;</code>
   * @return Whether the validationStrategy field is set.
   */
  @java.lang.Override public boolean hasValidationStrategy() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional .android_studio.ImportProjectEvent.ValidationStrategy validation_strategy = 5;</code>
   * @return The validationStrategy.
   */
  @java.lang.Override public com.google.wireless.android.sdk.stats.ImportProjectEvent.ValidationStrategy getValidationStrategy() {
    com.google.wireless.android.sdk.stats.ImportProjectEvent.ValidationStrategy result = com.google.wireless.android.sdk.stats.ImportProjectEvent.ValidationStrategy.forNumber(validationStrategy_);
    return result == null ? com.google.wireless.android.sdk.stats.ImportProjectEvent.ValidationStrategy.UNKNOWN_STRATEGY : result;
  }

  public static final int IS_JOURNEYS_ENABLED_FIELD_NUMBER = 6;
  private boolean isJourneysEnabled_ = false;
  /**
   * <code>optional bool is_journeys_enabled = 6;</code>
   * @return Whether the isJourneysEnabled field is set.
   */
  @java.lang.Override
  public boolean hasIsJourneysEnabled() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional bool is_journeys_enabled = 6;</code>
   * @return The isJourneysEnabled.
   */
  @java.lang.Override
  public boolean getIsJourneysEnabled() {
    return isJourneysEnabled_;
  }

  public static final int SESSION_ID_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sessionId_ = "";
  /**
   * <code>optional string session_id = 7;</code>
   * @return Whether the sessionId field is set.
   */
  @java.lang.Override
  public boolean hasSessionId() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional string session_id = 7;</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public java.lang.String getSessionId() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        sessionId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string session_id = 7;</code>
   * @return The bytes for sessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODEL_ID_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object modelId_ = "";
  /**
   * <code>optional string model_id = 8;</code>
   * @return Whether the modelId field is set.
   */
  @java.lang.Override
  public boolean hasModelId() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>optional string model_id = 8;</code>
   * @return The modelId.
   */
  @java.lang.Override
  public java.lang.String getModelId() {
    java.lang.Object ref = modelId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        modelId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string model_id = 8;</code>
   * @return The bytes for modelId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelIdBytes() {
    java.lang.Object ref = modelId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      modelId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeEnum(1, eventType_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeEnum(2, sourceProjectType_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeEnum(3, targetProjectType_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeEnum(4, interactivityMode_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeEnum(5, validationStrategy_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeBool(6, isJourneysEnabled_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, sessionId_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, modelId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, eventType_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, sourceProjectType_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, targetProjectType_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, interactivityMode_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, validationStrategy_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, isJourneysEnabled_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, sessionId_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, modelId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.wireless.android.sdk.stats.ImportProjectEvent)) {
      return super.equals(obj);
    }
    com.google.wireless.android.sdk.stats.ImportProjectEvent other = (com.google.wireless.android.sdk.stats.ImportProjectEvent) obj;

    if (hasEventType() != other.hasEventType()) return false;
    if (hasEventType()) {
      if (eventType_ != other.eventType_) return false;
    }
    if (hasSourceProjectType() != other.hasSourceProjectType()) return false;
    if (hasSourceProjectType()) {
      if (sourceProjectType_ != other.sourceProjectType_) return false;
    }
    if (hasTargetProjectType() != other.hasTargetProjectType()) return false;
    if (hasTargetProjectType()) {
      if (targetProjectType_ != other.targetProjectType_) return false;
    }
    if (hasInteractivityMode() != other.hasInteractivityMode()) return false;
    if (hasInteractivityMode()) {
      if (interactivityMode_ != other.interactivityMode_) return false;
    }
    if (hasValidationStrategy() != other.hasValidationStrategy()) return false;
    if (hasValidationStrategy()) {
      if (validationStrategy_ != other.validationStrategy_) return false;
    }
    if (hasIsJourneysEnabled() != other.hasIsJourneysEnabled()) return false;
    if (hasIsJourneysEnabled()) {
      if (getIsJourneysEnabled()
          != other.getIsJourneysEnabled()) return false;
    }
    if (hasSessionId() != other.hasSessionId()) return false;
    if (hasSessionId()) {
      if (!getSessionId()
          .equals(other.getSessionId())) return false;
    }
    if (hasModelId() != other.hasModelId()) return false;
    if (hasModelId()) {
      if (!getModelId()
          .equals(other.getModelId())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasEventType()) {
      hash = (37 * hash) + EVENT_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + eventType_;
    }
    if (hasSourceProjectType()) {
      hash = (37 * hash) + SOURCE_PROJECT_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + sourceProjectType_;
    }
    if (hasTargetProjectType()) {
      hash = (37 * hash) + TARGET_PROJECT_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + targetProjectType_;
    }
    if (hasInteractivityMode()) {
      hash = (37 * hash) + INTERACTIVITY_MODE_FIELD_NUMBER;
      hash = (53 * hash) + interactivityMode_;
    }
    if (hasValidationStrategy()) {
      hash = (37 * hash) + VALIDATION_STRATEGY_FIELD_NUMBER;
      hash = (53 * hash) + validationStrategy_;
    }
    if (hasIsJourneysEnabled()) {
      hash = (37 * hash) + IS_JOURNEYS_ENABLED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsJourneysEnabled());
    }
    if (hasSessionId()) {
      hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionId().hashCode();
    }
    if (hasModelId()) {
      hash = (37 * hash) + MODEL_ID_FIELD_NUMBER;
      hash = (53 * hash) + getModelId().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.wireless.android.sdk.stats.ImportProjectEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.ImportProjectEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.ImportProjectEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.ImportProjectEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.ImportProjectEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.ImportProjectEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.ImportProjectEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.ImportProjectEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.ImportProjectEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.ImportProjectEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.ImportProjectEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.ImportProjectEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.wireless.android.sdk.stats.ImportProjectEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Event related to Import Project Agent (e.g. from iOS, React Native, Flutter
   * to Android / KMP)
   * </pre>
   *
   * Protobuf type {@code android_studio.ImportProjectEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:android_studio.ImportProjectEvent)
      com.google.wireless.android.sdk.stats.ImportProjectEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_ImportProjectEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_ImportProjectEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.wireless.android.sdk.stats.ImportProjectEvent.class, com.google.wireless.android.sdk.stats.ImportProjectEvent.Builder.class);
    }

    // Construct using com.google.wireless.android.sdk.stats.ImportProjectEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      eventType_ = 0;
      sourceProjectType_ = 0;
      targetProjectType_ = 0;
      interactivityMode_ = 0;
      validationStrategy_ = 0;
      isJourneysEnabled_ = false;
      sessionId_ = "";
      modelId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_ImportProjectEvent_descriptor;
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.ImportProjectEvent getDefaultInstanceForType() {
      return com.google.wireless.android.sdk.stats.ImportProjectEvent.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.ImportProjectEvent build() {
      com.google.wireless.android.sdk.stats.ImportProjectEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.ImportProjectEvent buildPartial() {
      com.google.wireless.android.sdk.stats.ImportProjectEvent result = new com.google.wireless.android.sdk.stats.ImportProjectEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.wireless.android.sdk.stats.ImportProjectEvent result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.eventType_ = eventType_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.sourceProjectType_ = sourceProjectType_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.targetProjectType_ = targetProjectType_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.interactivityMode_ = interactivityMode_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.validationStrategy_ = validationStrategy_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.isJourneysEnabled_ = isJourneysEnabled_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.sessionId_ = sessionId_;
        to_bitField0_ |= 0x00000040;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.modelId_ = modelId_;
        to_bitField0_ |= 0x00000080;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.wireless.android.sdk.stats.ImportProjectEvent) {
        return mergeFrom((com.google.wireless.android.sdk.stats.ImportProjectEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.wireless.android.sdk.stats.ImportProjectEvent other) {
      if (other == com.google.wireless.android.sdk.stats.ImportProjectEvent.getDefaultInstance()) return this;
      if (other.hasEventType()) {
        setEventType(other.getEventType());
      }
      if (other.hasSourceProjectType()) {
        setSourceProjectType(other.getSourceProjectType());
      }
      if (other.hasTargetProjectType()) {
        setTargetProjectType(other.getTargetProjectType());
      }
      if (other.hasInteractivityMode()) {
        setInteractivityMode(other.getInteractivityMode());
      }
      if (other.hasValidationStrategy()) {
        setValidationStrategy(other.getValidationStrategy());
      }
      if (other.hasIsJourneysEnabled()) {
        setIsJourneysEnabled(other.getIsJourneysEnabled());
      }
      if (other.hasSessionId()) {
        sessionId_ = other.sessionId_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (other.hasModelId()) {
        modelId_ = other.modelId_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int tmpRaw = input.readEnum();
              com.google.wireless.android.sdk.stats.ImportProjectEvent.EventType tmpValue =
                  com.google.wireless.android.sdk.stats.ImportProjectEvent.EventType.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(1, tmpRaw);
              } else {
                eventType_ = tmpRaw;
                bitField0_ |= 0x00000001;
              }
              break;
            } // case 8
            case 16: {
              int tmpRaw = input.readEnum();
              com.google.wireless.android.sdk.stats.ImportProjectEvent.SourceProjectType tmpValue =
                  com.google.wireless.android.sdk.stats.ImportProjectEvent.SourceProjectType.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(2, tmpRaw);
              } else {
                sourceProjectType_ = tmpRaw;
                bitField0_ |= 0x00000002;
              }
              break;
            } // case 16
            case 24: {
              int tmpRaw = input.readEnum();
              com.google.wireless.android.sdk.stats.ImportProjectEvent.TargetProjectType tmpValue =
                  com.google.wireless.android.sdk.stats.ImportProjectEvent.TargetProjectType.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(3, tmpRaw);
              } else {
                targetProjectType_ = tmpRaw;
                bitField0_ |= 0x00000004;
              }
              break;
            } // case 24
            case 32: {
              int tmpRaw = input.readEnum();
              com.google.wireless.android.sdk.stats.ImportProjectEvent.InteractivityMode tmpValue =
                  com.google.wireless.android.sdk.stats.ImportProjectEvent.InteractivityMode.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(4, tmpRaw);
              } else {
                interactivityMode_ = tmpRaw;
                bitField0_ |= 0x00000008;
              }
              break;
            } // case 32
            case 40: {
              int tmpRaw = input.readEnum();
              com.google.wireless.android.sdk.stats.ImportProjectEvent.ValidationStrategy tmpValue =
                  com.google.wireless.android.sdk.stats.ImportProjectEvent.ValidationStrategy.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(5, tmpRaw);
              } else {
                validationStrategy_ = tmpRaw;
                bitField0_ |= 0x00000010;
              }
              break;
            } // case 40
            case 48: {
              isJourneysEnabled_ = input.readBool();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              sessionId_ = input.readBytes();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              modelId_ = input.readBytes();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int eventType_ = 0;
    /**
     * <code>optional .android_studio.ImportProjectEvent.EventType event_type = 1;</code>
     * @return Whether the eventType field is set.
     */
    @java.lang.Override public boolean hasEventType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .android_studio.ImportProjectEvent.EventType event_type = 1;</code>
     * @return The eventType.
     */
    @java.lang.Override
    public com.google.wireless.android.sdk.stats.ImportProjectEvent.EventType getEventType() {
      com.google.wireless.android.sdk.stats.ImportProjectEvent.EventType result = com.google.wireless.android.sdk.stats.ImportProjectEvent.EventType.forNumber(eventType_);
      return result == null ? com.google.wireless.android.sdk.stats.ImportProjectEvent.EventType.UNKNOWN_EVENT_TYPE : result;
    }
    /**
     * <code>optional .android_studio.ImportProjectEvent.EventType event_type = 1;</code>
     * @param value The eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventType(com.google.wireless.android.sdk.stats.ImportProjectEvent.EventType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      eventType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .android_studio.ImportProjectEvent.EventType event_type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      eventType_ = 0;
      onChanged();
      return this;
    }

    private int sourceProjectType_ = 0;
    /**
     * <code>optional .android_studio.ImportProjectEvent.SourceProjectType source_project_type = 2;</code>
     * @return Whether the sourceProjectType field is set.
     */
    @java.lang.Override public boolean hasSourceProjectType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .android_studio.ImportProjectEvent.SourceProjectType source_project_type = 2;</code>
     * @return The sourceProjectType.
     */
    @java.lang.Override
    public com.google.wireless.android.sdk.stats.ImportProjectEvent.SourceProjectType getSourceProjectType() {
      com.google.wireless.android.sdk.stats.ImportProjectEvent.SourceProjectType result = com.google.wireless.android.sdk.stats.ImportProjectEvent.SourceProjectType.forNumber(sourceProjectType_);
      return result == null ? com.google.wireless.android.sdk.stats.ImportProjectEvent.SourceProjectType.UNKNOWN_SOURCE_PROJECT_TYPE : result;
    }
    /**
     * <code>optional .android_studio.ImportProjectEvent.SourceProjectType source_project_type = 2;</code>
     * @param value The sourceProjectType to set.
     * @return This builder for chaining.
     */
    public Builder setSourceProjectType(com.google.wireless.android.sdk.stats.ImportProjectEvent.SourceProjectType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      sourceProjectType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .android_studio.ImportProjectEvent.SourceProjectType source_project_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceProjectType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      sourceProjectType_ = 0;
      onChanged();
      return this;
    }

    private int targetProjectType_ = 0;
    /**
     * <code>optional .android_studio.ImportProjectEvent.TargetProjectType target_project_type = 3;</code>
     * @return Whether the targetProjectType field is set.
     */
    @java.lang.Override public boolean hasTargetProjectType() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .android_studio.ImportProjectEvent.TargetProjectType target_project_type = 3;</code>
     * @return The targetProjectType.
     */
    @java.lang.Override
    public com.google.wireless.android.sdk.stats.ImportProjectEvent.TargetProjectType getTargetProjectType() {
      com.google.wireless.android.sdk.stats.ImportProjectEvent.TargetProjectType result = com.google.wireless.android.sdk.stats.ImportProjectEvent.TargetProjectType.forNumber(targetProjectType_);
      return result == null ? com.google.wireless.android.sdk.stats.ImportProjectEvent.TargetProjectType.UNKNOWN_TARGET_PROJECT_TYPE : result;
    }
    /**
     * <code>optional .android_studio.ImportProjectEvent.TargetProjectType target_project_type = 3;</code>
     * @param value The targetProjectType to set.
     * @return This builder for chaining.
     */
    public Builder setTargetProjectType(com.google.wireless.android.sdk.stats.ImportProjectEvent.TargetProjectType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      targetProjectType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .android_studio.ImportProjectEvent.TargetProjectType target_project_type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTargetProjectType() {
      bitField0_ = (bitField0_ & ~0x00000004);
      targetProjectType_ = 0;
      onChanged();
      return this;
    }

    private int interactivityMode_ = 0;
    /**
     * <code>optional .android_studio.ImportProjectEvent.InteractivityMode interactivity_mode = 4;</code>
     * @return Whether the interactivityMode field is set.
     */
    @java.lang.Override public boolean hasInteractivityMode() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .android_studio.ImportProjectEvent.InteractivityMode interactivity_mode = 4;</code>
     * @return The interactivityMode.
     */
    @java.lang.Override
    public com.google.wireless.android.sdk.stats.ImportProjectEvent.InteractivityMode getInteractivityMode() {
      com.google.wireless.android.sdk.stats.ImportProjectEvent.InteractivityMode result = com.google.wireless.android.sdk.stats.ImportProjectEvent.InteractivityMode.forNumber(interactivityMode_);
      return result == null ? com.google.wireless.android.sdk.stats.ImportProjectEvent.InteractivityMode.UNKNOWN_MODE : result;
    }
    /**
     * <code>optional .android_studio.ImportProjectEvent.InteractivityMode interactivity_mode = 4;</code>
     * @param value The interactivityMode to set.
     * @return This builder for chaining.
     */
    public Builder setInteractivityMode(com.google.wireless.android.sdk.stats.ImportProjectEvent.InteractivityMode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      interactivityMode_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .android_studio.ImportProjectEvent.InteractivityMode interactivity_mode = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearInteractivityMode() {
      bitField0_ = (bitField0_ & ~0x00000008);
      interactivityMode_ = 0;
      onChanged();
      return this;
    }

    private int validationStrategy_ = 0;
    /**
     * <code>optional .android_studio.ImportProjectEvent.ValidationStrategy validation_strategy = 5;</code>
     * @return Whether the validationStrategy field is set.
     */
    @java.lang.Override public boolean hasValidationStrategy() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional .android_studio.ImportProjectEvent.ValidationStrategy validation_strategy = 5;</code>
     * @return The validationStrategy.
     */
    @java.lang.Override
    public com.google.wireless.android.sdk.stats.ImportProjectEvent.ValidationStrategy getValidationStrategy() {
      com.google.wireless.android.sdk.stats.ImportProjectEvent.ValidationStrategy result = com.google.wireless.android.sdk.stats.ImportProjectEvent.ValidationStrategy.forNumber(validationStrategy_);
      return result == null ? com.google.wireless.android.sdk.stats.ImportProjectEvent.ValidationStrategy.UNKNOWN_STRATEGY : result;
    }
    /**
     * <code>optional .android_studio.ImportProjectEvent.ValidationStrategy validation_strategy = 5;</code>
     * @param value The validationStrategy to set.
     * @return This builder for chaining.
     */
    public Builder setValidationStrategy(com.google.wireless.android.sdk.stats.ImportProjectEvent.ValidationStrategy value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      validationStrategy_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .android_studio.ImportProjectEvent.ValidationStrategy validation_strategy = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearValidationStrategy() {
      bitField0_ = (bitField0_ & ~0x00000010);
      validationStrategy_ = 0;
      onChanged();
      return this;
    }

    private boolean isJourneysEnabled_ ;
    /**
     * <code>optional bool is_journeys_enabled = 6;</code>
     * @return Whether the isJourneysEnabled field is set.
     */
    @java.lang.Override
    public boolean hasIsJourneysEnabled() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional bool is_journeys_enabled = 6;</code>
     * @return The isJourneysEnabled.
     */
    @java.lang.Override
    public boolean getIsJourneysEnabled() {
      return isJourneysEnabled_;
    }
    /**
     * <code>optional bool is_journeys_enabled = 6;</code>
     * @param value The isJourneysEnabled to set.
     * @return This builder for chaining.
     */
    public Builder setIsJourneysEnabled(boolean value) {

      isJourneysEnabled_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool is_journeys_enabled = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsJourneysEnabled() {
      bitField0_ = (bitField0_ & ~0x00000020);
      isJourneysEnabled_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object sessionId_ = "";
    /**
     * <code>optional string session_id = 7;</code>
     * @return Whether the sessionId field is set.
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional string session_id = 7;</code>
     * @return The sessionId.
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessionId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string session_id = 7;</code>
     * @return The bytes for sessionId.
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string session_id = 7;</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sessionId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>optional string session_id = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      sessionId_ = getDefaultInstance().getSessionId();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>optional string session_id = 7;</code>
     * @param value The bytes for sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      sessionId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object modelId_ = "";
    /**
     * <code>optional string model_id = 8;</code>
     * @return Whether the modelId field is set.
     */
    public boolean hasModelId() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional string model_id = 8;</code>
     * @return The modelId.
     */
    public java.lang.String getModelId() {
      java.lang.Object ref = modelId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          modelId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string model_id = 8;</code>
     * @return The bytes for modelId.
     */
    public com.google.protobuf.ByteString
        getModelIdBytes() {
      java.lang.Object ref = modelId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string model_id = 8;</code>
     * @param value The modelId to set.
     * @return This builder for chaining.
     */
    public Builder setModelId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      modelId_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>optional string model_id = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearModelId() {
      modelId_ = getDefaultInstance().getModelId();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>optional string model_id = 8;</code>
     * @param value The bytes for modelId to set.
     * @return This builder for chaining.
     */
    public Builder setModelIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      modelId_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:android_studio.ImportProjectEvent)
  }

  // @@protoc_insertion_point(class_scope:android_studio.ImportProjectEvent)
  private static final com.google.wireless.android.sdk.stats.ImportProjectEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.wireless.android.sdk.stats.ImportProjectEvent();
  }

  public static com.google.wireless.android.sdk.stats.ImportProjectEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<ImportProjectEvent>
      PARSER = new com.google.protobuf.AbstractParser<ImportProjectEvent>() {
    @java.lang.Override
    public ImportProjectEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ImportProjectEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ImportProjectEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.wireless.android.sdk.stats.ImportProjectEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

