// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model_registry.proto

package com.google.wireless.android.sdk.stats;

/**
 * <pre>
 * Known models from ModelRegistry.kt for inference configuration and telemetry.
 * </pre>
 *
 * Protobuf enum {@code android_studio.Model}
 */
public enum Model
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>MODEL_UNKNOWN = 0;</code>
   */
  MODEL_UNKNOWN(0),
  /**
   * <pre>
   * AllenAI (1000 - 1099)
   * </pre>
   *
   * <code>MODEL_ALLEN_AI_UNKNOWN = 1000;</code>
   */
  MODEL_ALLEN_AI_UNKNOWN(1000),
  /**
   * <code>MODEL_ALLEN_AI_MOLMO28B = 1001;</code>
   */
  MODEL_ALLEN_AI_MOLMO28B(1001),
  /**
   * <code>MODEL_ALLEN_AI_OLMO3132B_INSTRUCT = 1002;</code>
   */
  MODEL_ALLEN_AI_OLMO3132B_INSTRUCT(1002),
  /**
   * <code>MODEL_ALLEN_AI_OLMO3132B_THINK = 1003;</code>
   */
  MODEL_ALLEN_AI_OLMO3132B_THINK(1003),
  /**
   * <code>MODEL_ALLEN_AI_OLMO332B_THINK = 1004;</code>
   */
  MODEL_ALLEN_AI_OLMO332B_THINK(1004),
  /**
   * <code>MODEL_ALLEN_AI_OLMO37B_INSTRUCT = 1005;</code>
   */
  MODEL_ALLEN_AI_OLMO37B_INSTRUCT(1005),
  /**
   * <code>MODEL_ALLEN_AI_OLMO37B_THINK = 1006;</code>
   */
  MODEL_ALLEN_AI_OLMO37B_THINK(1006),
  /**
   * <code>MODEL_ALLEN_AI_OLMO2032532B_INSTRUCT = 1007;</code>
   */
  MODEL_ALLEN_AI_OLMO2032532B_INSTRUCT(1007),
  /**
   * <code>MODEL_ALLEN_AI_LLAMA31_TULU3405B = 1008;</code>
   */
  MODEL_ALLEN_AI_LLAMA31_TULU3405B(1008),
  /**
   * <pre>
   * AI21 (1100 - 1199)
   * </pre>
   *
   * <code>MODEL_AI21_UNKNOWN = 1100;</code>
   */
  MODEL_AI21_UNKNOWN(1100),
  /**
   * <code>MODEL_AI21_JAMBA_MINI17 = 1101;</code>
   */
  MODEL_AI21_JAMBA_MINI17(1101),
  /**
   * <code>MODEL_AI21_JAMBA_LARGE17 = 1102;</code>
   */
  MODEL_AI21_JAMBA_LARGE17(1102),
  /**
   * <code>MODEL_AI21_JAMBA16_LARGE = 1103;</code>
   */
  MODEL_AI21_JAMBA16_LARGE(1103),
  /**
   * <code>MODEL_AI21_JAMBA16_MINI = 1104;</code>
   */
  MODEL_AI21_JAMBA16_MINI(1104),
  /**
   * <code>MODEL_AI21_JAMBA15_MINI = 1105;</code>
   */
  MODEL_AI21_JAMBA15_MINI(1105),
  /**
   * <code>MODEL_AI21_JAMBA15_LARGE = 1106;</code>
   */
  MODEL_AI21_JAMBA15_LARGE(1106),
  /**
   * <pre>
   * Anthropic (1200 - 1299)
   * </pre>
   *
   * <code>MODEL_ANTHROPIC_UNKNOWN = 1200;</code>
   */
  MODEL_ANTHROPIC_UNKNOWN(1200),
  /**
   * <code>MODEL_ANTHROPIC_CLAUDE_OPUS47 = 1201;</code>
   */
  MODEL_ANTHROPIC_CLAUDE_OPUS47(1201),
  /**
   * <code>MODEL_ANTHROPIC_CLAUDE_OPUS46_FAST = 1202;</code>
   */
  MODEL_ANTHROPIC_CLAUDE_OPUS46_FAST(1202),
  /**
   * <code>MODEL_ANTHROPIC_CLAUDE_SONNET46 = 1203;</code>
   */
  MODEL_ANTHROPIC_CLAUDE_SONNET46(1203),
  /**
   * <code>MODEL_ANTHROPIC_CLAUDE_OPUS46 = 1204;</code>
   */
  MODEL_ANTHROPIC_CLAUDE_OPUS46(1204),
  /**
   * <code>MODEL_ANTHROPIC_CLAUDE_OPUS45 = 1205;</code>
   */
  MODEL_ANTHROPIC_CLAUDE_OPUS45(1205),
  /**
   * <code>MODEL_ANTHROPIC_CLAUDE_HAIKU45 = 1206;</code>
   */
  MODEL_ANTHROPIC_CLAUDE_HAIKU45(1206),
  /**
   * <code>MODEL_ANTHROPIC_CLAUDE_SONNET45 = 1207;</code>
   */
  MODEL_ANTHROPIC_CLAUDE_SONNET45(1207),
  /**
   * <code>MODEL_ANTHROPIC_CLAUDE_OPUS41 = 1208;</code>
   */
  MODEL_ANTHROPIC_CLAUDE_OPUS41(1208),
  /**
   * <code>MODEL_ANTHROPIC_CLAUDE_OPUS4 = 1209;</code>
   */
  MODEL_ANTHROPIC_CLAUDE_OPUS4(1209),
  /**
   * <code>MODEL_ANTHROPIC_CLAUDE_SONNET4 = 1210;</code>
   */
  MODEL_ANTHROPIC_CLAUDE_SONNET4(1210),
  /**
   * <code>MODEL_ANTHROPIC_CLAUDE37_SONNET = 1211;</code>
   */
  MODEL_ANTHROPIC_CLAUDE37_SONNET(1211),
  /**
   * <pre>
   * Arcee AI (1300 - 1399)
   * </pre>
   *
   * <code>MODEL_ARCEE_AI_UNKNOWN = 1300;</code>
   */
  MODEL_ARCEE_AI_UNKNOWN(1300),
  /**
   * <code>MODEL_ARCEE_AI_TRINITY_LARGE_THINKING = 1301;</code>
   */
  MODEL_ARCEE_AI_TRINITY_LARGE_THINKING(1301),
  /**
   * <code>MODEL_ARCEE_AI_TRINITY_MINI = 1302;</code>
   */
  MODEL_ARCEE_AI_TRINITY_MINI(1302),
  /**
   * <code>MODEL_ARCEE_AI_AFM45B = 1303;</code>
   */
  MODEL_ARCEE_AI_AFM45B(1303),
  /**
   * <code>MODEL_ARCEE_AI_CALLER_LARGE = 1304;</code>
   */
  MODEL_ARCEE_AI_CALLER_LARGE(1304),
  /**
   * <code>MODEL_ARCEE_AI_SPOTLIGHT = 1305;</code>
   */
  MODEL_ARCEE_AI_SPOTLIGHT(1305),
  /**
   * <code>MODEL_ARCEE_AI_MAESTRO_REASONING = 1306;</code>
   */
  MODEL_ARCEE_AI_MAESTRO_REASONING(1306),
  /**
   * <code>MODEL_ARCEE_AI_VIRTUOSO_LARGE = 1307;</code>
   */
  MODEL_ARCEE_AI_VIRTUOSO_LARGE(1307),
  /**
   * <code>MODEL_ARCEE_AI_CODER_LARGE = 1308;</code>
   */
  MODEL_ARCEE_AI_CODER_LARGE(1308),
  /**
   * <code>MODEL_ARCEE_AI_VIRTUOSO_MEDIUM_V2 = 1309;</code>
   */
  MODEL_ARCEE_AI_VIRTUOSO_MEDIUM_V2(1309),
  /**
   * <code>MODEL_ARCEE_AI_ARCEE_BLITZ = 1310;</code>
   */
  MODEL_ARCEE_AI_ARCEE_BLITZ(1310),
  /**
   * <pre>
   * Baidu (1400 - 1499)
   * </pre>
   *
   * <code>MODEL_BAIDU_UNKNOWN = 1400;</code>
   */
  MODEL_BAIDU_UNKNOWN(1400),
  /**
   * <code>MODEL_BAIDU_ERNIE4521B_A3B_THINKING = 1401;</code>
   */
  MODEL_BAIDU_ERNIE4521B_A3B_THINKING(1401),
  /**
   * <code>MODEL_BAIDU_ERNIE4521B_A3B = 1402;</code>
   */
  MODEL_BAIDU_ERNIE4521B_A3B(1402),
  /**
   * <code>MODEL_BAIDU_ERNIE45_VL28B_A3B = 1403;</code>
   */
  MODEL_BAIDU_ERNIE45_VL28B_A3B(1403),
  /**
   * <code>MODEL_BAIDU_ERNIE45_VL424B_A47B = 1404;</code>
   */
  MODEL_BAIDU_ERNIE45_VL424B_A47B(1404),
  /**
   * <code>MODEL_BAIDU_ERNIE45300B_A47B = 1405;</code>
   */
  MODEL_BAIDU_ERNIE45300B_A47B(1405),
  /**
   * <pre>
   * ByteDance (1500 - 1599)
   * </pre>
   *
   * <code>MODEL_BYTEDANCE_UNKNOWN = 1500;</code>
   */
  MODEL_BYTEDANCE_UNKNOWN(1500),
  /**
   * <code>MODEL_BYTEDANCE_SEEDANCE20 = 1501;</code>
   */
  MODEL_BYTEDANCE_SEEDANCE20(1501),
  /**
   * <code>MODEL_BYTEDANCE_SEEDANCE20_FAST = 1502;</code>
   */
  MODEL_BYTEDANCE_SEEDANCE20_FAST(1502),
  /**
   * <code>MODEL_BYTEDANCE_SEEDANCE15_PRO = 1503;</code>
   */
  MODEL_BYTEDANCE_SEEDANCE15_PRO(1503),
  /**
   * <code>MODEL_BYTEDANCE_SEED_OSS36B_INSTRUCT = 1504;</code>
   */
  MODEL_BYTEDANCE_SEED_OSS36B_INSTRUCT(1504),
  /**
   * <code>MODEL_BYTEDANCE_UI_TARS7B = 1505;</code>
   */
  MODEL_BYTEDANCE_UI_TARS7B(1505),
  /**
   * <pre>
   * Deep Cogito (1600 - 1699)
   * </pre>
   *
   * <code>MODEL_DEEP_COGITO_UNKNOWN = 1600;</code>
   */
  MODEL_DEEP_COGITO_UNKNOWN(1600),
  /**
   * <code>MODEL_DEEP_COGITO_COGITO_V2_PREVIEW_LLAMA405B = 1601;</code>
   */
  MODEL_DEEP_COGITO_COGITO_V2_PREVIEW_LLAMA405B(1601),
  /**
   * <code>MODEL_DEEP_COGITO_COGITO_V2_PREVIEW_LLAMA70B = 1602;</code>
   */
  MODEL_DEEP_COGITO_COGITO_V2_PREVIEW_LLAMA70B(1602),
  /**
   * <code>MODEL_DEEP_COGITO_COGITO_V2_PREVIEW_LLAMA109B = 1603;</code>
   */
  MODEL_DEEP_COGITO_COGITO_V2_PREVIEW_LLAMA109B(1603),
  /**
   * <code>MODEL_DEEP_COGITO_COGITO_V2_PREVIEW_DEEPSEEK671B = 1604;</code>
   */
  MODEL_DEEP_COGITO_COGITO_V2_PREVIEW_DEEPSEEK671B(1604),
  /**
   * <pre>
   * DeepSeek (1700 - 1799)
   * </pre>
   *
   * <code>MODEL_DEEPSEEK_UNKNOWN = 1700;</code>
   */
  MODEL_DEEPSEEK_UNKNOWN(1700),
  /**
   * <code>MODEL_DEEPSEEK_V32_SPECIALE = 1701;</code>
   */
  MODEL_DEEPSEEK_V32_SPECIALE(1701),
  /**
   * <code>MODEL_DEEPSEEK_V32 = 1702;</code>
   */
  MODEL_DEEPSEEK_V32(1702),
  /**
   * <code>MODEL_DEEPSEEK_V31_TERMINUS = 1703;</code>
   */
  MODEL_DEEPSEEK_V31_TERMINUS(1703),
  /**
   * <code>MODEL_DEEPSEEK_V31 = 1704;</code>
   */
  MODEL_DEEPSEEK_V31(1704),
  /**
   * <code>MODEL_DEEPSEEK_V31_BASE = 1705;</code>
   */
  MODEL_DEEPSEEK_V31_BASE(1705),
  /**
   * <code>MODEL_DEEPSEEK_R1_DISTILL_QWEN7B = 1706;</code>
   */
  MODEL_DEEPSEEK_R1_DISTILL_QWEN7B(1706),
  /**
   * <code>MODEL_DEEPSEEK_R10528_QWEN38B = 1707;</code>
   */
  MODEL_DEEPSEEK_R10528_QWEN38B(1707),
  /**
   * <code>MODEL_DEEPSEEK_PROVER_V2 = 1708;</code>
   */
  MODEL_DEEPSEEK_PROVER_V2(1708),
  /**
   * <code>MODEL_DEEPSEEK_V3_BASE = 1709;</code>
   */
  MODEL_DEEPSEEK_V3_BASE(1709),
  /**
   * <code>MODEL_DEEPSEEK_R1_ZERO = 1710;</code>
   */
  MODEL_DEEPSEEK_R1_ZERO(1710),
  /**
   * <code>MODEL_DEEPSEEK_R1_DISTILL_LLAMA8B = 1711;</code>
   */
  MODEL_DEEPSEEK_R1_DISTILL_LLAMA8B(1711),
  /**
   * <code>MODEL_DEEPSEEK_R1_DISTILL_QWEN15B = 1712;</code>
   */
  MODEL_DEEPSEEK_R1_DISTILL_QWEN15B(1712),
  /**
   * <code>MODEL_DEEPSEEK_R1_DISTILL_QWEN32B = 1713;</code>
   */
  MODEL_DEEPSEEK_R1_DISTILL_QWEN32B(1713),
  /**
   * <code>MODEL_DEEPSEEK_R1_DISTILL_QWEN14B = 1714;</code>
   */
  MODEL_DEEPSEEK_R1_DISTILL_QWEN14B(1714),
  /**
   * <code>MODEL_DEEPSEEK_R1_DISTILL_LLAMA70B = 1715;</code>
   */
  MODEL_DEEPSEEK_R1_DISTILL_LLAMA70B(1715),
  /**
   * <pre>
   * Google (1800 - 1899)
   * </pre>
   *
   * <code>MODEL_GOOGLE_UNKNOWN = 1800;</code>
   */
  MODEL_GOOGLE_UNKNOWN(1800),
  /**
   * <code>MODEL_GOOGLE_GEMINI36_FLASH = 1801;</code>
   */
  MODEL_GOOGLE_GEMINI36_FLASH(1801),
  /**
   * <code>MODEL_GOOGLE_GEMINI35_FLASH = 1802;</code>
   */
  MODEL_GOOGLE_GEMINI35_FLASH(1802),
  /**
   * <code>MODEL_GOOGLE_GEMINI31_PRO = 1803;</code>
   */
  MODEL_GOOGLE_GEMINI31_PRO(1803),
  /**
   * <code>MODEL_GOOGLE_GEMINI31_FLASH = 1804;</code>
   */
  MODEL_GOOGLE_GEMINI31_FLASH(1804),
  /**
   * <code>MODEL_GOOGLE_GEMINI31_FLASH_LITE = 1805;</code>
   */
  MODEL_GOOGLE_GEMINI31_FLASH_LITE(1805),
  /**
   * <code>MODEL_GOOGLE_GEMINI30_PRO = 1806;</code>
   */
  MODEL_GOOGLE_GEMINI30_PRO(1806),
  /**
   * <code>MODEL_GOOGLE_GEMINI30_FLASH = 1807;</code>
   */
  MODEL_GOOGLE_GEMINI30_FLASH(1807),
  /**
   * <code>MODEL_GOOGLE_GEMINI30_FLASH_LITE = 1808;</code>
   */
  MODEL_GOOGLE_GEMINI30_FLASH_LITE(1808),
  /**
   * <code>MODEL_GOOGLE_GEMINI_EMBEDDING001 = 1809;</code>
   */
  MODEL_GOOGLE_GEMINI_EMBEDDING001(1809),
  /**
   * <code>MODEL_GOOGLE_GEMINI25_FLASH_LITE = 1810;</code>
   */
  MODEL_GOOGLE_GEMINI25_FLASH_LITE(1810),
  /**
   * <code>MODEL_GOOGLE_GEMINI25_FLASH = 1811;</code>
   */
  MODEL_GOOGLE_GEMINI25_FLASH(1811),
  /**
   * <code>MODEL_GOOGLE_GEMINI25_PRO = 1812;</code>
   */
  MODEL_GOOGLE_GEMINI25_PRO(1812),
  /**
   * <code>MODEL_GOOGLE_GEMMA12B = 1813;</code>
   */
  MODEL_GOOGLE_GEMMA12B(1813),
  /**
   * <code>MODEL_GOOGLE_GEMMA3N4B = 1814;</code>
   */
  MODEL_GOOGLE_GEMMA3N4B(1814),
  /**
   * <code>MODEL_GOOGLE_GEMMA31B = 1815;</code>
   */
  MODEL_GOOGLE_GEMMA31B(1815),
  /**
   * <code>MODEL_GOOGLE_GEMMA34B = 1816;</code>
   */
  MODEL_GOOGLE_GEMMA34B(1816),
  /**
   * <code>MODEL_GOOGLE_GEMMA312B = 1817;</code>
   */
  MODEL_GOOGLE_GEMMA312B(1817),
  /**
   * <code>MODEL_GOOGLE_GEMMA327B = 1818;</code>
   */
  MODEL_GOOGLE_GEMMA327B(1818),
  /**
   * <code>MODEL_GOOGLE_GEMINI20_FLASH_LITE = 1819;</code>
   */
  MODEL_GOOGLE_GEMINI20_FLASH_LITE(1819),
  /**
   * <code>MODEL_GOOGLE_GEMINI20_FLASH = 1820;</code>
   */
  MODEL_GOOGLE_GEMINI20_FLASH(1820),
  /**
   * <code>MODEL_GOOGLE_GEMMA431B = 1821;</code>
   */
  MODEL_GOOGLE_GEMMA431B(1821),
  /**
   * <code>MODEL_GOOGLE_GEMMA426B = 1822;</code>
   */
  MODEL_GOOGLE_GEMMA426B(1822),
  /**
   * <code>MODEL_GOOGLE_GEMMA44B = 1823;</code>
   */
  MODEL_GOOGLE_GEMMA44B(1823),
  /**
   * <code>MODEL_GOOGLE_GEMMA42B = 1824;</code>
   */
  MODEL_GOOGLE_GEMMA42B(1824),
  /**
   * <code>MODEL_GOOGLE_GEMMA = 1825;</code>
   */
  MODEL_GOOGLE_GEMMA(1825),
  /**
   * <code>MODEL_GOOGLE_GEMINI37_FLASH = 1826;</code>
   */
  MODEL_GOOGLE_GEMINI37_FLASH(1826),
  /**
   * <code>MODEL_GOOGLE_GEMINI38_FLASH = 1827;</code>
   */
  MODEL_GOOGLE_GEMINI38_FLASH(1827),
  /**
   * <pre>
   * LiquidAI (1900 - 1999)
   * </pre>
   *
   * <code>MODEL_LIQUID_AI_UNKNOWN = 1900;</code>
   */
  MODEL_LIQUID_AI_UNKNOWN(1900),
  /**
   * <code>MODEL_LIQUID_AI_LFM224B_A2B = 1901;</code>
   */
  MODEL_LIQUID_AI_LFM224B_A2B(1901),
  /**
   * <code>MODEL_LIQUID_AI_LFM28B_A1B = 1902;</code>
   */
  MODEL_LIQUID_AI_LFM28B_A1B(1902),
  /**
   * <code>MODEL_LIQUID_AI_LFM226B = 1903;</code>
   */
  MODEL_LIQUID_AI_LFM226B(1903),
  /**
   * <code>MODEL_LIQUID_AI_LFM7B = 1904;</code>
   */
  MODEL_LIQUID_AI_LFM7B(1904),
  /**
   * <code>MODEL_LIQUID_AI_LFM3B = 1905;</code>
   */
  MODEL_LIQUID_AI_LFM3B(1905),
  /**
   * <pre>
   * Meta (2000 - 2099)
   * </pre>
   *
   * <code>MODEL_META_UNKNOWN = 2000;</code>
   */
  MODEL_META_UNKNOWN(2000),
  /**
   * <code>MODEL_META_LLAMA_GUARD412B = 2001;</code>
   */
  MODEL_META_LLAMA_GUARD412B(2001),
  /**
   * <code>MODEL_META_LLAMA4_MAVERICK = 2002;</code>
   */
  MODEL_META_LLAMA4_MAVERICK(2002),
  /**
   * <code>MODEL_META_LLAMA4_SCOUT = 2003;</code>
   */
  MODEL_META_LLAMA4_SCOUT(2003),
  /**
   * <code>MODEL_META_LLAMA_GUARD38B = 2004;</code>
   */
  MODEL_META_LLAMA_GUARD38B(2004),
  /**
   * <code>MODEL_META_LLAMA3370B_INSTRUCT = 2005;</code>
   */
  MODEL_META_LLAMA3370B_INSTRUCT(2005),
  /**
   * <code>MODEL_META_LLAMA323B_INSTRUCT = 2006;</code>
   */
  MODEL_META_LLAMA323B_INSTRUCT(2006),
  /**
   * <code>MODEL_META_LLAMA321B_INSTRUCT = 2007;</code>
   */
  MODEL_META_LLAMA321B_INSTRUCT(2007),
  /**
   * <code>MODEL_META_LLAMA3290B_VISION_INSTRUCT = 2008;</code>
   */
  MODEL_META_LLAMA3290B_VISION_INSTRUCT(2008),
  /**
   * <code>MODEL_META_LLAMA3211B_VISION_INSTRUCT = 2009;</code>
   */
  MODEL_META_LLAMA3211B_VISION_INSTRUCT(2009),
  /**
   * <pre>
   * Microsoft (2100 - 2199)
   * </pre>
   *
   * <code>MODEL_MICROSOFT_UNKNOWN = 2100;</code>
   */
  MODEL_MICROSOFT_UNKNOWN(2100),
  /**
   * <code>MODEL_MICROSOFT_PHI4_REASONING_PLUS = 2101;</code>
   */
  MODEL_MICROSOFT_PHI4_REASONING_PLUS(2101),
  /**
   * <code>MODEL_MICROSOFT_PHI4_REASONING = 2102;</code>
   */
  MODEL_MICROSOFT_PHI4_REASONING(2102),
  /**
   * <code>MODEL_MICROSOFT_MAI_DS_R1 = 2103;</code>
   */
  MODEL_MICROSOFT_MAI_DS_R1(2103),
  /**
   * <code>MODEL_MICROSOFT_PHI4_MULTIMODAL_INSTRUCT = 2104;</code>
   */
  MODEL_MICROSOFT_PHI4_MULTIMODAL_INSTRUCT(2104),
  /**
   * <code>MODEL_MICROSOFT_PHI4 = 2105;</code>
   */
  MODEL_MICROSOFT_PHI4(2105),
  /**
   * <code>MODEL_MICROSOFT_PHI35_MINI128K_INSTRUCT = 2106;</code>
   */
  MODEL_MICROSOFT_PHI35_MINI128K_INSTRUCT(2106),
  /**
   * <pre>
   * Mistral (2200 - 2299)
   * </pre>
   *
   * <code>MODEL_MISTRAL_UNKNOWN = 2200;</code>
   */
  MODEL_MISTRAL_UNKNOWN(2200),
  /**
   * <code>MODEL_MISTRAL_SMALL_CREATIVE = 2201;</code>
   */
  MODEL_MISTRAL_SMALL_CREATIVE(2201),
  /**
   * <code>MODEL_MISTRAL_MEDIUM31 = 2202;</code>
   */
  MODEL_MISTRAL_MEDIUM31(2202),
  /**
   * <code>MODEL_MISTRAL_DEVSTRAL_MEDIUM = 2203;</code>
   */
  MODEL_MISTRAL_DEVSTRAL_MEDIUM(2203),
  /**
   * <code>MODEL_MISTRAL_DEVSTRAL_SMALL11 = 2204;</code>
   */
  MODEL_MISTRAL_DEVSTRAL_SMALL11(2204),
  /**
   * <code>MODEL_MISTRAL_SMALL3224B = 2205;</code>
   */
  MODEL_MISTRAL_SMALL3224B(2205),
  /**
   * <code>MODEL_MISTRAL_MEDIUM3 = 2206;</code>
   */
  MODEL_MISTRAL_MEDIUM3(2206),
  /**
   * <code>MODEL_MISTRAL_SMALL3124B = 2207;</code>
   */
  MODEL_MISTRAL_SMALL3124B(2207),
  /**
   * <code>MODEL_MISTRAL_SABA = 2208;</code>
   */
  MODEL_MISTRAL_SABA(2208),
  /**
   * <pre>
   * Nous (2300 - 2399)
   * </pre>
   *
   * <code>MODEL_NOUS_UNKNOWN = 2300;</code>
   */
  MODEL_NOUS_UNKNOWN(2300),
  /**
   * <code>MODEL_NOUS_HERMES470B = 2301;</code>
   */
  MODEL_NOUS_HERMES470B(2301),
  /**
   * <code>MODEL_NOUS_HERMES4405B = 2302;</code>
   */
  MODEL_NOUS_HERMES4405B(2302),
  /**
   * <code>MODEL_NOUS_HERMES370B_INSTRUCT = 2303;</code>
   */
  MODEL_NOUS_HERMES370B_INSTRUCT(2303),
  /**
   * <code>MODEL_NOUS_HERMES3405B_INSTRUCT = 2304;</code>
   */
  MODEL_NOUS_HERMES3405B_INSTRUCT(2304),
  /**
   * <pre>
   * NVIDIA (2400 - 2499)
   * </pre>
   *
   * <code>MODEL_NVIDIA_UNKNOWN = 2400;</code>
   */
  MODEL_NVIDIA_UNKNOWN(2400),
  /**
   * <code>MODEL_NVIDIA_NEMOTRON3_SUPER = 2401;</code>
   */
  MODEL_NVIDIA_NEMOTRON3_SUPER(2401),
  /**
   * <code>MODEL_NVIDIA_NEMOTRON3_NANO30B_A3B = 2402;</code>
   */
  MODEL_NVIDIA_NEMOTRON3_NANO30B_A3B(2402),
  /**
   * <code>MODEL_NVIDIA_NEMOTRON_NANO12B2_VL = 2403;</code>
   */
  MODEL_NVIDIA_NEMOTRON_NANO12B2_VL(2403),
  /**
   * <code>MODEL_NVIDIA_LLAMA33_NEMOTRON_SUPER49B_V15 = 2404;</code>
   */
  MODEL_NVIDIA_LLAMA33_NEMOTRON_SUPER49B_V15(2404),
  /**
   * <code>MODEL_NVIDIA_NEMOTRON_NANO9B_V2 = 2405;</code>
   */
  MODEL_NVIDIA_NEMOTRON_NANO9B_V2(2405),
  /**
   * <code>MODEL_NVIDIA_LLAMA31_NEMOTRON_NANO8B_V1 = 2406;</code>
   */
  MODEL_NVIDIA_LLAMA31_NEMOTRON_NANO8B_V1(2406),
  /**
   * <code>MODEL_NVIDIA_LLAMA33_NEMOTRON_SUPER49B_V1 = 2407;</code>
   */
  MODEL_NVIDIA_LLAMA33_NEMOTRON_SUPER49B_V1(2407),
  /**
   * <code>MODEL_NVIDIA_LLAMA31_NEMOTRON_ULTRA253B_V1 = 2408;</code>
   */
  MODEL_NVIDIA_LLAMA31_NEMOTRON_ULTRA253B_V1(2408),
  /**
   * <pre>
   * OpenAI (2500 - 2599)
   * </pre>
   *
   * <code>MODEL_OPENAI_UNKNOWN = 2500;</code>
   */
  MODEL_OPENAI_UNKNOWN(2500),
  /**
   * <code>MODEL_OPENAI_SORA2_PRO = 2501;</code>
   */
  MODEL_OPENAI_SORA2_PRO(2501),
  /**
   * <code>MODEL_OPENAI_GPT54_NANO = 2502;</code>
   */
  MODEL_OPENAI_GPT54_NANO(2502),
  /**
   * <code>MODEL_OPENAI_GPT54_MINI = 2503;</code>
   */
  MODEL_OPENAI_GPT54_MINI(2503),
  /**
   * <code>MODEL_OPENAI_GPT54_PRO = 2504;</code>
   */
  MODEL_OPENAI_GPT54_PRO(2504),
  /**
   * <code>MODEL_OPENAI_GPT54 = 2505;</code>
   */
  MODEL_OPENAI_GPT54(2505),
  /**
   * <code>MODEL_OPENAI_GPT53_CHAT = 2506;</code>
   */
  MODEL_OPENAI_GPT53_CHAT(2506),
  /**
   * <code>MODEL_OPENAI_GPT53_CODEX = 2507;</code>
   */
  MODEL_OPENAI_GPT53_CODEX(2507),
  /**
   * <code>MODEL_OPENAI_GPT_AUDIO = 2508;</code>
   */
  MODEL_OPENAI_GPT_AUDIO(2508),
  /**
   * <code>MODEL_OPENAI_GPT_AUDIO_MINI = 2509;</code>
   */
  MODEL_OPENAI_GPT_AUDIO_MINI(2509),
  /**
   * <code>MODEL_OPENAI_GPT52_CODEX = 2510;</code>
   */
  MODEL_OPENAI_GPT52_CODEX(2510),
  /**
   * <code>MODEL_OPENAI_GPT52_CHAT = 2511;</code>
   */
  MODEL_OPENAI_GPT52_CHAT(2511),
  /**
   * <code>MODEL_OPENAI_GPT52_PRO = 2512;</code>
   */
  MODEL_OPENAI_GPT52_PRO(2512),
  /**
   * <code>MODEL_OPENAI_GPT52 = 2513;</code>
   */
  MODEL_OPENAI_GPT52(2513),
  /**
   * <code>MODEL_OPENAI_GPT51_CODEX_MAX = 2514;</code>
   */
  MODEL_OPENAI_GPT51_CODEX_MAX(2514),
  /**
   * <code>MODEL_OPENAI_GPT51 = 2515;</code>
   */
  MODEL_OPENAI_GPT51(2515),
  /**
   * <code>MODEL_OPENAI_GPT51_CHAT = 2516;</code>
   */
  MODEL_OPENAI_GPT51_CHAT(2516),
  /**
   * <code>MODEL_OPENAI_GPT51_CODEX = 2517;</code>
   */
  MODEL_OPENAI_GPT51_CODEX(2517),
  /**
   * <code>MODEL_OPENAI_GPT51_CODEX_MINI = 2518;</code>
   */
  MODEL_OPENAI_GPT51_CODEX_MINI(2518),
  /**
   * <code>MODEL_OPENAI_TEXT_EMBEDDING_ADA002 = 2519;</code>
   */
  MODEL_OPENAI_TEXT_EMBEDDING_ADA002(2519),
  /**
   * <code>MODEL_OPENAI_TEXT_EMBEDDING3_LARGE = 2520;</code>
   */
  MODEL_OPENAI_TEXT_EMBEDDING3_LARGE(2520),
  /**
   * <code>MODEL_OPENAI_TEXT_EMBEDDING3_SMALL = 2521;</code>
   */
  MODEL_OPENAI_TEXT_EMBEDDING3_SMALL(2521),
  /**
   * <code>MODEL_OPENAI_GPT_OSS_SAFEGUARD20B = 2522;</code>
   */
  MODEL_OPENAI_GPT_OSS_SAFEGUARD20B(2522),
  /**
   * <code>MODEL_OPENAI_GPT5_IMAGE_MINI = 2523;</code>
   */
  MODEL_OPENAI_GPT5_IMAGE_MINI(2523),
  /**
   * <code>MODEL_OPENAI_GPT5_IMAGE = 2524;</code>
   */
  MODEL_OPENAI_GPT5_IMAGE(2524),
  /**
   * <code>MODEL_OPENAI_O3_DEEP_RESEARCH = 2525;</code>
   */
  MODEL_OPENAI_O3_DEEP_RESEARCH(2525),
  /**
   * <code>MODEL_OPENAI_O4_MINI_DEEP_RESEARCH = 2526;</code>
   */
  MODEL_OPENAI_O4_MINI_DEEP_RESEARCH(2526),
  /**
   * <code>MODEL_OPENAI_GPT5_PRO = 2527;</code>
   */
  MODEL_OPENAI_GPT5_PRO(2527),
  /**
   * <code>MODEL_OPENAI_GPT5_CODEX = 2528;</code>
   */
  MODEL_OPENAI_GPT5_CODEX(2528),
  /**
   * <code>MODEL_OPENAI_GPT5_CHAT = 2529;</code>
   */
  MODEL_OPENAI_GPT5_CHAT(2529),
  /**
   * <code>MODEL_OPENAI_GPT5 = 2530;</code>
   */
  MODEL_OPENAI_GPT5(2530),
  /**
   * <code>MODEL_OPENAI_GPT5_MINI = 2531;</code>
   */
  MODEL_OPENAI_GPT5_MINI(2531),
  /**
   * <code>MODEL_OPENAI_GPT5_NANO = 2532;</code>
   */
  MODEL_OPENAI_GPT5_NANO(2532),
  /**
   * <code>MODEL_OPENAI_GPT_OSS120B = 2533;</code>
   */
  MODEL_OPENAI_GPT_OSS120B(2533),
  /**
   * <code>MODEL_OPENAI_GPT_OSS20B = 2534;</code>
   */
  MODEL_OPENAI_GPT_OSS20B(2534),
  /**
   * <code>MODEL_OPENAI_O3_PRO = 2535;</code>
   */
  MODEL_OPENAI_O3_PRO(2535),
  /**
   * <code>MODEL_OPENAI_CODEX_MINI = 2536;</code>
   */
  MODEL_OPENAI_CODEX_MINI(2536),
  /**
   * <code>MODEL_OPENAI_O4_MINI_HIGH = 2537;</code>
   */
  MODEL_OPENAI_O4_MINI_HIGH(2537),
  /**
   * <code>MODEL_OPENAI_O3 = 2538;</code>
   */
  MODEL_OPENAI_O3(2538),
  /**
   * <code>MODEL_OPENAI_O4_MINI = 2539;</code>
   */
  MODEL_OPENAI_O4_MINI(2539),
  /**
   * <code>MODEL_OPENAI_GPT41 = 2540;</code>
   */
  MODEL_OPENAI_GPT41(2540),
  /**
   * <code>MODEL_OPENAI_GPT41_MINI = 2541;</code>
   */
  MODEL_OPENAI_GPT41_MINI(2541),
  /**
   * <code>MODEL_OPENAI_GPT41_NANO = 2542;</code>
   */
  MODEL_OPENAI_GPT41_NANO(2542),
  /**
   * <code>MODEL_OPENAI_O1_PRO = 2543;</code>
   */
  MODEL_OPENAI_O1_PRO(2543),
  /**
   * <code>MODEL_OPENAI_O3_MINI_HIGH = 2544;</code>
   */
  MODEL_OPENAI_O3_MINI_HIGH(2544),
  /**
   * <code>MODEL_OPENAI_O3_MINI = 2545;</code>
   */
  MODEL_OPENAI_O3_MINI(2545),
  /**
   * <pre>
   * Perplexity (2600 - 2699)
   * </pre>
   *
   * <code>MODEL_PERPLEXITY_UNKNOWN = 2600;</code>
   */
  MODEL_PERPLEXITY_UNKNOWN(2600),
  /**
   * <code>MODEL_PERPLEXITY_EMBED_V14B = 2601;</code>
   */
  MODEL_PERPLEXITY_EMBED_V14B(2601),
  /**
   * <code>MODEL_PERPLEXITY_EMBED_V106B = 2602;</code>
   */
  MODEL_PERPLEXITY_EMBED_V106B(2602),
  /**
   * <code>MODEL_PERPLEXITY_SONAR_PRO_SEARCH = 2603;</code>
   */
  MODEL_PERPLEXITY_SONAR_PRO_SEARCH(2603),
  /**
   * <code>MODEL_PERPLEXITY_SONAR_REASONING_PRO = 2604;</code>
   */
  MODEL_PERPLEXITY_SONAR_REASONING_PRO(2604),
  /**
   * <code>MODEL_PERPLEXITY_SONAR_PRO = 2605;</code>
   */
  MODEL_PERPLEXITY_SONAR_PRO(2605),
  /**
   * <code>MODEL_PERPLEXITY_SONAR_DEEP_RESEARCH = 2606;</code>
   */
  MODEL_PERPLEXITY_SONAR_DEEP_RESEARCH(2606),
  /**
   * <code>MODEL_PERPLEXITY_SONAR_REASONING = 2607;</code>
   */
  MODEL_PERPLEXITY_SONAR_REASONING(2607),
  /**
   * <code>MODEL_PERPLEXITY_SONAR = 2608;</code>
   */
  MODEL_PERPLEXITY_SONAR(2608),
  /**
   * <pre>
   * Qwen (2700 - 2799)
   * </pre>
   *
   * <code>MODEL_QWEN_UNKNOWN = 2700;</code>
   */
  MODEL_QWEN_UNKNOWN(2700),
  /**
   * <code>MODEL_QWEN36_PLUS = 2701;</code>
   */
  MODEL_QWEN36_PLUS(2701),
  /**
   * <code>MODEL_QWEN359B = 2702;</code>
   */
  MODEL_QWEN359B(2702),
  /**
   * <code>MODEL_QWEN3535B_A3B = 2703;</code>
   */
  MODEL_QWEN3535B_A3B(2703),
  /**
   * <code>MODEL_QWEN3527B = 2704;</code>
   */
  MODEL_QWEN3527B(2704),
  /**
   * <code>MODEL_QWEN35122B_A10B = 2705;</code>
   */
  MODEL_QWEN35122B_A10B(2705),
  /**
   * <code>MODEL_QWEN35_FLASH = 2706;</code>
   */
  MODEL_QWEN35_FLASH(2706),
  /**
   * <code>MODEL_QWEN35_PLUS20260215 = 2707;</code>
   */
  MODEL_QWEN35_PLUS20260215(2707),
  /**
   * <code>MODEL_QWEN35397B_A17B = 2708;</code>
   */
  MODEL_QWEN35397B_A17B(2708),
  /**
   * <code>MODEL_QWEN3_MAX_THINKING = 2709;</code>
   */
  MODEL_QWEN3_MAX_THINKING(2709),
  /**
   * <code>MODEL_QWEN3_CODER_NEXT = 2710;</code>
   */
  MODEL_QWEN3_CODER_NEXT(2710),
  /**
   * <code>MODEL_QWEN3_EMBEDDING06B = 2711;</code>
   */
  MODEL_QWEN3_EMBEDDING06B(2711),
  /**
   * <code>MODEL_QWEN3_EMBEDDING8B = 2712;</code>
   */
  MODEL_QWEN3_EMBEDDING8B(2712),
  /**
   * <code>MODEL_QWEN3_EMBEDDING4B = 2713;</code>
   */
  MODEL_QWEN3_EMBEDDING4B(2713),
  /**
   * <code>MODEL_QWEN3_VL32B_INSTRUCT = 2714;</code>
   */
  MODEL_QWEN3_VL32B_INSTRUCT(2714),
  /**
   * <code>MODEL_QWEN3_VL8B_THINKING = 2715;</code>
   */
  MODEL_QWEN3_VL8B_THINKING(2715),
  /**
   * <code>MODEL_QWEN3_VL8B_INSTRUCT = 2716;</code>
   */
  MODEL_QWEN3_VL8B_INSTRUCT(2716),
  /**
   * <code>MODEL_QWEN3_VL30B_A3B_THINKING = 2717;</code>
   */
  MODEL_QWEN3_VL30B_A3B_THINKING(2717),
  /**
   * <code>MODEL_QWEN3_VL30B_A3B_INSTRUCT = 2718;</code>
   */
  MODEL_QWEN3_VL30B_A3B_INSTRUCT(2718),
  /**
   * <code>MODEL_QWEN3_VL235B_A22B_THINKING = 2719;</code>
   */
  MODEL_QWEN3_VL235B_A22B_THINKING(2719),
  /**
   * <code>MODEL_QWEN3_VL235B_A22B_INSTRUCT = 2720;</code>
   */
  MODEL_QWEN3_VL235B_A22B_INSTRUCT(2720),
  /**
   * <code>MODEL_QWEN3_MAX = 2721;</code>
   */
  MODEL_QWEN3_MAX(2721),
  /**
   * <code>MODEL_QWEN3_CODER_PLUS = 2722;</code>
   */
  MODEL_QWEN3_CODER_PLUS(2722),
  /**
   * <code>MODEL_QWEN3_CODER_FLASH = 2723;</code>
   */
  MODEL_QWEN3_CODER_FLASH(2723),
  /**
   * <code>MODEL_QWEN3_NEXT80B_A3B_THINKING = 2724;</code>
   */
  MODEL_QWEN3_NEXT80B_A3B_THINKING(2724),
  /**
   * <code>MODEL_QWEN3_NEXT80B_A3B_INSTRUCT = 2725;</code>
   */
  MODEL_QWEN3_NEXT80B_A3B_INSTRUCT(2725),
  /**
   * <code>MODEL_QWEN3_CODER30B_A3B_INSTRUCT = 2726;</code>
   */
  MODEL_QWEN3_CODER30B_A3B_INSTRUCT(2726),
  /**
   * <code>MODEL_QWEN3_CODER480B_A35B = 2727;</code>
   */
  MODEL_QWEN3_CODER480B_A35B(2727),
  /**
   * <code>MODEL_QWEN306B = 2728;</code>
   */
  MODEL_QWEN306B(2728),
  /**
   * <code>MODEL_QWEN317B = 2729;</code>
   */
  MODEL_QWEN317B(2729),
  /**
   * <code>MODEL_QWEN34B = 2730;</code>
   */
  MODEL_QWEN34B(2730),
  /**
   * <code>MODEL_QWEN330B_A3B = 2731;</code>
   */
  MODEL_QWEN330B_A3B(2731),
  /**
   * <code>MODEL_QWEN38B = 2732;</code>
   */
  MODEL_QWEN38B(2732),
  /**
   * <code>MODEL_QWEN314B = 2733;</code>
   */
  MODEL_QWEN314B(2733),
  /**
   * <code>MODEL_QWEN332B = 2734;</code>
   */
  MODEL_QWEN332B(2734),
  /**
   * <code>MODEL_QWEN3235B_A22B = 2735;</code>
   */
  MODEL_QWEN3235B_A22B(2735),
  /**
   * <code>MODEL_QWEN25_CODER7B_INSTRUCT = 2736;</code>
   */
  MODEL_QWEN25_CODER7B_INSTRUCT(2736),
  /**
   * <code>MODEL_QWEN25_VL3B_INSTRUCT = 2737;</code>
   */
  MODEL_QWEN25_VL3B_INSTRUCT(2737),
  /**
   * <code>MODEL_QWEN25_VL32B_INSTRUCT = 2738;</code>
   */
  MODEL_QWEN25_VL32B_INSTRUCT(2738),
  /**
   * <code>MODEL_QWEN_QWQ32B = 2739;</code>
   */
  MODEL_QWEN_QWQ32B(2739),
  /**
   * <code>MODEL_QWEN2532B_INSTRUCT = 2740;</code>
   */
  MODEL_QWEN2532B_INSTRUCT(2740),
  /**
   * <code>MODEL_QWEN_VL_PLUS = 2741;</code>
   */
  MODEL_QWEN_VL_PLUS(2741),
  /**
   * <code>MODEL_QWEN_VL_MAX = 2742;</code>
   */
  MODEL_QWEN_VL_MAX(2742),
  /**
   * <code>MODEL_QWEN_TURBO = 2743;</code>
   */
  MODEL_QWEN_TURBO(2743),
  /**
   * <code>MODEL_QWEN25_VL72B_INSTRUCT = 2744;</code>
   */
  MODEL_QWEN25_VL72B_INSTRUCT(2744),
  /**
   * <code>MODEL_QWEN_PLUS = 2745;</code>
   */
  MODEL_QWEN_PLUS(2745),
  /**
   * <code>MODEL_QWEN_MAX = 2746;</code>
   */
  MODEL_QWEN_MAX(2746),
  /**
   * <pre>
   * TheDrummer (2800 - 2899)
   * </pre>
   *
   * <code>MODEL_THE_DRUMMER_UNKNOWN = 2800;</code>
   */
  MODEL_THE_DRUMMER_UNKNOWN(2800),
  /**
   * <code>MODEL_THE_DRUMMER_CYDONIA24B_V41 = 2801;</code>
   */
  MODEL_THE_DRUMMER_CYDONIA24B_V41(2801),
  /**
   * <code>MODEL_THE_DRUMMER_ANUBIS70B_V11 = 2802;</code>
   */
  MODEL_THE_DRUMMER_ANUBIS70B_V11(2802),
  /**
   * <code>MODEL_THE_DRUMMER_VALKYRIE49B_V1 = 2803;</code>
   */
  MODEL_THE_DRUMMER_VALKYRIE49B_V1(2803),
  /**
   * <code>MODEL_THE_DRUMMER_ANUBIS_PRO105B_V1 = 2804;</code>
   */
  MODEL_THE_DRUMMER_ANUBIS_PRO105B_V1(2804),
  /**
   * <code>MODEL_THE_DRUMMER_SKYFALL36B_V2 = 2805;</code>
   */
  MODEL_THE_DRUMMER_SKYFALL36B_V2(2805),
  /**
   * <code>MODEL_THE_DRUMMER_UNSLOPNEMO12B = 2806;</code>
   */
  MODEL_THE_DRUMMER_UNSLOPNEMO12B(2806),
  /**
   * <code>MODEL_THE_DRUMMER_ROCINANTE12B = 2807;</code>
   */
  MODEL_THE_DRUMMER_ROCINANTE12B(2807),
  /**
   * <pre>
   * THUDM (2900 - 2999)
   * </pre>
   *
   * <code>MODEL_THUDM_UNKNOWN = 2900;</code>
   */
  MODEL_THUDM_UNKNOWN(2900),
  /**
   * <code>MODEL_THUDM_GLM41V9B_THINKING = 2901;</code>
   */
  MODEL_THUDM_GLM41V9B_THINKING(2901),
  /**
   * <code>MODEL_THUDM_GLM_Z1_RUMINATION32B = 2902;</code>
   */
  MODEL_THUDM_GLM_Z1_RUMINATION32B(2902),
  /**
   * <code>MODEL_THUDM_GLM_Z19B = 2903;</code>
   */
  MODEL_THUDM_GLM_Z19B(2903),
  /**
   * <code>MODEL_THUDM_GLM49B = 2904;</code>
   */
  MODEL_THUDM_GLM49B(2904),
  /**
   * <code>MODEL_THUDM_GLM_Z132B = 2905;</code>
   */
  MODEL_THUDM_GLM_Z132B(2905),
  /**
   * <code>MODEL_THUDM_GLM432B = 2906;</code>
   */
  MODEL_THUDM_GLM432B(2906),
  /**
   * <pre>
   * TNG (3000 - 3099)
   * </pre>
   *
   * <code>MODEL_TNG_UNKNOWN = 3000;</code>
   */
  MODEL_TNG_UNKNOWN(3000),
  /**
   * <code>MODEL_TNG_DEEPSEEK_R1T2_CHIMERA = 3001;</code>
   */
  MODEL_TNG_DEEPSEEK_R1T2_CHIMERA(3001),
  /**
   * <code>MODEL_TNG_DEEPSEEK_R1T_CHIMERA = 3002;</code>
   */
  MODEL_TNG_DEEPSEEK_R1T_CHIMERA(3002),
  /**
   * <pre>
   * xAI (3100 - 3199)
   * </pre>
   *
   * <code>MODEL_XAI_UNKNOWN = 3100;</code>
   */
  MODEL_XAI_UNKNOWN(3100),
  /**
   * <code>MODEL_XAI_GROK4_FAST = 3101;</code>
   */
  MODEL_XAI_GROK4_FAST(3101),
  /**
   * <code>MODEL_XAI_GROK_CODE_FAST1 = 3102;</code>
   */
  MODEL_XAI_GROK_CODE_FAST1(3102),
  /**
   * <code>MODEL_XAI_GROK4 = 3103;</code>
   */
  MODEL_XAI_GROK4(3103),
  /**
   * <code>MODEL_XAI_GROK3_MINI = 3104;</code>
   */
  MODEL_XAI_GROK3_MINI(3104),
  /**
   * <code>MODEL_XAI_GROK3 = 3105;</code>
   */
  MODEL_XAI_GROK3(3105),
  /**
   * <code>MODEL_XAI_GROK2_MINI = 3106;</code>
   */
  MODEL_XAI_GROK2_MINI(3106),
  /**
   * <code>MODEL_XAI_GROK2 = 3107;</code>
   */
  MODEL_XAI_GROK2(3107),
  /**
   * <pre>
   * Z.AI (3200 - 3299)
   * </pre>
   *
   * <code>MODEL_ZAI_UNKNOWN = 3200;</code>
   */
  MODEL_ZAI_UNKNOWN(3200),
  /**
   * <code>MODEL_ZAI_GLM46 = 3201;</code>
   */
  MODEL_ZAI_GLM46(3201),
  /**
   * <code>MODEL_ZAI_GLM45V = 3202;</code>
   */
  MODEL_ZAI_GLM45V(3202),
  /**
   * <code>MODEL_ZAI_GLM45 = 3203;</code>
   */
  MODEL_ZAI_GLM45(3203),
  /**
   * <code>MODEL_ZAI_GLM45_AIR = 3204;</code>
   */
  MODEL_ZAI_GLM45_AIR(3204),
  /**
   * <code>MODEL_ZAI_GLM432B = 3205;</code>
   */
  MODEL_ZAI_GLM432B(3205),
  ;

  /**
   * <code>MODEL_UNKNOWN = 0;</code>
   */
  public static final int MODEL_UNKNOWN_VALUE = 0;
  /**
   * <pre>
   * AllenAI (1000 - 1099)
   * </pre>
   *
   * <code>MODEL_ALLEN_AI_UNKNOWN = 1000;</code>
   */
  public static final int MODEL_ALLEN_AI_UNKNOWN_VALUE = 1000;
  /**
   * <code>MODEL_ALLEN_AI_MOLMO28B = 1001;</code>
   */
  public static final int MODEL_ALLEN_AI_MOLMO28B_VALUE = 1001;
  /**
   * <code>MODEL_ALLEN_AI_OLMO3132B_INSTRUCT = 1002;</code>
   */
  public static final int MODEL_ALLEN_AI_OLMO3132B_INSTRUCT_VALUE = 1002;
  /**
   * <code>MODEL_ALLEN_AI_OLMO3132B_THINK = 1003;</code>
   */
  public static final int MODEL_ALLEN_AI_OLMO3132B_THINK_VALUE = 1003;
  /**
   * <code>MODEL_ALLEN_AI_OLMO332B_THINK = 1004;</code>
   */
  public static final int MODEL_ALLEN_AI_OLMO332B_THINK_VALUE = 1004;
  /**
   * <code>MODEL_ALLEN_AI_OLMO37B_INSTRUCT = 1005;</code>
   */
  public static final int MODEL_ALLEN_AI_OLMO37B_INSTRUCT_VALUE = 1005;
  /**
   * <code>MODEL_ALLEN_AI_OLMO37B_THINK = 1006;</code>
   */
  public static final int MODEL_ALLEN_AI_OLMO37B_THINK_VALUE = 1006;
  /**
   * <code>MODEL_ALLEN_AI_OLMO2032532B_INSTRUCT = 1007;</code>
   */
  public static final int MODEL_ALLEN_AI_OLMO2032532B_INSTRUCT_VALUE = 1007;
  /**
   * <code>MODEL_ALLEN_AI_LLAMA31_TULU3405B = 1008;</code>
   */
  public static final int MODEL_ALLEN_AI_LLAMA31_TULU3405B_VALUE = 1008;
  /**
   * <pre>
   * AI21 (1100 - 1199)
   * </pre>
   *
   * <code>MODEL_AI21_UNKNOWN = 1100;</code>
   */
  public static final int MODEL_AI21_UNKNOWN_VALUE = 1100;
  /**
   * <code>MODEL_AI21_JAMBA_MINI17 = 1101;</code>
   */
  public static final int MODEL_AI21_JAMBA_MINI17_VALUE = 1101;
  /**
   * <code>MODEL_AI21_JAMBA_LARGE17 = 1102;</code>
   */
  public static final int MODEL_AI21_JAMBA_LARGE17_VALUE = 1102;
  /**
   * <code>MODEL_AI21_JAMBA16_LARGE = 1103;</code>
   */
  public static final int MODEL_AI21_JAMBA16_LARGE_VALUE = 1103;
  /**
   * <code>MODEL_AI21_JAMBA16_MINI = 1104;</code>
   */
  public static final int MODEL_AI21_JAMBA16_MINI_VALUE = 1104;
  /**
   * <code>MODEL_AI21_JAMBA15_MINI = 1105;</code>
   */
  public static final int MODEL_AI21_JAMBA15_MINI_VALUE = 1105;
  /**
   * <code>MODEL_AI21_JAMBA15_LARGE = 1106;</code>
   */
  public static final int MODEL_AI21_JAMBA15_LARGE_VALUE = 1106;
  /**
   * <pre>
   * Anthropic (1200 - 1299)
   * </pre>
   *
   * <code>MODEL_ANTHROPIC_UNKNOWN = 1200;</code>
   */
  public static final int MODEL_ANTHROPIC_UNKNOWN_VALUE = 1200;
  /**
   * <code>MODEL_ANTHROPIC_CLAUDE_OPUS47 = 1201;</code>
   */
  public static final int MODEL_ANTHROPIC_CLAUDE_OPUS47_VALUE = 1201;
  /**
   * <code>MODEL_ANTHROPIC_CLAUDE_OPUS46_FAST = 1202;</code>
   */
  public static final int MODEL_ANTHROPIC_CLAUDE_OPUS46_FAST_VALUE = 1202;
  /**
   * <code>MODEL_ANTHROPIC_CLAUDE_SONNET46 = 1203;</code>
   */
  public static final int MODEL_ANTHROPIC_CLAUDE_SONNET46_VALUE = 1203;
  /**
   * <code>MODEL_ANTHROPIC_CLAUDE_OPUS46 = 1204;</code>
   */
  public static final int MODEL_ANTHROPIC_CLAUDE_OPUS46_VALUE = 1204;
  /**
   * <code>MODEL_ANTHROPIC_CLAUDE_OPUS45 = 1205;</code>
   */
  public static final int MODEL_ANTHROPIC_CLAUDE_OPUS45_VALUE = 1205;
  /**
   * <code>MODEL_ANTHROPIC_CLAUDE_HAIKU45 = 1206;</code>
   */
  public static final int MODEL_ANTHROPIC_CLAUDE_HAIKU45_VALUE = 1206;
  /**
   * <code>MODEL_ANTHROPIC_CLAUDE_SONNET45 = 1207;</code>
   */
  public static final int MODEL_ANTHROPIC_CLAUDE_SONNET45_VALUE = 1207;
  /**
   * <code>MODEL_ANTHROPIC_CLAUDE_OPUS41 = 1208;</code>
   */
  public static final int MODEL_ANTHROPIC_CLAUDE_OPUS41_VALUE = 1208;
  /**
   * <code>MODEL_ANTHROPIC_CLAUDE_OPUS4 = 1209;</code>
   */
  public static final int MODEL_ANTHROPIC_CLAUDE_OPUS4_VALUE = 1209;
  /**
   * <code>MODEL_ANTHROPIC_CLAUDE_SONNET4 = 1210;</code>
   */
  public static final int MODEL_ANTHROPIC_CLAUDE_SONNET4_VALUE = 1210;
  /**
   * <code>MODEL_ANTHROPIC_CLAUDE37_SONNET = 1211;</code>
   */
  public static final int MODEL_ANTHROPIC_CLAUDE37_SONNET_VALUE = 1211;
  /**
   * <pre>
   * Arcee AI (1300 - 1399)
   * </pre>
   *
   * <code>MODEL_ARCEE_AI_UNKNOWN = 1300;</code>
   */
  public static final int MODEL_ARCEE_AI_UNKNOWN_VALUE = 1300;
  /**
   * <code>MODEL_ARCEE_AI_TRINITY_LARGE_THINKING = 1301;</code>
   */
  public static final int MODEL_ARCEE_AI_TRINITY_LARGE_THINKING_VALUE = 1301;
  /**
   * <code>MODEL_ARCEE_AI_TRINITY_MINI = 1302;</code>
   */
  public static final int MODEL_ARCEE_AI_TRINITY_MINI_VALUE = 1302;
  /**
   * <code>MODEL_ARCEE_AI_AFM45B = 1303;</code>
   */
  public static final int MODEL_ARCEE_AI_AFM45B_VALUE = 1303;
  /**
   * <code>MODEL_ARCEE_AI_CALLER_LARGE = 1304;</code>
   */
  public static final int MODEL_ARCEE_AI_CALLER_LARGE_VALUE = 1304;
  /**
   * <code>MODEL_ARCEE_AI_SPOTLIGHT = 1305;</code>
   */
  public static final int MODEL_ARCEE_AI_SPOTLIGHT_VALUE = 1305;
  /**
   * <code>MODEL_ARCEE_AI_MAESTRO_REASONING = 1306;</code>
   */
  public static final int MODEL_ARCEE_AI_MAESTRO_REASONING_VALUE = 1306;
  /**
   * <code>MODEL_ARCEE_AI_VIRTUOSO_LARGE = 1307;</code>
   */
  public static final int MODEL_ARCEE_AI_VIRTUOSO_LARGE_VALUE = 1307;
  /**
   * <code>MODEL_ARCEE_AI_CODER_LARGE = 1308;</code>
   */
  public static final int MODEL_ARCEE_AI_CODER_LARGE_VALUE = 1308;
  /**
   * <code>MODEL_ARCEE_AI_VIRTUOSO_MEDIUM_V2 = 1309;</code>
   */
  public static final int MODEL_ARCEE_AI_VIRTUOSO_MEDIUM_V2_VALUE = 1309;
  /**
   * <code>MODEL_ARCEE_AI_ARCEE_BLITZ = 1310;</code>
   */
  public static final int MODEL_ARCEE_AI_ARCEE_BLITZ_VALUE = 1310;
  /**
   * <pre>
   * Baidu (1400 - 1499)
   * </pre>
   *
   * <code>MODEL_BAIDU_UNKNOWN = 1400;</code>
   */
  public static final int MODEL_BAIDU_UNKNOWN_VALUE = 1400;
  /**
   * <code>MODEL_BAIDU_ERNIE4521B_A3B_THINKING = 1401;</code>
   */
  public static final int MODEL_BAIDU_ERNIE4521B_A3B_THINKING_VALUE = 1401;
  /**
   * <code>MODEL_BAIDU_ERNIE4521B_A3B = 1402;</code>
   */
  public static final int MODEL_BAIDU_ERNIE4521B_A3B_VALUE = 1402;
  /**
   * <code>MODEL_BAIDU_ERNIE45_VL28B_A3B = 1403;</code>
   */
  public static final int MODEL_BAIDU_ERNIE45_VL28B_A3B_VALUE = 1403;
  /**
   * <code>MODEL_BAIDU_ERNIE45_VL424B_A47B = 1404;</code>
   */
  public static final int MODEL_BAIDU_ERNIE45_VL424B_A47B_VALUE = 1404;
  /**
   * <code>MODEL_BAIDU_ERNIE45300B_A47B = 1405;</code>
   */
  public static final int MODEL_BAIDU_ERNIE45300B_A47B_VALUE = 1405;
  /**
   * <pre>
   * ByteDance (1500 - 1599)
   * </pre>
   *
   * <code>MODEL_BYTEDANCE_UNKNOWN = 1500;</code>
   */
  public static final int MODEL_BYTEDANCE_UNKNOWN_VALUE = 1500;
  /**
   * <code>MODEL_BYTEDANCE_SEEDANCE20 = 1501;</code>
   */
  public static final int MODEL_BYTEDANCE_SEEDANCE20_VALUE = 1501;
  /**
   * <code>MODEL_BYTEDANCE_SEEDANCE20_FAST = 1502;</code>
   */
  public static final int MODEL_BYTEDANCE_SEEDANCE20_FAST_VALUE = 1502;
  /**
   * <code>MODEL_BYTEDANCE_SEEDANCE15_PRO = 1503;</code>
   */
  public static final int MODEL_BYTEDANCE_SEEDANCE15_PRO_VALUE = 1503;
  /**
   * <code>MODEL_BYTEDANCE_SEED_OSS36B_INSTRUCT = 1504;</code>
   */
  public static final int MODEL_BYTEDANCE_SEED_OSS36B_INSTRUCT_VALUE = 1504;
  /**
   * <code>MODEL_BYTEDANCE_UI_TARS7B = 1505;</code>
   */
  public static final int MODEL_BYTEDANCE_UI_TARS7B_VALUE = 1505;
  /**
   * <pre>
   * Deep Cogito (1600 - 1699)
   * </pre>
   *
   * <code>MODEL_DEEP_COGITO_UNKNOWN = 1600;</code>
   */
  public static final int MODEL_DEEP_COGITO_UNKNOWN_VALUE = 1600;
  /**
   * <code>MODEL_DEEP_COGITO_COGITO_V2_PREVIEW_LLAMA405B = 1601;</code>
   */
  public static final int MODEL_DEEP_COGITO_COGITO_V2_PREVIEW_LLAMA405B_VALUE = 1601;
  /**
   * <code>MODEL_DEEP_COGITO_COGITO_V2_PREVIEW_LLAMA70B = 1602;</code>
   */
  public static final int MODEL_DEEP_COGITO_COGITO_V2_PREVIEW_LLAMA70B_VALUE = 1602;
  /**
   * <code>MODEL_DEEP_COGITO_COGITO_V2_PREVIEW_LLAMA109B = 1603;</code>
   */
  public static final int MODEL_DEEP_COGITO_COGITO_V2_PREVIEW_LLAMA109B_VALUE = 1603;
  /**
   * <code>MODEL_DEEP_COGITO_COGITO_V2_PREVIEW_DEEPSEEK671B = 1604;</code>
   */
  public static final int MODEL_DEEP_COGITO_COGITO_V2_PREVIEW_DEEPSEEK671B_VALUE = 1604;
  /**
   * <pre>
   * DeepSeek (1700 - 1799)
   * </pre>
   *
   * <code>MODEL_DEEPSEEK_UNKNOWN = 1700;</code>
   */
  public static final int MODEL_DEEPSEEK_UNKNOWN_VALUE = 1700;
  /**
   * <code>MODEL_DEEPSEEK_V32_SPECIALE = 1701;</code>
   */
  public static final int MODEL_DEEPSEEK_V32_SPECIALE_VALUE = 1701;
  /**
   * <code>MODEL_DEEPSEEK_V32 = 1702;</code>
   */
  public static final int MODEL_DEEPSEEK_V32_VALUE = 1702;
  /**
   * <code>MODEL_DEEPSEEK_V31_TERMINUS = 1703;</code>
   */
  public static final int MODEL_DEEPSEEK_V31_TERMINUS_VALUE = 1703;
  /**
   * <code>MODEL_DEEPSEEK_V31 = 1704;</code>
   */
  public static final int MODEL_DEEPSEEK_V31_VALUE = 1704;
  /**
   * <code>MODEL_DEEPSEEK_V31_BASE = 1705;</code>
   */
  public static final int MODEL_DEEPSEEK_V31_BASE_VALUE = 1705;
  /**
   * <code>MODEL_DEEPSEEK_R1_DISTILL_QWEN7B = 1706;</code>
   */
  public static final int MODEL_DEEPSEEK_R1_DISTILL_QWEN7B_VALUE = 1706;
  /**
   * <code>MODEL_DEEPSEEK_R10528_QWEN38B = 1707;</code>
   */
  public static final int MODEL_DEEPSEEK_R10528_QWEN38B_VALUE = 1707;
  /**
   * <code>MODEL_DEEPSEEK_PROVER_V2 = 1708;</code>
   */
  public static final int MODEL_DEEPSEEK_PROVER_V2_VALUE = 1708;
  /**
   * <code>MODEL_DEEPSEEK_V3_BASE = 1709;</code>
   */
  public static final int MODEL_DEEPSEEK_V3_BASE_VALUE = 1709;
  /**
   * <code>MODEL_DEEPSEEK_R1_ZERO = 1710;</code>
   */
  public static final int MODEL_DEEPSEEK_R1_ZERO_VALUE = 1710;
  /**
   * <code>MODEL_DEEPSEEK_R1_DISTILL_LLAMA8B = 1711;</code>
   */
  public static final int MODEL_DEEPSEEK_R1_DISTILL_LLAMA8B_VALUE = 1711;
  /**
   * <code>MODEL_DEEPSEEK_R1_DISTILL_QWEN15B = 1712;</code>
   */
  public static final int MODEL_DEEPSEEK_R1_DISTILL_QWEN15B_VALUE = 1712;
  /**
   * <code>MODEL_DEEPSEEK_R1_DISTILL_QWEN32B = 1713;</code>
   */
  public static final int MODEL_DEEPSEEK_R1_DISTILL_QWEN32B_VALUE = 1713;
  /**
   * <code>MODEL_DEEPSEEK_R1_DISTILL_QWEN14B = 1714;</code>
   */
  public static final int MODEL_DEEPSEEK_R1_DISTILL_QWEN14B_VALUE = 1714;
  /**
   * <code>MODEL_DEEPSEEK_R1_DISTILL_LLAMA70B = 1715;</code>
   */
  public static final int MODEL_DEEPSEEK_R1_DISTILL_LLAMA70B_VALUE = 1715;
  /**
   * <pre>
   * Google (1800 - 1899)
   * </pre>
   *
   * <code>MODEL_GOOGLE_UNKNOWN = 1800;</code>
   */
  public static final int MODEL_GOOGLE_UNKNOWN_VALUE = 1800;
  /**
   * <code>MODEL_GOOGLE_GEMINI36_FLASH = 1801;</code>
   */
  public static final int MODEL_GOOGLE_GEMINI36_FLASH_VALUE = 1801;
  /**
   * <code>MODEL_GOOGLE_GEMINI35_FLASH = 1802;</code>
   */
  public static final int MODEL_GOOGLE_GEMINI35_FLASH_VALUE = 1802;
  /**
   * <code>MODEL_GOOGLE_GEMINI31_PRO = 1803;</code>
   */
  public static final int MODEL_GOOGLE_GEMINI31_PRO_VALUE = 1803;
  /**
   * <code>MODEL_GOOGLE_GEMINI31_FLASH = 1804;</code>
   */
  public static final int MODEL_GOOGLE_GEMINI31_FLASH_VALUE = 1804;
  /**
   * <code>MODEL_GOOGLE_GEMINI31_FLASH_LITE = 1805;</code>
   */
  public static final int MODEL_GOOGLE_GEMINI31_FLASH_LITE_VALUE = 1805;
  /**
   * <code>MODEL_GOOGLE_GEMINI30_PRO = 1806;</code>
   */
  public static final int MODEL_GOOGLE_GEMINI30_PRO_VALUE = 1806;
  /**
   * <code>MODEL_GOOGLE_GEMINI30_FLASH = 1807;</code>
   */
  public static final int MODEL_GOOGLE_GEMINI30_FLASH_VALUE = 1807;
  /**
   * <code>MODEL_GOOGLE_GEMINI30_FLASH_LITE = 1808;</code>
   */
  public static final int MODEL_GOOGLE_GEMINI30_FLASH_LITE_VALUE = 1808;
  /**
   * <code>MODEL_GOOGLE_GEMINI_EMBEDDING001 = 1809;</code>
   */
  public static final int MODEL_GOOGLE_GEMINI_EMBEDDING001_VALUE = 1809;
  /**
   * <code>MODEL_GOOGLE_GEMINI25_FLASH_LITE = 1810;</code>
   */
  public static final int MODEL_GOOGLE_GEMINI25_FLASH_LITE_VALUE = 1810;
  /**
   * <code>MODEL_GOOGLE_GEMINI25_FLASH = 1811;</code>
   */
  public static final int MODEL_GOOGLE_GEMINI25_FLASH_VALUE = 1811;
  /**
   * <code>MODEL_GOOGLE_GEMINI25_PRO = 1812;</code>
   */
  public static final int MODEL_GOOGLE_GEMINI25_PRO_VALUE = 1812;
  /**
   * <code>MODEL_GOOGLE_GEMMA12B = 1813;</code>
   */
  public static final int MODEL_GOOGLE_GEMMA12B_VALUE = 1813;
  /**
   * <code>MODEL_GOOGLE_GEMMA3N4B = 1814;</code>
   */
  public static final int MODEL_GOOGLE_GEMMA3N4B_VALUE = 1814;
  /**
   * <code>MODEL_GOOGLE_GEMMA31B = 1815;</code>
   */
  public static final int MODEL_GOOGLE_GEMMA31B_VALUE = 1815;
  /**
   * <code>MODEL_GOOGLE_GEMMA34B = 1816;</code>
   */
  public static final int MODEL_GOOGLE_GEMMA34B_VALUE = 1816;
  /**
   * <code>MODEL_GOOGLE_GEMMA312B = 1817;</code>
   */
  public static final int MODEL_GOOGLE_GEMMA312B_VALUE = 1817;
  /**
   * <code>MODEL_GOOGLE_GEMMA327B = 1818;</code>
   */
  public static final int MODEL_GOOGLE_GEMMA327B_VALUE = 1818;
  /**
   * <code>MODEL_GOOGLE_GEMINI20_FLASH_LITE = 1819;</code>
   */
  public static final int MODEL_GOOGLE_GEMINI20_FLASH_LITE_VALUE = 1819;
  /**
   * <code>MODEL_GOOGLE_GEMINI20_FLASH = 1820;</code>
   */
  public static final int MODEL_GOOGLE_GEMINI20_FLASH_VALUE = 1820;
  /**
   * <code>MODEL_GOOGLE_GEMMA431B = 1821;</code>
   */
  public static final int MODEL_GOOGLE_GEMMA431B_VALUE = 1821;
  /**
   * <code>MODEL_GOOGLE_GEMMA426B = 1822;</code>
   */
  public static final int MODEL_GOOGLE_GEMMA426B_VALUE = 1822;
  /**
   * <code>MODEL_GOOGLE_GEMMA44B = 1823;</code>
   */
  public static final int MODEL_GOOGLE_GEMMA44B_VALUE = 1823;
  /**
   * <code>MODEL_GOOGLE_GEMMA42B = 1824;</code>
   */
  public static final int MODEL_GOOGLE_GEMMA42B_VALUE = 1824;
  /**
   * <code>MODEL_GOOGLE_GEMMA = 1825;</code>
   */
  public static final int MODEL_GOOGLE_GEMMA_VALUE = 1825;
  /**
   * <code>MODEL_GOOGLE_GEMINI37_FLASH = 1826;</code>
   */
  public static final int MODEL_GOOGLE_GEMINI37_FLASH_VALUE = 1826;
  /**
   * <code>MODEL_GOOGLE_GEMINI38_FLASH = 1827;</code>
   */
  public static final int MODEL_GOOGLE_GEMINI38_FLASH_VALUE = 1827;
  /**
   * <pre>
   * LiquidAI (1900 - 1999)
   * </pre>
   *
   * <code>MODEL_LIQUID_AI_UNKNOWN = 1900;</code>
   */
  public static final int MODEL_LIQUID_AI_UNKNOWN_VALUE = 1900;
  /**
   * <code>MODEL_LIQUID_AI_LFM224B_A2B = 1901;</code>
   */
  public static final int MODEL_LIQUID_AI_LFM224B_A2B_VALUE = 1901;
  /**
   * <code>MODEL_LIQUID_AI_LFM28B_A1B = 1902;</code>
   */
  public static final int MODEL_LIQUID_AI_LFM28B_A1B_VALUE = 1902;
  /**
   * <code>MODEL_LIQUID_AI_LFM226B = 1903;</code>
   */
  public static final int MODEL_LIQUID_AI_LFM226B_VALUE = 1903;
  /**
   * <code>MODEL_LIQUID_AI_LFM7B = 1904;</code>
   */
  public static final int MODEL_LIQUID_AI_LFM7B_VALUE = 1904;
  /**
   * <code>MODEL_LIQUID_AI_LFM3B = 1905;</code>
   */
  public static final int MODEL_LIQUID_AI_LFM3B_VALUE = 1905;
  /**
   * <pre>
   * Meta (2000 - 2099)
   * </pre>
   *
   * <code>MODEL_META_UNKNOWN = 2000;</code>
   */
  public static final int MODEL_META_UNKNOWN_VALUE = 2000;
  /**
   * <code>MODEL_META_LLAMA_GUARD412B = 2001;</code>
   */
  public static final int MODEL_META_LLAMA_GUARD412B_VALUE = 2001;
  /**
   * <code>MODEL_META_LLAMA4_MAVERICK = 2002;</code>
   */
  public static final int MODEL_META_LLAMA4_MAVERICK_VALUE = 2002;
  /**
   * <code>MODEL_META_LLAMA4_SCOUT = 2003;</code>
   */
  public static final int MODEL_META_LLAMA4_SCOUT_VALUE = 2003;
  /**
   * <code>MODEL_META_LLAMA_GUARD38B = 2004;</code>
   */
  public static final int MODEL_META_LLAMA_GUARD38B_VALUE = 2004;
  /**
   * <code>MODEL_META_LLAMA3370B_INSTRUCT = 2005;</code>
   */
  public static final int MODEL_META_LLAMA3370B_INSTRUCT_VALUE = 2005;
  /**
   * <code>MODEL_META_LLAMA323B_INSTRUCT = 2006;</code>
   */
  public static final int MODEL_META_LLAMA323B_INSTRUCT_VALUE = 2006;
  /**
   * <code>MODEL_META_LLAMA321B_INSTRUCT = 2007;</code>
   */
  public static final int MODEL_META_LLAMA321B_INSTRUCT_VALUE = 2007;
  /**
   * <code>MODEL_META_LLAMA3290B_VISION_INSTRUCT = 2008;</code>
   */
  public static final int MODEL_META_LLAMA3290B_VISION_INSTRUCT_VALUE = 2008;
  /**
   * <code>MODEL_META_LLAMA3211B_VISION_INSTRUCT = 2009;</code>
   */
  public static final int MODEL_META_LLAMA3211B_VISION_INSTRUCT_VALUE = 2009;
  /**
   * <pre>
   * Microsoft (2100 - 2199)
   * </pre>
   *
   * <code>MODEL_MICROSOFT_UNKNOWN = 2100;</code>
   */
  public static final int MODEL_MICROSOFT_UNKNOWN_VALUE = 2100;
  /**
   * <code>MODEL_MICROSOFT_PHI4_REASONING_PLUS = 2101;</code>
   */
  public static final int MODEL_MICROSOFT_PHI4_REASONING_PLUS_VALUE = 2101;
  /**
   * <code>MODEL_MICROSOFT_PHI4_REASONING = 2102;</code>
   */
  public static final int MODEL_MICROSOFT_PHI4_REASONING_VALUE = 2102;
  /**
   * <code>MODEL_MICROSOFT_MAI_DS_R1 = 2103;</code>
   */
  public static final int MODEL_MICROSOFT_MAI_DS_R1_VALUE = 2103;
  /**
   * <code>MODEL_MICROSOFT_PHI4_MULTIMODAL_INSTRUCT = 2104;</code>
   */
  public static final int MODEL_MICROSOFT_PHI4_MULTIMODAL_INSTRUCT_VALUE = 2104;
  /**
   * <code>MODEL_MICROSOFT_PHI4 = 2105;</code>
   */
  public static final int MODEL_MICROSOFT_PHI4_VALUE = 2105;
  /**
   * <code>MODEL_MICROSOFT_PHI35_MINI128K_INSTRUCT = 2106;</code>
   */
  public static final int MODEL_MICROSOFT_PHI35_MINI128K_INSTRUCT_VALUE = 2106;
  /**
   * <pre>
   * Mistral (2200 - 2299)
   * </pre>
   *
   * <code>MODEL_MISTRAL_UNKNOWN = 2200;</code>
   */
  public static final int MODEL_MISTRAL_UNKNOWN_VALUE = 2200;
  /**
   * <code>MODEL_MISTRAL_SMALL_CREATIVE = 2201;</code>
   */
  public static final int MODEL_MISTRAL_SMALL_CREATIVE_VALUE = 2201;
  /**
   * <code>MODEL_MISTRAL_MEDIUM31 = 2202;</code>
   */
  public static final int MODEL_MISTRAL_MEDIUM31_VALUE = 2202;
  /**
   * <code>MODEL_MISTRAL_DEVSTRAL_MEDIUM = 2203;</code>
   */
  public static final int MODEL_MISTRAL_DEVSTRAL_MEDIUM_VALUE = 2203;
  /**
   * <code>MODEL_MISTRAL_DEVSTRAL_SMALL11 = 2204;</code>
   */
  public static final int MODEL_MISTRAL_DEVSTRAL_SMALL11_VALUE = 2204;
  /**
   * <code>MODEL_MISTRAL_SMALL3224B = 2205;</code>
   */
  public static final int MODEL_MISTRAL_SMALL3224B_VALUE = 2205;
  /**
   * <code>MODEL_MISTRAL_MEDIUM3 = 2206;</code>
   */
  public static final int MODEL_MISTRAL_MEDIUM3_VALUE = 2206;
  /**
   * <code>MODEL_MISTRAL_SMALL3124B = 2207;</code>
   */
  public static final int MODEL_MISTRAL_SMALL3124B_VALUE = 2207;
  /**
   * <code>MODEL_MISTRAL_SABA = 2208;</code>
   */
  public static final int MODEL_MISTRAL_SABA_VALUE = 2208;
  /**
   * <pre>
   * Nous (2300 - 2399)
   * </pre>
   *
   * <code>MODEL_NOUS_UNKNOWN = 2300;</code>
   */
  public static final int MODEL_NOUS_UNKNOWN_VALUE = 2300;
  /**
   * <code>MODEL_NOUS_HERMES470B = 2301;</code>
   */
  public static final int MODEL_NOUS_HERMES470B_VALUE = 2301;
  /**
   * <code>MODEL_NOUS_HERMES4405B = 2302;</code>
   */
  public static final int MODEL_NOUS_HERMES4405B_VALUE = 2302;
  /**
   * <code>MODEL_NOUS_HERMES370B_INSTRUCT = 2303;</code>
   */
  public static final int MODEL_NOUS_HERMES370B_INSTRUCT_VALUE = 2303;
  /**
   * <code>MODEL_NOUS_HERMES3405B_INSTRUCT = 2304;</code>
   */
  public static final int MODEL_NOUS_HERMES3405B_INSTRUCT_VALUE = 2304;
  /**
   * <pre>
   * NVIDIA (2400 - 2499)
   * </pre>
   *
   * <code>MODEL_NVIDIA_UNKNOWN = 2400;</code>
   */
  public static final int MODEL_NVIDIA_UNKNOWN_VALUE = 2400;
  /**
   * <code>MODEL_NVIDIA_NEMOTRON3_SUPER = 2401;</code>
   */
  public static final int MODEL_NVIDIA_NEMOTRON3_SUPER_VALUE = 2401;
  /**
   * <code>MODEL_NVIDIA_NEMOTRON3_NANO30B_A3B = 2402;</code>
   */
  public static final int MODEL_NVIDIA_NEMOTRON3_NANO30B_A3B_VALUE = 2402;
  /**
   * <code>MODEL_NVIDIA_NEMOTRON_NANO12B2_VL = 2403;</code>
   */
  public static final int MODEL_NVIDIA_NEMOTRON_NANO12B2_VL_VALUE = 2403;
  /**
   * <code>MODEL_NVIDIA_LLAMA33_NEMOTRON_SUPER49B_V15 = 2404;</code>
   */
  public static final int MODEL_NVIDIA_LLAMA33_NEMOTRON_SUPER49B_V15_VALUE = 2404;
  /**
   * <code>MODEL_NVIDIA_NEMOTRON_NANO9B_V2 = 2405;</code>
   */
  public static final int MODEL_NVIDIA_NEMOTRON_NANO9B_V2_VALUE = 2405;
  /**
   * <code>MODEL_NVIDIA_LLAMA31_NEMOTRON_NANO8B_V1 = 2406;</code>
   */
  public static final int MODEL_NVIDIA_LLAMA31_NEMOTRON_NANO8B_V1_VALUE = 2406;
  /**
   * <code>MODEL_NVIDIA_LLAMA33_NEMOTRON_SUPER49B_V1 = 2407;</code>
   */
  public static final int MODEL_NVIDIA_LLAMA33_NEMOTRON_SUPER49B_V1_VALUE = 2407;
  /**
   * <code>MODEL_NVIDIA_LLAMA31_NEMOTRON_ULTRA253B_V1 = 2408;</code>
   */
  public static final int MODEL_NVIDIA_LLAMA31_NEMOTRON_ULTRA253B_V1_VALUE = 2408;
  /**
   * <pre>
   * OpenAI (2500 - 2599)
   * </pre>
   *
   * <code>MODEL_OPENAI_UNKNOWN = 2500;</code>
   */
  public static final int MODEL_OPENAI_UNKNOWN_VALUE = 2500;
  /**
   * <code>MODEL_OPENAI_SORA2_PRO = 2501;</code>
   */
  public static final int MODEL_OPENAI_SORA2_PRO_VALUE = 2501;
  /**
   * <code>MODEL_OPENAI_GPT54_NANO = 2502;</code>
   */
  public static final int MODEL_OPENAI_GPT54_NANO_VALUE = 2502;
  /**
   * <code>MODEL_OPENAI_GPT54_MINI = 2503;</code>
   */
  public static final int MODEL_OPENAI_GPT54_MINI_VALUE = 2503;
  /**
   * <code>MODEL_OPENAI_GPT54_PRO = 2504;</code>
   */
  public static final int MODEL_OPENAI_GPT54_PRO_VALUE = 2504;
  /**
   * <code>MODEL_OPENAI_GPT54 = 2505;</code>
   */
  public static final int MODEL_OPENAI_GPT54_VALUE = 2505;
  /**
   * <code>MODEL_OPENAI_GPT53_CHAT = 2506;</code>
   */
  public static final int MODEL_OPENAI_GPT53_CHAT_VALUE = 2506;
  /**
   * <code>MODEL_OPENAI_GPT53_CODEX = 2507;</code>
   */
  public static final int MODEL_OPENAI_GPT53_CODEX_VALUE = 2507;
  /**
   * <code>MODEL_OPENAI_GPT_AUDIO = 2508;</code>
   */
  public static final int MODEL_OPENAI_GPT_AUDIO_VALUE = 2508;
  /**
   * <code>MODEL_OPENAI_GPT_AUDIO_MINI = 2509;</code>
   */
  public static final int MODEL_OPENAI_GPT_AUDIO_MINI_VALUE = 2509;
  /**
   * <code>MODEL_OPENAI_GPT52_CODEX = 2510;</code>
   */
  public static final int MODEL_OPENAI_GPT52_CODEX_VALUE = 2510;
  /**
   * <code>MODEL_OPENAI_GPT52_CHAT = 2511;</code>
   */
  public static final int MODEL_OPENAI_GPT52_CHAT_VALUE = 2511;
  /**
   * <code>MODEL_OPENAI_GPT52_PRO = 2512;</code>
   */
  public static final int MODEL_OPENAI_GPT52_PRO_VALUE = 2512;
  /**
   * <code>MODEL_OPENAI_GPT52 = 2513;</code>
   */
  public static final int MODEL_OPENAI_GPT52_VALUE = 2513;
  /**
   * <code>MODEL_OPENAI_GPT51_CODEX_MAX = 2514;</code>
   */
  public static final int MODEL_OPENAI_GPT51_CODEX_MAX_VALUE = 2514;
  /**
   * <code>MODEL_OPENAI_GPT51 = 2515;</code>
   */
  public static final int MODEL_OPENAI_GPT51_VALUE = 2515;
  /**
   * <code>MODEL_OPENAI_GPT51_CHAT = 2516;</code>
   */
  public static final int MODEL_OPENAI_GPT51_CHAT_VALUE = 2516;
  /**
   * <code>MODEL_OPENAI_GPT51_CODEX = 2517;</code>
   */
  public static final int MODEL_OPENAI_GPT51_CODEX_VALUE = 2517;
  /**
   * <code>MODEL_OPENAI_GPT51_CODEX_MINI = 2518;</code>
   */
  public static final int MODEL_OPENAI_GPT51_CODEX_MINI_VALUE = 2518;
  /**
   * <code>MODEL_OPENAI_TEXT_EMBEDDING_ADA002 = 2519;</code>
   */
  public static final int MODEL_OPENAI_TEXT_EMBEDDING_ADA002_VALUE = 2519;
  /**
   * <code>MODEL_OPENAI_TEXT_EMBEDDING3_LARGE = 2520;</code>
   */
  public static final int MODEL_OPENAI_TEXT_EMBEDDING3_LARGE_VALUE = 2520;
  /**
   * <code>MODEL_OPENAI_TEXT_EMBEDDING3_SMALL = 2521;</code>
   */
  public static final int MODEL_OPENAI_TEXT_EMBEDDING3_SMALL_VALUE = 2521;
  /**
   * <code>MODEL_OPENAI_GPT_OSS_SAFEGUARD20B = 2522;</code>
   */
  public static final int MODEL_OPENAI_GPT_OSS_SAFEGUARD20B_VALUE = 2522;
  /**
   * <code>MODEL_OPENAI_GPT5_IMAGE_MINI = 2523;</code>
   */
  public static final int MODEL_OPENAI_GPT5_IMAGE_MINI_VALUE = 2523;
  /**
   * <code>MODEL_OPENAI_GPT5_IMAGE = 2524;</code>
   */
  public static final int MODEL_OPENAI_GPT5_IMAGE_VALUE = 2524;
  /**
   * <code>MODEL_OPENAI_O3_DEEP_RESEARCH = 2525;</code>
   */
  public static final int MODEL_OPENAI_O3_DEEP_RESEARCH_VALUE = 2525;
  /**
   * <code>MODEL_OPENAI_O4_MINI_DEEP_RESEARCH = 2526;</code>
   */
  public static final int MODEL_OPENAI_O4_MINI_DEEP_RESEARCH_VALUE = 2526;
  /**
   * <code>MODEL_OPENAI_GPT5_PRO = 2527;</code>
   */
  public static final int MODEL_OPENAI_GPT5_PRO_VALUE = 2527;
  /**
   * <code>MODEL_OPENAI_GPT5_CODEX = 2528;</code>
   */
  public static final int MODEL_OPENAI_GPT5_CODEX_VALUE = 2528;
  /**
   * <code>MODEL_OPENAI_GPT5_CHAT = 2529;</code>
   */
  public static final int MODEL_OPENAI_GPT5_CHAT_VALUE = 2529;
  /**
   * <code>MODEL_OPENAI_GPT5 = 2530;</code>
   */
  public static final int MODEL_OPENAI_GPT5_VALUE = 2530;
  /**
   * <code>MODEL_OPENAI_GPT5_MINI = 2531;</code>
   */
  public static final int MODEL_OPENAI_GPT5_MINI_VALUE = 2531;
  /**
   * <code>MODEL_OPENAI_GPT5_NANO = 2532;</code>
   */
  public static final int MODEL_OPENAI_GPT5_NANO_VALUE = 2532;
  /**
   * <code>MODEL_OPENAI_GPT_OSS120B = 2533;</code>
   */
  public static final int MODEL_OPENAI_GPT_OSS120B_VALUE = 2533;
  /**
   * <code>MODEL_OPENAI_GPT_OSS20B = 2534;</code>
   */
  public static final int MODEL_OPENAI_GPT_OSS20B_VALUE = 2534;
  /**
   * <code>MODEL_OPENAI_O3_PRO = 2535;</code>
   */
  public static final int MODEL_OPENAI_O3_PRO_VALUE = 2535;
  /**
   * <code>MODEL_OPENAI_CODEX_MINI = 2536;</code>
   */
  public static final int MODEL_OPENAI_CODEX_MINI_VALUE = 2536;
  /**
   * <code>MODEL_OPENAI_O4_MINI_HIGH = 2537;</code>
   */
  public static final int MODEL_OPENAI_O4_MINI_HIGH_VALUE = 2537;
  /**
   * <code>MODEL_OPENAI_O3 = 2538;</code>
   */
  public static final int MODEL_OPENAI_O3_VALUE = 2538;
  /**
   * <code>MODEL_OPENAI_O4_MINI = 2539;</code>
   */
  public static final int MODEL_OPENAI_O4_MINI_VALUE = 2539;
  /**
   * <code>MODEL_OPENAI_GPT41 = 2540;</code>
   */
  public static final int MODEL_OPENAI_GPT41_VALUE = 2540;
  /**
   * <code>MODEL_OPENAI_GPT41_MINI = 2541;</code>
   */
  public static final int MODEL_OPENAI_GPT41_MINI_VALUE = 2541;
  /**
   * <code>MODEL_OPENAI_GPT41_NANO = 2542;</code>
   */
  public static final int MODEL_OPENAI_GPT41_NANO_VALUE = 2542;
  /**
   * <code>MODEL_OPENAI_O1_PRO = 2543;</code>
   */
  public static final int MODEL_OPENAI_O1_PRO_VALUE = 2543;
  /**
   * <code>MODEL_OPENAI_O3_MINI_HIGH = 2544;</code>
   */
  public static final int MODEL_OPENAI_O3_MINI_HIGH_VALUE = 2544;
  /**
   * <code>MODEL_OPENAI_O3_MINI = 2545;</code>
   */
  public static final int MODEL_OPENAI_O3_MINI_VALUE = 2545;
  /**
   * <pre>
   * Perplexity (2600 - 2699)
   * </pre>
   *
   * <code>MODEL_PERPLEXITY_UNKNOWN = 2600;</code>
   */
  public static final int MODEL_PERPLEXITY_UNKNOWN_VALUE = 2600;
  /**
   * <code>MODEL_PERPLEXITY_EMBED_V14B = 2601;</code>
   */
  public static final int MODEL_PERPLEXITY_EMBED_V14B_VALUE = 2601;
  /**
   * <code>MODEL_PERPLEXITY_EMBED_V106B = 2602;</code>
   */
  public static final int MODEL_PERPLEXITY_EMBED_V106B_VALUE = 2602;
  /**
   * <code>MODEL_PERPLEXITY_SONAR_PRO_SEARCH = 2603;</code>
   */
  public static final int MODEL_PERPLEXITY_SONAR_PRO_SEARCH_VALUE = 2603;
  /**
   * <code>MODEL_PERPLEXITY_SONAR_REASONING_PRO = 2604;</code>
   */
  public static final int MODEL_PERPLEXITY_SONAR_REASONING_PRO_VALUE = 2604;
  /**
   * <code>MODEL_PERPLEXITY_SONAR_PRO = 2605;</code>
   */
  public static final int MODEL_PERPLEXITY_SONAR_PRO_VALUE = 2605;
  /**
   * <code>MODEL_PERPLEXITY_SONAR_DEEP_RESEARCH = 2606;</code>
   */
  public static final int MODEL_PERPLEXITY_SONAR_DEEP_RESEARCH_VALUE = 2606;
  /**
   * <code>MODEL_PERPLEXITY_SONAR_REASONING = 2607;</code>
   */
  public static final int MODEL_PERPLEXITY_SONAR_REASONING_VALUE = 2607;
  /**
   * <code>MODEL_PERPLEXITY_SONAR = 2608;</code>
   */
  public static final int MODEL_PERPLEXITY_SONAR_VALUE = 2608;
  /**
   * <pre>
   * Qwen (2700 - 2799)
   * </pre>
   *
   * <code>MODEL_QWEN_UNKNOWN = 2700;</code>
   */
  public static final int MODEL_QWEN_UNKNOWN_VALUE = 2700;
  /**
   * <code>MODEL_QWEN36_PLUS = 2701;</code>
   */
  public static final int MODEL_QWEN36_PLUS_VALUE = 2701;
  /**
   * <code>MODEL_QWEN359B = 2702;</code>
   */
  public static final int MODEL_QWEN359B_VALUE = 2702;
  /**
   * <code>MODEL_QWEN3535B_A3B = 2703;</code>
   */
  public static final int MODEL_QWEN3535B_A3B_VALUE = 2703;
  /**
   * <code>MODEL_QWEN3527B = 2704;</code>
   */
  public static final int MODEL_QWEN3527B_VALUE = 2704;
  /**
   * <code>MODEL_QWEN35122B_A10B = 2705;</code>
   */
  public static final int MODEL_QWEN35122B_A10B_VALUE = 2705;
  /**
   * <code>MODEL_QWEN35_FLASH = 2706;</code>
   */
  public static final int MODEL_QWEN35_FLASH_VALUE = 2706;
  /**
   * <code>MODEL_QWEN35_PLUS20260215 = 2707;</code>
   */
  public static final int MODEL_QWEN35_PLUS20260215_VALUE = 2707;
  /**
   * <code>MODEL_QWEN35397B_A17B = 2708;</code>
   */
  public static final int MODEL_QWEN35397B_A17B_VALUE = 2708;
  /**
   * <code>MODEL_QWEN3_MAX_THINKING = 2709;</code>
   */
  public static final int MODEL_QWEN3_MAX_THINKING_VALUE = 2709;
  /**
   * <code>MODEL_QWEN3_CODER_NEXT = 2710;</code>
   */
  public static final int MODEL_QWEN3_CODER_NEXT_VALUE = 2710;
  /**
   * <code>MODEL_QWEN3_EMBEDDING06B = 2711;</code>
   */
  public static final int MODEL_QWEN3_EMBEDDING06B_VALUE = 2711;
  /**
   * <code>MODEL_QWEN3_EMBEDDING8B = 2712;</code>
   */
  public static final int MODEL_QWEN3_EMBEDDING8B_VALUE = 2712;
  /**
   * <code>MODEL_QWEN3_EMBEDDING4B = 2713;</code>
   */
  public static final int MODEL_QWEN3_EMBEDDING4B_VALUE = 2713;
  /**
   * <code>MODEL_QWEN3_VL32B_INSTRUCT = 2714;</code>
   */
  public static final int MODEL_QWEN3_VL32B_INSTRUCT_VALUE = 2714;
  /**
   * <code>MODEL_QWEN3_VL8B_THINKING = 2715;</code>
   */
  public static final int MODEL_QWEN3_VL8B_THINKING_VALUE = 2715;
  /**
   * <code>MODEL_QWEN3_VL8B_INSTRUCT = 2716;</code>
   */
  public static final int MODEL_QWEN3_VL8B_INSTRUCT_VALUE = 2716;
  /**
   * <code>MODEL_QWEN3_VL30B_A3B_THINKING = 2717;</code>
   */
  public static final int MODEL_QWEN3_VL30B_A3B_THINKING_VALUE = 2717;
  /**
   * <code>MODEL_QWEN3_VL30B_A3B_INSTRUCT = 2718;</code>
   */
  public static final int MODEL_QWEN3_VL30B_A3B_INSTRUCT_VALUE = 2718;
  /**
   * <code>MODEL_QWEN3_VL235B_A22B_THINKING = 2719;</code>
   */
  public static final int MODEL_QWEN3_VL235B_A22B_THINKING_VALUE = 2719;
  /**
   * <code>MODEL_QWEN3_VL235B_A22B_INSTRUCT = 2720;</code>
   */
  public static final int MODEL_QWEN3_VL235B_A22B_INSTRUCT_VALUE = 2720;
  /**
   * <code>MODEL_QWEN3_MAX = 2721;</code>
   */
  public static final int MODEL_QWEN3_MAX_VALUE = 2721;
  /**
   * <code>MODEL_QWEN3_CODER_PLUS = 2722;</code>
   */
  public static final int MODEL_QWEN3_CODER_PLUS_VALUE = 2722;
  /**
   * <code>MODEL_QWEN3_CODER_FLASH = 2723;</code>
   */
  public static final int MODEL_QWEN3_CODER_FLASH_VALUE = 2723;
  /**
   * <code>MODEL_QWEN3_NEXT80B_A3B_THINKING = 2724;</code>
   */
  public static final int MODEL_QWEN3_NEXT80B_A3B_THINKING_VALUE = 2724;
  /**
   * <code>MODEL_QWEN3_NEXT80B_A3B_INSTRUCT = 2725;</code>
   */
  public static final int MODEL_QWEN3_NEXT80B_A3B_INSTRUCT_VALUE = 2725;
  /**
   * <code>MODEL_QWEN3_CODER30B_A3B_INSTRUCT = 2726;</code>
   */
  public static final int MODEL_QWEN3_CODER30B_A3B_INSTRUCT_VALUE = 2726;
  /**
   * <code>MODEL_QWEN3_CODER480B_A35B = 2727;</code>
   */
  public static final int MODEL_QWEN3_CODER480B_A35B_VALUE = 2727;
  /**
   * <code>MODEL_QWEN306B = 2728;</code>
   */
  public static final int MODEL_QWEN306B_VALUE = 2728;
  /**
   * <code>MODEL_QWEN317B = 2729;</code>
   */
  public static final int MODEL_QWEN317B_VALUE = 2729;
  /**
   * <code>MODEL_QWEN34B = 2730;</code>
   */
  public static final int MODEL_QWEN34B_VALUE = 2730;
  /**
   * <code>MODEL_QWEN330B_A3B = 2731;</code>
   */
  public static final int MODEL_QWEN330B_A3B_VALUE = 2731;
  /**
   * <code>MODEL_QWEN38B = 2732;</code>
   */
  public static final int MODEL_QWEN38B_VALUE = 2732;
  /**
   * <code>MODEL_QWEN314B = 2733;</code>
   */
  public static final int MODEL_QWEN314B_VALUE = 2733;
  /**
   * <code>MODEL_QWEN332B = 2734;</code>
   */
  public static final int MODEL_QWEN332B_VALUE = 2734;
  /**
   * <code>MODEL_QWEN3235B_A22B = 2735;</code>
   */
  public static final int MODEL_QWEN3235B_A22B_VALUE = 2735;
  /**
   * <code>MODEL_QWEN25_CODER7B_INSTRUCT = 2736;</code>
   */
  public static final int MODEL_QWEN25_CODER7B_INSTRUCT_VALUE = 2736;
  /**
   * <code>MODEL_QWEN25_VL3B_INSTRUCT = 2737;</code>
   */
  public static final int MODEL_QWEN25_VL3B_INSTRUCT_VALUE = 2737;
  /**
   * <code>MODEL_QWEN25_VL32B_INSTRUCT = 2738;</code>
   */
  public static final int MODEL_QWEN25_VL32B_INSTRUCT_VALUE = 2738;
  /**
   * <code>MODEL_QWEN_QWQ32B = 2739;</code>
   */
  public static final int MODEL_QWEN_QWQ32B_VALUE = 2739;
  /**
   * <code>MODEL_QWEN2532B_INSTRUCT = 2740;</code>
   */
  public static final int MODEL_QWEN2532B_INSTRUCT_VALUE = 2740;
  /**
   * <code>MODEL_QWEN_VL_PLUS = 2741;</code>
   */
  public static final int MODEL_QWEN_VL_PLUS_VALUE = 2741;
  /**
   * <code>MODEL_QWEN_VL_MAX = 2742;</code>
   */
  public static final int MODEL_QWEN_VL_MAX_VALUE = 2742;
  /**
   * <code>MODEL_QWEN_TURBO = 2743;</code>
   */
  public static final int MODEL_QWEN_TURBO_VALUE = 2743;
  /**
   * <code>MODEL_QWEN25_VL72B_INSTRUCT = 2744;</code>
   */
  public static final int MODEL_QWEN25_VL72B_INSTRUCT_VALUE = 2744;
  /**
   * <code>MODEL_QWEN_PLUS = 2745;</code>
   */
  public static final int MODEL_QWEN_PLUS_VALUE = 2745;
  /**
   * <code>MODEL_QWEN_MAX = 2746;</code>
   */
  public static final int MODEL_QWEN_MAX_VALUE = 2746;
  /**
   * <pre>
   * TheDrummer (2800 - 2899)
   * </pre>
   *
   * <code>MODEL_THE_DRUMMER_UNKNOWN = 2800;</code>
   */
  public static final int MODEL_THE_DRUMMER_UNKNOWN_VALUE = 2800;
  /**
   * <code>MODEL_THE_DRUMMER_CYDONIA24B_V41 = 2801;</code>
   */
  public static final int MODEL_THE_DRUMMER_CYDONIA24B_V41_VALUE = 2801;
  /**
   * <code>MODEL_THE_DRUMMER_ANUBIS70B_V11 = 2802;</code>
   */
  public static final int MODEL_THE_DRUMMER_ANUBIS70B_V11_VALUE = 2802;
  /**
   * <code>MODEL_THE_DRUMMER_VALKYRIE49B_V1 = 2803;</code>
   */
  public static final int MODEL_THE_DRUMMER_VALKYRIE49B_V1_VALUE = 2803;
  /**
   * <code>MODEL_THE_DRUMMER_ANUBIS_PRO105B_V1 = 2804;</code>
   */
  public static final int MODEL_THE_DRUMMER_ANUBIS_PRO105B_V1_VALUE = 2804;
  /**
   * <code>MODEL_THE_DRUMMER_SKYFALL36B_V2 = 2805;</code>
   */
  public static final int MODEL_THE_DRUMMER_SKYFALL36B_V2_VALUE = 2805;
  /**
   * <code>MODEL_THE_DRUMMER_UNSLOPNEMO12B = 2806;</code>
   */
  public static final int MODEL_THE_DRUMMER_UNSLOPNEMO12B_VALUE = 2806;
  /**
   * <code>MODEL_THE_DRUMMER_ROCINANTE12B = 2807;</code>
   */
  public static final int MODEL_THE_DRUMMER_ROCINANTE12B_VALUE = 2807;
  /**
   * <pre>
   * THUDM (2900 - 2999)
   * </pre>
   *
   * <code>MODEL_THUDM_UNKNOWN = 2900;</code>
   */
  public static final int MODEL_THUDM_UNKNOWN_VALUE = 2900;
  /**
   * <code>MODEL_THUDM_GLM41V9B_THINKING = 2901;</code>
   */
  public static final int MODEL_THUDM_GLM41V9B_THINKING_VALUE = 2901;
  /**
   * <code>MODEL_THUDM_GLM_Z1_RUMINATION32B = 2902;</code>
   */
  public static final int MODEL_THUDM_GLM_Z1_RUMINATION32B_VALUE = 2902;
  /**
   * <code>MODEL_THUDM_GLM_Z19B = 2903;</code>
   */
  public static final int MODEL_THUDM_GLM_Z19B_VALUE = 2903;
  /**
   * <code>MODEL_THUDM_GLM49B = 2904;</code>
   */
  public static final int MODEL_THUDM_GLM49B_VALUE = 2904;
  /**
   * <code>MODEL_THUDM_GLM_Z132B = 2905;</code>
   */
  public static final int MODEL_THUDM_GLM_Z132B_VALUE = 2905;
  /**
   * <code>MODEL_THUDM_GLM432B = 2906;</code>
   */
  public static final int MODEL_THUDM_GLM432B_VALUE = 2906;
  /**
   * <pre>
   * TNG (3000 - 3099)
   * </pre>
   *
   * <code>MODEL_TNG_UNKNOWN = 3000;</code>
   */
  public static final int MODEL_TNG_UNKNOWN_VALUE = 3000;
  /**
   * <code>MODEL_TNG_DEEPSEEK_R1T2_CHIMERA = 3001;</code>
   */
  public static final int MODEL_TNG_DEEPSEEK_R1T2_CHIMERA_VALUE = 3001;
  /**
   * <code>MODEL_TNG_DEEPSEEK_R1T_CHIMERA = 3002;</code>
   */
  public static final int MODEL_TNG_DEEPSEEK_R1T_CHIMERA_VALUE = 3002;
  /**
   * <pre>
   * xAI (3100 - 3199)
   * </pre>
   *
   * <code>MODEL_XAI_UNKNOWN = 3100;</code>
   */
  public static final int MODEL_XAI_UNKNOWN_VALUE = 3100;
  /**
   * <code>MODEL_XAI_GROK4_FAST = 3101;</code>
   */
  public static final int MODEL_XAI_GROK4_FAST_VALUE = 3101;
  /**
   * <code>MODEL_XAI_GROK_CODE_FAST1 = 3102;</code>
   */
  public static final int MODEL_XAI_GROK_CODE_FAST1_VALUE = 3102;
  /**
   * <code>MODEL_XAI_GROK4 = 3103;</code>
   */
  public static final int MODEL_XAI_GROK4_VALUE = 3103;
  /**
   * <code>MODEL_XAI_GROK3_MINI = 3104;</code>
   */
  public static final int MODEL_XAI_GROK3_MINI_VALUE = 3104;
  /**
   * <code>MODEL_XAI_GROK3 = 3105;</code>
   */
  public static final int MODEL_XAI_GROK3_VALUE = 3105;
  /**
   * <code>MODEL_XAI_GROK2_MINI = 3106;</code>
   */
  public static final int MODEL_XAI_GROK2_MINI_VALUE = 3106;
  /**
   * <code>MODEL_XAI_GROK2 = 3107;</code>
   */
  public static final int MODEL_XAI_GROK2_VALUE = 3107;
  /**
   * <pre>
   * Z.AI (3200 - 3299)
   * </pre>
   *
   * <code>MODEL_ZAI_UNKNOWN = 3200;</code>
   */
  public static final int MODEL_ZAI_UNKNOWN_VALUE = 3200;
  /**
   * <code>MODEL_ZAI_GLM46 = 3201;</code>
   */
  public static final int MODEL_ZAI_GLM46_VALUE = 3201;
  /**
   * <code>MODEL_ZAI_GLM45V = 3202;</code>
   */
  public static final int MODEL_ZAI_GLM45V_VALUE = 3202;
  /**
   * <code>MODEL_ZAI_GLM45 = 3203;</code>
   */
  public static final int MODEL_ZAI_GLM45_VALUE = 3203;
  /**
   * <code>MODEL_ZAI_GLM45_AIR = 3204;</code>
   */
  public static final int MODEL_ZAI_GLM45_AIR_VALUE = 3204;
  /**
   * <code>MODEL_ZAI_GLM432B = 3205;</code>
   */
  public static final int MODEL_ZAI_GLM432B_VALUE = 3205;


  public final int getNumber() {
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Model valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Model forNumber(int value) {
    switch (value) {
      case 0: return MODEL_UNKNOWN;
      case 1000: return MODEL_ALLEN_AI_UNKNOWN;
      case 1001: return MODEL_ALLEN_AI_MOLMO28B;
      case 1002: return MODEL_ALLEN_AI_OLMO3132B_INSTRUCT;
      case 1003: return MODEL_ALLEN_AI_OLMO3132B_THINK;
      case 1004: return MODEL_ALLEN_AI_OLMO332B_THINK;
      case 1005: return MODEL_ALLEN_AI_OLMO37B_INSTRUCT;
      case 1006: return MODEL_ALLEN_AI_OLMO37B_THINK;
      case 1007: return MODEL_ALLEN_AI_OLMO2032532B_INSTRUCT;
      case 1008: return MODEL_ALLEN_AI_LLAMA31_TULU3405B;
      case 1100: return MODEL_AI21_UNKNOWN;
      case 1101: return MODEL_AI21_JAMBA_MINI17;
      case 1102: return MODEL_AI21_JAMBA_LARGE17;
      case 1103: return MODEL_AI21_JAMBA16_LARGE;
      case 1104: return MODEL_AI21_JAMBA16_MINI;
      case 1105: return MODEL_AI21_JAMBA15_MINI;
      case 1106: return MODEL_AI21_JAMBA15_LARGE;
      case 1200: return MODEL_ANTHROPIC_UNKNOWN;
      case 1201: return MODEL_ANTHROPIC_CLAUDE_OPUS47;
      case 1202: return MODEL_ANTHROPIC_CLAUDE_OPUS46_FAST;
      case 1203: return MODEL_ANTHROPIC_CLAUDE_SONNET46;
      case 1204: return MODEL_ANTHROPIC_CLAUDE_OPUS46;
      case 1205: return MODEL_ANTHROPIC_CLAUDE_OPUS45;
      case 1206: return MODEL_ANTHROPIC_CLAUDE_HAIKU45;
      case 1207: return MODEL_ANTHROPIC_CLAUDE_SONNET45;
      case 1208: return MODEL_ANTHROPIC_CLAUDE_OPUS41;
      case 1209: return MODEL_ANTHROPIC_CLAUDE_OPUS4;
      case 1210: return MODEL_ANTHROPIC_CLAUDE_SONNET4;
      case 1211: return MODEL_ANTHROPIC_CLAUDE37_SONNET;
      case 1300: return MODEL_ARCEE_AI_UNKNOWN;
      case 1301: return MODEL_ARCEE_AI_TRINITY_LARGE_THINKING;
      case 1302: return MODEL_ARCEE_AI_TRINITY_MINI;
      case 1303: return MODEL_ARCEE_AI_AFM45B;
      case 1304: return MODEL_ARCEE_AI_CALLER_LARGE;
      case 1305: return MODEL_ARCEE_AI_SPOTLIGHT;
      case 1306: return MODEL_ARCEE_AI_MAESTRO_REASONING;
      case 1307: return MODEL_ARCEE_AI_VIRTUOSO_LARGE;
      case 1308: return MODEL_ARCEE_AI_CODER_LARGE;
      case 1309: return MODEL_ARCEE_AI_VIRTUOSO_MEDIUM_V2;
      case 1310: return MODEL_ARCEE_AI_ARCEE_BLITZ;
      case 1400: return MODEL_BAIDU_UNKNOWN;
      case 1401: return MODEL_BAIDU_ERNIE4521B_A3B_THINKING;
      case 1402: return MODEL_BAIDU_ERNIE4521B_A3B;
      case 1403: return MODEL_BAIDU_ERNIE45_VL28B_A3B;
      case 1404: return MODEL_BAIDU_ERNIE45_VL424B_A47B;
      case 1405: return MODEL_BAIDU_ERNIE45300B_A47B;
      case 1500: return MODEL_BYTEDANCE_UNKNOWN;
      case 1501: return MODEL_BYTEDANCE_SEEDANCE20;
      case 1502: return MODEL_BYTEDANCE_SEEDANCE20_FAST;
      case 1503: return MODEL_BYTEDANCE_SEEDANCE15_PRO;
      case 1504: return MODEL_BYTEDANCE_SEED_OSS36B_INSTRUCT;
      case 1505: return MODEL_BYTEDANCE_UI_TARS7B;
      case 1600: return MODEL_DEEP_COGITO_UNKNOWN;
      case 1601: return MODEL_DEEP_COGITO_COGITO_V2_PREVIEW_LLAMA405B;
      case 1602: return MODEL_DEEP_COGITO_COGITO_V2_PREVIEW_LLAMA70B;
      case 1603: return MODEL_DEEP_COGITO_COGITO_V2_PREVIEW_LLAMA109B;
      case 1604: return MODEL_DEEP_COGITO_COGITO_V2_PREVIEW_DEEPSEEK671B;
      case 1700: return MODEL_DEEPSEEK_UNKNOWN;
      case 1701: return MODEL_DEEPSEEK_V32_SPECIALE;
      case 1702: return MODEL_DEEPSEEK_V32;
      case 1703: return MODEL_DEEPSEEK_V31_TERMINUS;
      case 1704: return MODEL_DEEPSEEK_V31;
      case 1705: return MODEL_DEEPSEEK_V31_BASE;
      case 1706: return MODEL_DEEPSEEK_R1_DISTILL_QWEN7B;
      case 1707: return MODEL_DEEPSEEK_R10528_QWEN38B;
      case 1708: return MODEL_DEEPSEEK_PROVER_V2;
      case 1709: return MODEL_DEEPSEEK_V3_BASE;
      case 1710: return MODEL_DEEPSEEK_R1_ZERO;
      case 1711: return MODEL_DEEPSEEK_R1_DISTILL_LLAMA8B;
      case 1712: return MODEL_DEEPSEEK_R1_DISTILL_QWEN15B;
      case 1713: return MODEL_DEEPSEEK_R1_DISTILL_QWEN32B;
      case 1714: return MODEL_DEEPSEEK_R1_DISTILL_QWEN14B;
      case 1715: return MODEL_DEEPSEEK_R1_DISTILL_LLAMA70B;
      case 1800: return MODEL_GOOGLE_UNKNOWN;
      case 1801: return MODEL_GOOGLE_GEMINI36_FLASH;
      case 1802: return MODEL_GOOGLE_GEMINI35_FLASH;
      case 1803: return MODEL_GOOGLE_GEMINI31_PRO;
      case 1804: return MODEL_GOOGLE_GEMINI31_FLASH;
      case 1805: return MODEL_GOOGLE_GEMINI31_FLASH_LITE;
      case 1806: return MODEL_GOOGLE_GEMINI30_PRO;
      case 1807: return MODEL_GOOGLE_GEMINI30_FLASH;
      case 1808: return MODEL_GOOGLE_GEMINI30_FLASH_LITE;
      case 1809: return MODEL_GOOGLE_GEMINI_EMBEDDING001;
      case 1810: return MODEL_GOOGLE_GEMINI25_FLASH_LITE;
      case 1811: return MODEL_GOOGLE_GEMINI25_FLASH;
      case 1812: return MODEL_GOOGLE_GEMINI25_PRO;
      case 1813: return MODEL_GOOGLE_GEMMA12B;
      case 1814: return MODEL_GOOGLE_GEMMA3N4B;
      case 1815: return MODEL_GOOGLE_GEMMA31B;
      case 1816: return MODEL_GOOGLE_GEMMA34B;
      case 1817: return MODEL_GOOGLE_GEMMA312B;
      case 1818: return MODEL_GOOGLE_GEMMA327B;
      case 1819: return MODEL_GOOGLE_GEMINI20_FLASH_LITE;
      case 1820: return MODEL_GOOGLE_GEMINI20_FLASH;
      case 1821: return MODEL_GOOGLE_GEMMA431B;
      case 1822: return MODEL_GOOGLE_GEMMA426B;
      case 1823: return MODEL_GOOGLE_GEMMA44B;
      case 1824: return MODEL_GOOGLE_GEMMA42B;
      case 1825: return MODEL_GOOGLE_GEMMA;
      case 1826: return MODEL_GOOGLE_GEMINI37_FLASH;
      case 1827: return MODEL_GOOGLE_GEMINI38_FLASH;
      case 1900: return MODEL_LIQUID_AI_UNKNOWN;
      case 1901: return MODEL_LIQUID_AI_LFM224B_A2B;
      case 1902: return MODEL_LIQUID_AI_LFM28B_A1B;
      case 1903: return MODEL_LIQUID_AI_LFM226B;
      case 1904: return MODEL_LIQUID_AI_LFM7B;
      case 1905: return MODEL_LIQUID_AI_LFM3B;
      case 2000: return MODEL_META_UNKNOWN;
      case 2001: return MODEL_META_LLAMA_GUARD412B;
      case 2002: return MODEL_META_LLAMA4_MAVERICK;
      case 2003: return MODEL_META_LLAMA4_SCOUT;
      case 2004: return MODEL_META_LLAMA_GUARD38B;
      case 2005: return MODEL_META_LLAMA3370B_INSTRUCT;
      case 2006: return MODEL_META_LLAMA323B_INSTRUCT;
      case 2007: return MODEL_META_LLAMA321B_INSTRUCT;
      case 2008: return MODEL_META_LLAMA3290B_VISION_INSTRUCT;
      case 2009: return MODEL_META_LLAMA3211B_VISION_INSTRUCT;
      case 2100: return MODEL_MICROSOFT_UNKNOWN;
      case 2101: return MODEL_MICROSOFT_PHI4_REASONING_PLUS;
      case 2102: return MODEL_MICROSOFT_PHI4_REASONING;
      case 2103: return MODEL_MICROSOFT_MAI_DS_R1;
      case 2104: return MODEL_MICROSOFT_PHI4_MULTIMODAL_INSTRUCT;
      case 2105: return MODEL_MICROSOFT_PHI4;
      case 2106: return MODEL_MICROSOFT_PHI35_MINI128K_INSTRUCT;
      case 2200: return MODEL_MISTRAL_UNKNOWN;
      case 2201: return MODEL_MISTRAL_SMALL_CREATIVE;
      case 2202: return MODEL_MISTRAL_MEDIUM31;
      case 2203: return MODEL_MISTRAL_DEVSTRAL_MEDIUM;
      case 2204: return MODEL_MISTRAL_DEVSTRAL_SMALL11;
      case 2205: return MODEL_MISTRAL_SMALL3224B;
      case 2206: return MODEL_MISTRAL_MEDIUM3;
      case 2207: return MODEL_MISTRAL_SMALL3124B;
      case 2208: return MODEL_MISTRAL_SABA;
      case 2300: return MODEL_NOUS_UNKNOWN;
      case 2301: return MODEL_NOUS_HERMES470B;
      case 2302: return MODEL_NOUS_HERMES4405B;
      case 2303: return MODEL_NOUS_HERMES370B_INSTRUCT;
      case 2304: return MODEL_NOUS_HERMES3405B_INSTRUCT;
      case 2400: return MODEL_NVIDIA_UNKNOWN;
      case 2401: return MODEL_NVIDIA_NEMOTRON3_SUPER;
      case 2402: return MODEL_NVIDIA_NEMOTRON3_NANO30B_A3B;
      case 2403: return MODEL_NVIDIA_NEMOTRON_NANO12B2_VL;
      case 2404: return MODEL_NVIDIA_LLAMA33_NEMOTRON_SUPER49B_V15;
      case 2405: return MODEL_NVIDIA_NEMOTRON_NANO9B_V2;
      case 2406: return MODEL_NVIDIA_LLAMA31_NEMOTRON_NANO8B_V1;
      case 2407: return MODEL_NVIDIA_LLAMA33_NEMOTRON_SUPER49B_V1;
      case 2408: return MODEL_NVIDIA_LLAMA31_NEMOTRON_ULTRA253B_V1;
      case 2500: return MODEL_OPENAI_UNKNOWN;
      case 2501: return MODEL_OPENAI_SORA2_PRO;
      case 2502: return MODEL_OPENAI_GPT54_NANO;
      case 2503: return MODEL_OPENAI_GPT54_MINI;
      case 2504: return MODEL_OPENAI_GPT54_PRO;
      case 2505: return MODEL_OPENAI_GPT54;
      case 2506: return MODEL_OPENAI_GPT53_CHAT;
      case 2507: return MODEL_OPENAI_GPT53_CODEX;
      case 2508: return MODEL_OPENAI_GPT_AUDIO;
      case 2509: return MODEL_OPENAI_GPT_AUDIO_MINI;
      case 2510: return MODEL_OPENAI_GPT52_CODEX;
      case 2511: return MODEL_OPENAI_GPT52_CHAT;
      case 2512: return MODEL_OPENAI_GPT52_PRO;
      case 2513: return MODEL_OPENAI_GPT52;
      case 2514: return MODEL_OPENAI_GPT51_CODEX_MAX;
      case 2515: return MODEL_OPENAI_GPT51;
      case 2516: return MODEL_OPENAI_GPT51_CHAT;
      case 2517: return MODEL_OPENAI_GPT51_CODEX;
      case 2518: return MODEL_OPENAI_GPT51_CODEX_MINI;
      case 2519: return MODEL_OPENAI_TEXT_EMBEDDING_ADA002;
      case 2520: return MODEL_OPENAI_TEXT_EMBEDDING3_LARGE;
      case 2521: return MODEL_OPENAI_TEXT_EMBEDDING3_SMALL;
      case 2522: return MODEL_OPENAI_GPT_OSS_SAFEGUARD20B;
      case 2523: return MODEL_OPENAI_GPT5_IMAGE_MINI;
      case 2524: return MODEL_OPENAI_GPT5_IMAGE;
      case 2525: return MODEL_OPENAI_O3_DEEP_RESEARCH;
      case 2526: return MODEL_OPENAI_O4_MINI_DEEP_RESEARCH;
      case 2527: return MODEL_OPENAI_GPT5_PRO;
      case 2528: return MODEL_OPENAI_GPT5_CODEX;
      case 2529: return MODEL_OPENAI_GPT5_CHAT;
      case 2530: return MODEL_OPENAI_GPT5;
      case 2531: return MODEL_OPENAI_GPT5_MINI;
      case 2532: return MODEL_OPENAI_GPT5_NANO;
      case 2533: return MODEL_OPENAI_GPT_OSS120B;
      case 2534: return MODEL_OPENAI_GPT_OSS20B;
      case 2535: return MODEL_OPENAI_O3_PRO;
      case 2536: return MODEL_OPENAI_CODEX_MINI;
      case 2537: return MODEL_OPENAI_O4_MINI_HIGH;
      case 2538: return MODEL_OPENAI_O3;
      case 2539: return MODEL_OPENAI_O4_MINI;
      case 2540: return MODEL_OPENAI_GPT41;
      case 2541: return MODEL_OPENAI_GPT41_MINI;
      case 2542: return MODEL_OPENAI_GPT41_NANO;
      case 2543: return MODEL_OPENAI_O1_PRO;
      case 2544: return MODEL_OPENAI_O3_MINI_HIGH;
      case 2545: return MODEL_OPENAI_O3_MINI;
      case 2600: return MODEL_PERPLEXITY_UNKNOWN;
      case 2601: return MODEL_PERPLEXITY_EMBED_V14B;
      case 2602: return MODEL_PERPLEXITY_EMBED_V106B;
      case 2603: return MODEL_PERPLEXITY_SONAR_PRO_SEARCH;
      case 2604: return MODEL_PERPLEXITY_SONAR_REASONING_PRO;
      case 2605: return MODEL_PERPLEXITY_SONAR_PRO;
      case 2606: return MODEL_PERPLEXITY_SONAR_DEEP_RESEARCH;
      case 2607: return MODEL_PERPLEXITY_SONAR_REASONING;
      case 2608: return MODEL_PERPLEXITY_SONAR;
      case 2700: return MODEL_QWEN_UNKNOWN;
      case 2701: return MODEL_QWEN36_PLUS;
      case 2702: return MODEL_QWEN359B;
      case 2703: return MODEL_QWEN3535B_A3B;
      case 2704: return MODEL_QWEN3527B;
      case 2705: return MODEL_QWEN35122B_A10B;
      case 2706: return MODEL_QWEN35_FLASH;
      case 2707: return MODEL_QWEN35_PLUS20260215;
      case 2708: return MODEL_QWEN35397B_A17B;
      case 2709: return MODEL_QWEN3_MAX_THINKING;
      case 2710: return MODEL_QWEN3_CODER_NEXT;
      case 2711: return MODEL_QWEN3_EMBEDDING06B;
      case 2712: return MODEL_QWEN3_EMBEDDING8B;
      case 2713: return MODEL_QWEN3_EMBEDDING4B;
      case 2714: return MODEL_QWEN3_VL32B_INSTRUCT;
      case 2715: return MODEL_QWEN3_VL8B_THINKING;
      case 2716: return MODEL_QWEN3_VL8B_INSTRUCT;
      case 2717: return MODEL_QWEN3_VL30B_A3B_THINKING;
      case 2718: return MODEL_QWEN3_VL30B_A3B_INSTRUCT;
      case 2719: return MODEL_QWEN3_VL235B_A22B_THINKING;
      case 2720: return MODEL_QWEN3_VL235B_A22B_INSTRUCT;
      case 2721: return MODEL_QWEN3_MAX;
      case 2722: return MODEL_QWEN3_CODER_PLUS;
      case 2723: return MODEL_QWEN3_CODER_FLASH;
      case 2724: return MODEL_QWEN3_NEXT80B_A3B_THINKING;
      case 2725: return MODEL_QWEN3_NEXT80B_A3B_INSTRUCT;
      case 2726: return MODEL_QWEN3_CODER30B_A3B_INSTRUCT;
      case 2727: return MODEL_QWEN3_CODER480B_A35B;
      case 2728: return MODEL_QWEN306B;
      case 2729: return MODEL_QWEN317B;
      case 2730: return MODEL_QWEN34B;
      case 2731: return MODEL_QWEN330B_A3B;
      case 2732: return MODEL_QWEN38B;
      case 2733: return MODEL_QWEN314B;
      case 2734: return MODEL_QWEN332B;
      case 2735: return MODEL_QWEN3235B_A22B;
      case 2736: return MODEL_QWEN25_CODER7B_INSTRUCT;
      case 2737: return MODEL_QWEN25_VL3B_INSTRUCT;
      case 2738: return MODEL_QWEN25_VL32B_INSTRUCT;
      case 2739: return MODEL_QWEN_QWQ32B;
      case 2740: return MODEL_QWEN2532B_INSTRUCT;
      case 2741: return MODEL_QWEN_VL_PLUS;
      case 2742: return MODEL_QWEN_VL_MAX;
      case 2743: return MODEL_QWEN_TURBO;
      case 2744: return MODEL_QWEN25_VL72B_INSTRUCT;
      case 2745: return MODEL_QWEN_PLUS;
      case 2746: return MODEL_QWEN_MAX;
      case 2800: return MODEL_THE_DRUMMER_UNKNOWN;
      case 2801: return MODEL_THE_DRUMMER_CYDONIA24B_V41;
      case 2802: return MODEL_THE_DRUMMER_ANUBIS70B_V11;
      case 2803: return MODEL_THE_DRUMMER_VALKYRIE49B_V1;
      case 2804: return MODEL_THE_DRUMMER_ANUBIS_PRO105B_V1;
      case 2805: return MODEL_THE_DRUMMER_SKYFALL36B_V2;
      case 2806: return MODEL_THE_DRUMMER_UNSLOPNEMO12B;
      case 2807: return MODEL_THE_DRUMMER_ROCINANTE12B;
      case 2900: return MODEL_THUDM_UNKNOWN;
      case 2901: return MODEL_THUDM_GLM41V9B_THINKING;
      case 2902: return MODEL_THUDM_GLM_Z1_RUMINATION32B;
      case 2903: return MODEL_THUDM_GLM_Z19B;
      case 2904: return MODEL_THUDM_GLM49B;
      case 2905: return MODEL_THUDM_GLM_Z132B;
      case 2906: return MODEL_THUDM_GLM432B;
      case 3000: return MODEL_TNG_UNKNOWN;
      case 3001: return MODEL_TNG_DEEPSEEK_R1T2_CHIMERA;
      case 3002: return MODEL_TNG_DEEPSEEK_R1T_CHIMERA;
      case 3100: return MODEL_XAI_UNKNOWN;
      case 3101: return MODEL_XAI_GROK4_FAST;
      case 3102: return MODEL_XAI_GROK_CODE_FAST1;
      case 3103: return MODEL_XAI_GROK4;
      case 3104: return MODEL_XAI_GROK3_MINI;
      case 3105: return MODEL_XAI_GROK3;
      case 3106: return MODEL_XAI_GROK2_MINI;
      case 3107: return MODEL_XAI_GROK2;
      case 3200: return MODEL_ZAI_UNKNOWN;
      case 3201: return MODEL_ZAI_GLM46;
      case 3202: return MODEL_ZAI_GLM45V;
      case 3203: return MODEL_ZAI_GLM45;
      case 3204: return MODEL_ZAI_GLM45_AIR;
      case 3205: return MODEL_ZAI_GLM432B;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Model>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Model> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Model>() {
          public Model findValueByNumber(int number) {
            return Model.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.google.wireless.android.sdk.stats.ModelRegistryProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final Model[] VALUES = values();

  public static Model valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Model(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:android_studio.Model)
}

