// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

// Protobuf Java Version: 3.25.5
package com.google.wireless.android.sdk.stats;

public interface OptInToMetricsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:android_studio.OptInToMetrics)
    com.google.protobuf.MessageOrBuilder {
}
