// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

// Protobuf Java Version: 3.25.5
package com.google.wireless.android.sdk.stats;

public interface ResolveComposeTracingCodeLocationMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:android_studio.ResolveComposeTracingCodeLocationMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Number of source-code locations resolved for the query
   * </pre>
   *
   * <code>optional int32 result_count = 1;</code>
   * @return Whether the resultCount field is set.
   */
  boolean hasResultCount();
  /**
   * <pre>
   * Number of source-code locations resolved for the query
   * </pre>
   *
   * <code>optional int32 result_count = 1;</code>
   * @return The resultCount.
   */
  int getResultCount();
}
