// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface SkillsEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:android_studio.SkillsEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Common metadata for all skills events.
   * </pre>
   *
   * <code>optional .android_studio.SmlResponseMetadata metadata = 1 [lazy = true];</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <pre>
   * Common metadata for all skills events.
   * </pre>
   *
   * <code>optional .android_studio.SmlResponseMetadata metadata = 1 [lazy = true];</code>
   * @return The metadata.
   */
  com.google.wireless.android.sdk.stats.SmlResponseMetadata getMetadata();
  /**
   * <pre>
   * Common metadata for all skills events.
   * </pre>
   *
   * <code>optional .android_studio.SmlResponseMetadata metadata = 1 [lazy = true];</code>
   */
  com.google.wireless.android.sdk.stats.SmlResponseMetadataOrBuilder getMetadataOrBuilder();

  /**
   * <code>.android_studio.SkillsEvent.Activation activation = 2 [lazy = true];</code>
   * @return Whether the activation field is set.
   */
  boolean hasActivation();
  /**
   * <code>.android_studio.SkillsEvent.Activation activation = 2 [lazy = true];</code>
   * @return The activation.
   */
  com.google.wireless.android.sdk.stats.SkillsEvent.Activation getActivation();
  /**
   * <code>.android_studio.SkillsEvent.Activation activation = 2 [lazy = true];</code>
   */
  com.google.wireless.android.sdk.stats.SkillsEvent.ActivationOrBuilder getActivationOrBuilder();

  /**
   * <code>.android_studio.SkillsEvent.Discovery discovery = 3 [lazy = true];</code>
   * @return Whether the discovery field is set.
   */
  boolean hasDiscovery();
  /**
   * <code>.android_studio.SkillsEvent.Discovery discovery = 3 [lazy = true];</code>
   * @return The discovery.
   */
  com.google.wireless.android.sdk.stats.SkillsEvent.Discovery getDiscovery();
  /**
   * <code>.android_studio.SkillsEvent.Discovery discovery = 3 [lazy = true];</code>
   */
  com.google.wireless.android.sdk.stats.SkillsEvent.DiscoveryOrBuilder getDiscoveryOrBuilder();

  /**
   * <code>.android_studio.SkillsEvent.UserAction user_action = 4 [lazy = true];</code>
   * @return Whether the userAction field is set.
   */
  boolean hasUserAction();
  /**
   * <code>.android_studio.SkillsEvent.UserAction user_action = 4 [lazy = true];</code>
   * @return The userAction.
   */
  com.google.wireless.android.sdk.stats.SkillsEvent.UserAction getUserAction();
  /**
   * <code>.android_studio.SkillsEvent.UserAction user_action = 4 [lazy = true];</code>
   */
  com.google.wireless.android.sdk.stats.SkillsEvent.UserActionOrBuilder getUserActionOrBuilder();

  com.google.wireless.android.sdk.stats.SkillsEvent.EventCase getEventCase();
}
