// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats_logged_in.proto

package com.google.wireless.android.sdk.stats;

public interface SmlChatBotEventLoggedInOrBuilder extends
    // @@protoc_insertion_point(interface_extends:android_studio.SmlChatBotEventLoggedIn)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.android_studio.SmlChatBotEventLoggedIn.BotResponse response = 1 [lazy = true];</code>
   * @return Whether the response field is set.
   */
  boolean hasResponse();
  /**
   * <code>.android_studio.SmlChatBotEventLoggedIn.BotResponse response = 1 [lazy = true];</code>
   * @return The response.
   */
  com.google.wireless.android.sdk.stats.SmlChatBotEventLoggedIn.BotResponse getResponse();
  /**
   * <code>.android_studio.SmlChatBotEventLoggedIn.BotResponse response = 1 [lazy = true];</code>
   */
  com.google.wireless.android.sdk.stats.SmlChatBotEventLoggedIn.BotResponseOrBuilder getResponseOrBuilder();

  /**
   * <code>.android_studio.SmlChatBotEventLoggedIn.ActionInvoked action_invoked = 3 [lazy = true];</code>
   * @return Whether the actionInvoked field is set.
   */
  boolean hasActionInvoked();
  /**
   * <code>.android_studio.SmlChatBotEventLoggedIn.ActionInvoked action_invoked = 3 [lazy = true];</code>
   * @return The actionInvoked.
   */
  com.google.wireless.android.sdk.stats.SmlChatBotEventLoggedIn.ActionInvoked getActionInvoked();
  /**
   * <code>.android_studio.SmlChatBotEventLoggedIn.ActionInvoked action_invoked = 3 [lazy = true];</code>
   */
  com.google.wireless.android.sdk.stats.SmlChatBotEventLoggedIn.ActionInvokedOrBuilder getActionInvokedOrBuilder();

  /**
   * <code>.android_studio.SmlChatBotEventLoggedIn.QueryBoxEvent query_box_event = 10 [lazy = true];</code>
   * @return Whether the queryBoxEvent field is set.
   */
  boolean hasQueryBoxEvent();
  /**
   * <code>.android_studio.SmlChatBotEventLoggedIn.QueryBoxEvent query_box_event = 10 [lazy = true];</code>
   * @return The queryBoxEvent.
   */
  com.google.wireless.android.sdk.stats.SmlChatBotEventLoggedIn.QueryBoxEvent getQueryBoxEvent();
  /**
   * <code>.android_studio.SmlChatBotEventLoggedIn.QueryBoxEvent query_box_event = 10 [lazy = true];</code>
   */
  com.google.wireless.android.sdk.stats.SmlChatBotEventLoggedIn.QueryBoxEventOrBuilder getQueryBoxEventOrBuilder();

  /**
   * <code>.android_studio.SmlChatBotEventLoggedIn.ContextDrawerEvent context_drawer_event = 11 [lazy = true];</code>
   * @return Whether the contextDrawerEvent field is set.
   */
  boolean hasContextDrawerEvent();
  /**
   * <code>.android_studio.SmlChatBotEventLoggedIn.ContextDrawerEvent context_drawer_event = 11 [lazy = true];</code>
   * @return The contextDrawerEvent.
   */
  com.google.wireless.android.sdk.stats.SmlChatBotEventLoggedIn.ContextDrawerEvent getContextDrawerEvent();
  /**
   * <code>.android_studio.SmlChatBotEventLoggedIn.ContextDrawerEvent context_drawer_event = 11 [lazy = true];</code>
   */
  com.google.wireless.android.sdk.stats.SmlChatBotEventLoggedIn.ContextDrawerEventOrBuilder getContextDrawerEventOrBuilder();

  com.google.wireless.android.sdk.stats.SmlChatBotEventLoggedIn.ContentCase getContentCase();
}
