// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: analytics_settings.proto

package com.android.tools.analytics.proto;

public final class AnalyticsSettingsProto {
  private AnalyticsSettingsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AnalyticsSettingsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:android.analytics.AnalyticsSettings)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Pseudo-anonymous identifier for the developer environment (UUID v4)
     * </pre>
     *
     * <code>string user_id = 1 [json_name = "userId"];</code>
     * @return The userId.
     */
    java.lang.String getUserId();
    /**
     * <pre>
     * Pseudo-anonymous identifier for the developer environment (UUID v4)
     * </pre>
     *
     * <code>string user_id = 1 [json_name = "userId"];</code>
     * @return The bytes for userId.
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <pre>
     * Whether the user has opted in to telemetry collection
     * </pre>
     *
     * <code>bool opted_in = 2 [json_name = "hasOptedIn"];</code>
     * @return The optedIn.
     */
    boolean getOptedIn();

    /**
     * <pre>
     * Debug flag to disable publishing metrics to Google servers
     * </pre>
     *
     * <code>bool debug_disable_publishing = 3 [json_name = "debugDisablePublishing"];</code>
     * @return The debugDisablePublishing.
     */
    boolean getDebugDisablePublishing();

    /**
     * <pre>
     * 192-bit cryptographic salt serialized as a signed decimal string
     * </pre>
     *
     * <code>string salt_value = 4 [json_name = "saltValue"];</code>
     * @return The saltValue.
     */
    java.lang.String getSaltValue();
    /**
     * <pre>
     * 192-bit cryptographic salt serialized as a signed decimal string
     * </pre>
     *
     * <code>string salt_value = 4 [json_name = "saltValue"];</code>
     * @return The bytes for saltValue.
     */
    com.google.protobuf.ByteString
        getSaltValueBytes();

    /**
     * <pre>
     * Rotation epoch index tracking 28-day intervals since 1970-01-01
     * </pre>
     *
     * <code>int32 salt_skew = 5 [json_name = "saltSkew"];</code>
     * @return The saltSkew.
     */
    int getSaltSkew();

    /**
     * <pre>
     * Date of the last user sentiment prompt (formatted as string)
     * </pre>
     *
     * <code>string last_sentiment_question_date = 6 [json_name = "lastSentimentQuestionDate"];</code>
     * @return The lastSentimentQuestionDate.
     */
    java.lang.String getLastSentimentQuestionDate();
    /**
     * <pre>
     * Date of the last user sentiment prompt (formatted as string)
     * </pre>
     *
     * <code>string last_sentiment_question_date = 6 [json_name = "lastSentimentQuestionDate"];</code>
     * @return The bytes for lastSentimentQuestionDate.
     */
    com.google.protobuf.ByteString
        getLastSentimentQuestionDateBytes();

    /**
     * <pre>
     * Date of the last user sentiment answer (formatted as string)
     * </pre>
     *
     * <code>string last_sentiment_answer_date = 7 [json_name = "lastSentimentAnswerDate"];</code>
     * @return The lastSentimentAnswerDate.
     */
    java.lang.String getLastSentimentAnswerDate();
    /**
     * <pre>
     * Date of the last user sentiment answer (formatted as string)
     * </pre>
     *
     * <code>string last_sentiment_answer_date = 7 [json_name = "lastSentimentAnswerDate"];</code>
     * @return The bytes for lastSentimentAnswerDate.
     */
    com.google.protobuf.ByteString
        getLastSentimentAnswerDateBytes();

    /**
     * <pre>
     * Date of the next scheduled general feature survey (formatted as string)
     * </pre>
     *
     * <code>string last_feature_survey_date = 8 [json_name = "lastFeatureSurveyDate"];</code>
     * @return The lastFeatureSurveyDate.
     */
    java.lang.String getLastFeatureSurveyDate();
    /**
     * <pre>
     * Date of the next scheduled general feature survey (formatted as string)
     * </pre>
     *
     * <code>string last_feature_survey_date = 8 [json_name = "lastFeatureSurveyDate"];</code>
     * @return The bytes for lastFeatureSurveyDate.
     */
    com.google.protobuf.ByteString
        getLastFeatureSurveyDateBytes();

    /**
     * <pre>
     * Per-feature survey schedule map (feature_name -&gt; next survey date string)
     * </pre>
     *
     * <code>map&lt;string, string&gt; last_feature_survey_date_map = 9 [json_name = "lastFeatureSurveyDateMap"];</code>
     */
    int getLastFeatureSurveyDateMapCount();
    /**
     * <pre>
     * Per-feature survey schedule map (feature_name -&gt; next survey date string)
     * </pre>
     *
     * <code>map&lt;string, string&gt; last_feature_survey_date_map = 9 [json_name = "lastFeatureSurveyDateMap"];</code>
     */
    boolean containsLastFeatureSurveyDateMap(
        java.lang.String key);
    /**
     * Use {@link #getLastFeatureSurveyDateMapMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getLastFeatureSurveyDateMap();
    /**
     * <pre>
     * Per-feature survey schedule map (feature_name -&gt; next survey date string)
     * </pre>
     *
     * <code>map&lt;string, string&gt; last_feature_survey_date_map = 9 [json_name = "lastFeatureSurveyDateMap"];</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getLastFeatureSurveyDateMapMap();
    /**
     * <pre>
     * Per-feature survey schedule map (feature_name -&gt; next survey date string)
     * </pre>
     *
     * <code>map&lt;string, string&gt; last_feature_survey_date_map = 9 [json_name = "lastFeatureSurveyDateMap"];</code>
     */
    /* nullable */
java.lang.String getLastFeatureSurveyDateMapOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <pre>
     * Per-feature survey schedule map (feature_name -&gt; next survey date string)
     * </pre>
     *
     * <code>map&lt;string, string&gt; last_feature_survey_date_map = 9 [json_name = "lastFeatureSurveyDateMap"];</code>
     */
    java.lang.String getLastFeatureSurveyDateMapOrThrow(
        java.lang.String key);

    /**
     * <pre>
     * Major/minor version of Android Studio when opt-in was last prompted (e.g. "2024.1")
     * </pre>
     *
     * <code>string last_optin_prompt_version = 10 [json_name = "lastOptinPromptVersion"];</code>
     * @return The lastOptinPromptVersion.
     */
    java.lang.String getLastOptinPromptVersion();
    /**
     * <pre>
     * Major/minor version of Android Studio when opt-in was last prompted (e.g. "2024.1")
     * </pre>
     *
     * <code>string last_optin_prompt_version = 10 [json_name = "lastOptinPromptVersion"];</code>
     * @return The bytes for lastOptinPromptVersion.
     */
    com.google.protobuf.ByteString
        getLastOptinPromptVersionBytes();
  }
  /**
   * <pre>
   * Represents the schema for ~/.android/analytics.settings serialized as JSON.
   * </pre>
   *
   * Protobuf type {@code android.analytics.AnalyticsSettings}
   */
  public static final class AnalyticsSettings extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:android.analytics.AnalyticsSettings)
      AnalyticsSettingsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AnalyticsSettings.newBuilder() to construct.
    private AnalyticsSettings(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AnalyticsSettings() {
      userId_ = "";
      saltValue_ = "";
      lastSentimentQuestionDate_ = "";
      lastSentimentAnswerDate_ = "";
      lastFeatureSurveyDate_ = "";
      lastOptinPromptVersion_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AnalyticsSettings();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.android.tools.analytics.proto.AnalyticsSettingsProto.internal_static_android_analytics_AnalyticsSettings_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 9:
          return internalGetLastFeatureSurveyDateMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.android.tools.analytics.proto.AnalyticsSettingsProto.internal_static_android_analytics_AnalyticsSettings_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings.class, com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings.Builder.class);
    }

    public static final int USER_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object userId_ = "";
    /**
     * <pre>
     * Pseudo-anonymous identifier for the developer environment (UUID v4)
     * </pre>
     *
     * <code>string user_id = 1 [json_name = "userId"];</code>
     * @return The userId.
     */
    @java.lang.Override
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Pseudo-anonymous identifier for the developer environment (UUID v4)
     * </pre>
     *
     * <code>string user_id = 1 [json_name = "userId"];</code>
     * @return The bytes for userId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPTED_IN_FIELD_NUMBER = 2;
    private boolean optedIn_ = false;
    /**
     * <pre>
     * Whether the user has opted in to telemetry collection
     * </pre>
     *
     * <code>bool opted_in = 2 [json_name = "hasOptedIn"];</code>
     * @return The optedIn.
     */
    @java.lang.Override
    public boolean getOptedIn() {
      return optedIn_;
    }

    public static final int DEBUG_DISABLE_PUBLISHING_FIELD_NUMBER = 3;
    private boolean debugDisablePublishing_ = false;
    /**
     * <pre>
     * Debug flag to disable publishing metrics to Google servers
     * </pre>
     *
     * <code>bool debug_disable_publishing = 3 [json_name = "debugDisablePublishing"];</code>
     * @return The debugDisablePublishing.
     */
    @java.lang.Override
    public boolean getDebugDisablePublishing() {
      return debugDisablePublishing_;
    }

    public static final int SALT_VALUE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object saltValue_ = "";
    /**
     * <pre>
     * 192-bit cryptographic salt serialized as a signed decimal string
     * </pre>
     *
     * <code>string salt_value = 4 [json_name = "saltValue"];</code>
     * @return The saltValue.
     */
    @java.lang.Override
    public java.lang.String getSaltValue() {
      java.lang.Object ref = saltValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        saltValue_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 192-bit cryptographic salt serialized as a signed decimal string
     * </pre>
     *
     * <code>string salt_value = 4 [json_name = "saltValue"];</code>
     * @return The bytes for saltValue.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSaltValueBytes() {
      java.lang.Object ref = saltValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        saltValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SALT_SKEW_FIELD_NUMBER = 5;
    private int saltSkew_ = 0;
    /**
     * <pre>
     * Rotation epoch index tracking 28-day intervals since 1970-01-01
     * </pre>
     *
     * <code>int32 salt_skew = 5 [json_name = "saltSkew"];</code>
     * @return The saltSkew.
     */
    @java.lang.Override
    public int getSaltSkew() {
      return saltSkew_;
    }

    public static final int LAST_SENTIMENT_QUESTION_DATE_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object lastSentimentQuestionDate_ = "";
    /**
     * <pre>
     * Date of the last user sentiment prompt (formatted as string)
     * </pre>
     *
     * <code>string last_sentiment_question_date = 6 [json_name = "lastSentimentQuestionDate"];</code>
     * @return The lastSentimentQuestionDate.
     */
    @java.lang.Override
    public java.lang.String getLastSentimentQuestionDate() {
      java.lang.Object ref = lastSentimentQuestionDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastSentimentQuestionDate_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Date of the last user sentiment prompt (formatted as string)
     * </pre>
     *
     * <code>string last_sentiment_question_date = 6 [json_name = "lastSentimentQuestionDate"];</code>
     * @return The bytes for lastSentimentQuestionDate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastSentimentQuestionDateBytes() {
      java.lang.Object ref = lastSentimentQuestionDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastSentimentQuestionDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_SENTIMENT_ANSWER_DATE_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object lastSentimentAnswerDate_ = "";
    /**
     * <pre>
     * Date of the last user sentiment answer (formatted as string)
     * </pre>
     *
     * <code>string last_sentiment_answer_date = 7 [json_name = "lastSentimentAnswerDate"];</code>
     * @return The lastSentimentAnswerDate.
     */
    @java.lang.Override
    public java.lang.String getLastSentimentAnswerDate() {
      java.lang.Object ref = lastSentimentAnswerDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastSentimentAnswerDate_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Date of the last user sentiment answer (formatted as string)
     * </pre>
     *
     * <code>string last_sentiment_answer_date = 7 [json_name = "lastSentimentAnswerDate"];</code>
     * @return The bytes for lastSentimentAnswerDate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastSentimentAnswerDateBytes() {
      java.lang.Object ref = lastSentimentAnswerDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastSentimentAnswerDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_FEATURE_SURVEY_DATE_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile java.lang.Object lastFeatureSurveyDate_ = "";
    /**
     * <pre>
     * Date of the next scheduled general feature survey (formatted as string)
     * </pre>
     *
     * <code>string last_feature_survey_date = 8 [json_name = "lastFeatureSurveyDate"];</code>
     * @return The lastFeatureSurveyDate.
     */
    @java.lang.Override
    public java.lang.String getLastFeatureSurveyDate() {
      java.lang.Object ref = lastFeatureSurveyDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastFeatureSurveyDate_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Date of the next scheduled general feature survey (formatted as string)
     * </pre>
     *
     * <code>string last_feature_survey_date = 8 [json_name = "lastFeatureSurveyDate"];</code>
     * @return The bytes for lastFeatureSurveyDate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastFeatureSurveyDateBytes() {
      java.lang.Object ref = lastFeatureSurveyDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastFeatureSurveyDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_FEATURE_SURVEY_DATE_MAP_FIELD_NUMBER = 9;
    private static final class LastFeatureSurveyDateMapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.android.tools.analytics.proto.AnalyticsSettingsProto.internal_static_android_analytics_AnalyticsSettings_LastFeatureSurveyDateMapEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> lastFeatureSurveyDateMap_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetLastFeatureSurveyDateMap() {
      if (lastFeatureSurveyDateMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            LastFeatureSurveyDateMapDefaultEntryHolder.defaultEntry);
      }
      return lastFeatureSurveyDateMap_;
    }
    public int getLastFeatureSurveyDateMapCount() {
      return internalGetLastFeatureSurveyDateMap().getMap().size();
    }
    /**
     * <pre>
     * Per-feature survey schedule map (feature_name -&gt; next survey date string)
     * </pre>
     *
     * <code>map&lt;string, string&gt; last_feature_survey_date_map = 9 [json_name = "lastFeatureSurveyDateMap"];</code>
     */
    @java.lang.Override
    public boolean containsLastFeatureSurveyDateMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetLastFeatureSurveyDateMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getLastFeatureSurveyDateMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getLastFeatureSurveyDateMap() {
      return getLastFeatureSurveyDateMapMap();
    }
    /**
     * <pre>
     * Per-feature survey schedule map (feature_name -&gt; next survey date string)
     * </pre>
     *
     * <code>map&lt;string, string&gt; last_feature_survey_date_map = 9 [json_name = "lastFeatureSurveyDateMap"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getLastFeatureSurveyDateMapMap() {
      return internalGetLastFeatureSurveyDateMap().getMap();
    }
    /**
     * <pre>
     * Per-feature survey schedule map (feature_name -&gt; next survey date string)
     * </pre>
     *
     * <code>map&lt;string, string&gt; last_feature_survey_date_map = 9 [json_name = "lastFeatureSurveyDateMap"];</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getLastFeatureSurveyDateMapOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetLastFeatureSurveyDateMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Per-feature survey schedule map (feature_name -&gt; next survey date string)
     * </pre>
     *
     * <code>map&lt;string, string&gt; last_feature_survey_date_map = 9 [json_name = "lastFeatureSurveyDateMap"];</code>
     */
    @java.lang.Override
    public java.lang.String getLastFeatureSurveyDateMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetLastFeatureSurveyDateMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int LAST_OPTIN_PROMPT_VERSION_FIELD_NUMBER = 10;
    @SuppressWarnings("serial")
    private volatile java.lang.Object lastOptinPromptVersion_ = "";
    /**
     * <pre>
     * Major/minor version of Android Studio when opt-in was last prompted (e.g. "2024.1")
     * </pre>
     *
     * <code>string last_optin_prompt_version = 10 [json_name = "lastOptinPromptVersion"];</code>
     * @return The lastOptinPromptVersion.
     */
    @java.lang.Override
    public java.lang.String getLastOptinPromptVersion() {
      java.lang.Object ref = lastOptinPromptVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastOptinPromptVersion_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Major/minor version of Android Studio when opt-in was last prompted (e.g. "2024.1")
     * </pre>
     *
     * <code>string last_optin_prompt_version = 10 [json_name = "lastOptinPromptVersion"];</code>
     * @return The bytes for lastOptinPromptVersion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastOptinPromptVersionBytes() {
      java.lang.Object ref = lastOptinPromptVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastOptinPromptVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
      }
      if (optedIn_ != false) {
        output.writeBool(2, optedIn_);
      }
      if (debugDisablePublishing_ != false) {
        output.writeBool(3, debugDisablePublishing_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(saltValue_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, saltValue_);
      }
      if (saltSkew_ != 0) {
        output.writeInt32(5, saltSkew_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastSentimentQuestionDate_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, lastSentimentQuestionDate_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastSentimentAnswerDate_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, lastSentimentAnswerDate_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastFeatureSurveyDate_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, lastFeatureSurveyDate_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetLastFeatureSurveyDateMap(),
          LastFeatureSurveyDateMapDefaultEntryHolder.defaultEntry,
          9);
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastOptinPromptVersion_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, lastOptinPromptVersion_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
      }
      if (optedIn_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, optedIn_);
      }
      if (debugDisablePublishing_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, debugDisablePublishing_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(saltValue_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, saltValue_);
      }
      if (saltSkew_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, saltSkew_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastSentimentQuestionDate_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, lastSentimentQuestionDate_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastSentimentAnswerDate_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, lastSentimentAnswerDate_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastFeatureSurveyDate_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, lastFeatureSurveyDate_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetLastFeatureSurveyDateMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        lastFeatureSurveyDateMap__ = LastFeatureSurveyDateMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(9, lastFeatureSurveyDateMap__);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastOptinPromptVersion_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, lastOptinPromptVersion_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings)) {
        return super.equals(obj);
      }
      com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings other = (com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings) obj;

      if (!getUserId()
          .equals(other.getUserId())) return false;
      if (getOptedIn()
          != other.getOptedIn()) return false;
      if (getDebugDisablePublishing()
          != other.getDebugDisablePublishing()) return false;
      if (!getSaltValue()
          .equals(other.getSaltValue())) return false;
      if (getSaltSkew()
          != other.getSaltSkew()) return false;
      if (!getLastSentimentQuestionDate()
          .equals(other.getLastSentimentQuestionDate())) return false;
      if (!getLastSentimentAnswerDate()
          .equals(other.getLastSentimentAnswerDate())) return false;
      if (!getLastFeatureSurveyDate()
          .equals(other.getLastFeatureSurveyDate())) return false;
      if (!internalGetLastFeatureSurveyDateMap().equals(
          other.internalGetLastFeatureSurveyDateMap())) return false;
      if (!getLastOptinPromptVersion()
          .equals(other.getLastOptinPromptVersion())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + OPTED_IN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getOptedIn());
      hash = (37 * hash) + DEBUG_DISABLE_PUBLISHING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDebugDisablePublishing());
      hash = (37 * hash) + SALT_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getSaltValue().hashCode();
      hash = (37 * hash) + SALT_SKEW_FIELD_NUMBER;
      hash = (53 * hash) + getSaltSkew();
      hash = (37 * hash) + LAST_SENTIMENT_QUESTION_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getLastSentimentQuestionDate().hashCode();
      hash = (37 * hash) + LAST_SENTIMENT_ANSWER_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getLastSentimentAnswerDate().hashCode();
      hash = (37 * hash) + LAST_FEATURE_SURVEY_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getLastFeatureSurveyDate().hashCode();
      if (!internalGetLastFeatureSurveyDateMap().getMap().isEmpty()) {
        hash = (37 * hash) + LAST_FEATURE_SURVEY_DATE_MAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetLastFeatureSurveyDateMap().hashCode();
      }
      hash = (37 * hash) + LAST_OPTIN_PROMPT_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getLastOptinPromptVersion().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Represents the schema for ~/.android/analytics.settings serialized as JSON.
     * </pre>
     *
     * Protobuf type {@code android.analytics.AnalyticsSettings}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:android.analytics.AnalyticsSettings)
        com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettingsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.android.tools.analytics.proto.AnalyticsSettingsProto.internal_static_android_analytics_AnalyticsSettings_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 9:
            return internalGetLastFeatureSurveyDateMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 9:
            return internalGetMutableLastFeatureSurveyDateMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.android.tools.analytics.proto.AnalyticsSettingsProto.internal_static_android_analytics_AnalyticsSettings_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings.class, com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings.Builder.class);
      }

      // Construct using com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        userId_ = "";
        optedIn_ = false;
        debugDisablePublishing_ = false;
        saltValue_ = "";
        saltSkew_ = 0;
        lastSentimentQuestionDate_ = "";
        lastSentimentAnswerDate_ = "";
        lastFeatureSurveyDate_ = "";
        internalGetMutableLastFeatureSurveyDateMap().clear();
        lastOptinPromptVersion_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.android.tools.analytics.proto.AnalyticsSettingsProto.internal_static_android_analytics_AnalyticsSettings_descriptor;
      }

      @java.lang.Override
      public com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings getDefaultInstanceForType() {
        return com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings.getDefaultInstance();
      }

      @java.lang.Override
      public com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings build() {
        com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings buildPartial() {
        com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings result = new com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.userId_ = userId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.optedIn_ = optedIn_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.debugDisablePublishing_ = debugDisablePublishing_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.saltValue_ = saltValue_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.saltSkew_ = saltSkew_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.lastSentimentQuestionDate_ = lastSentimentQuestionDate_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.lastSentimentAnswerDate_ = lastSentimentAnswerDate_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.lastFeatureSurveyDate_ = lastFeatureSurveyDate_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.lastFeatureSurveyDateMap_ = internalGetLastFeatureSurveyDateMap();
          result.lastFeatureSurveyDateMap_.makeImmutable();
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.lastOptinPromptVersion_ = lastOptinPromptVersion_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings) {
          return mergeFrom((com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings other) {
        if (other == com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings.getDefaultInstance()) return this;
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getOptedIn() != false) {
          setOptedIn(other.getOptedIn());
        }
        if (other.getDebugDisablePublishing() != false) {
          setDebugDisablePublishing(other.getDebugDisablePublishing());
        }
        if (!other.getSaltValue().isEmpty()) {
          saltValue_ = other.saltValue_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.getSaltSkew() != 0) {
          setSaltSkew(other.getSaltSkew());
        }
        if (!other.getLastSentimentQuestionDate().isEmpty()) {
          lastSentimentQuestionDate_ = other.lastSentimentQuestionDate_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getLastSentimentAnswerDate().isEmpty()) {
          lastSentimentAnswerDate_ = other.lastSentimentAnswerDate_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (!other.getLastFeatureSurveyDate().isEmpty()) {
          lastFeatureSurveyDate_ = other.lastFeatureSurveyDate_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        internalGetMutableLastFeatureSurveyDateMap().mergeFrom(
            other.internalGetLastFeatureSurveyDateMap());
        bitField0_ |= 0x00000100;
        if (!other.getLastOptinPromptVersion().isEmpty()) {
          lastOptinPromptVersion_ = other.lastOptinPromptVersion_;
          bitField0_ |= 0x00000200;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                userId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                optedIn_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                debugDisablePublishing_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                saltValue_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                saltSkew_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                lastSentimentQuestionDate_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                lastSentimentAnswerDate_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 66: {
                lastFeatureSurveyDate_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              case 74: {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                lastFeatureSurveyDateMap__ = input.readMessage(
                    LastFeatureSurveyDateMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableLastFeatureSurveyDateMap().getMutableMap().put(
                    lastFeatureSurveyDateMap__.getKey(), lastFeatureSurveyDateMap__.getValue());
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              case 82: {
                lastOptinPromptVersion_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000200;
                break;
              } // case 82
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object userId_ = "";
      /**
       * <pre>
       * Pseudo-anonymous identifier for the developer environment (UUID v4)
       * </pre>
       *
       * <code>string user_id = 1 [json_name = "userId"];</code>
       * @return The userId.
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Pseudo-anonymous identifier for the developer environment (UUID v4)
       * </pre>
       *
       * <code>string user_id = 1 [json_name = "userId"];</code>
       * @return The bytes for userId.
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Pseudo-anonymous identifier for the developer environment (UUID v4)
       * </pre>
       *
       * <code>string user_id = 1 [json_name = "userId"];</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        userId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Pseudo-anonymous identifier for the developer environment (UUID v4)
       * </pre>
       *
       * <code>string user_id = 1 [json_name = "userId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        userId_ = getDefaultInstance().getUserId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Pseudo-anonymous identifier for the developer environment (UUID v4)
       * </pre>
       *
       * <code>string user_id = 1 [json_name = "userId"];</code>
       * @param value The bytes for userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        userId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private boolean optedIn_ ;
      /**
       * <pre>
       * Whether the user has opted in to telemetry collection
       * </pre>
       *
       * <code>bool opted_in = 2 [json_name = "hasOptedIn"];</code>
       * @return The optedIn.
       */
      @java.lang.Override
      public boolean getOptedIn() {
        return optedIn_;
      }
      /**
       * <pre>
       * Whether the user has opted in to telemetry collection
       * </pre>
       *
       * <code>bool opted_in = 2 [json_name = "hasOptedIn"];</code>
       * @param value The optedIn to set.
       * @return This builder for chaining.
       */
      public Builder setOptedIn(boolean value) {

        optedIn_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Whether the user has opted in to telemetry collection
       * </pre>
       *
       * <code>bool opted_in = 2 [json_name = "hasOptedIn"];</code>
       * @return This builder for chaining.
       */
      public Builder clearOptedIn() {
        bitField0_ = (bitField0_ & ~0x00000002);
        optedIn_ = false;
        onChanged();
        return this;
      }

      private boolean debugDisablePublishing_ ;
      /**
       * <pre>
       * Debug flag to disable publishing metrics to Google servers
       * </pre>
       *
       * <code>bool debug_disable_publishing = 3 [json_name = "debugDisablePublishing"];</code>
       * @return The debugDisablePublishing.
       */
      @java.lang.Override
      public boolean getDebugDisablePublishing() {
        return debugDisablePublishing_;
      }
      /**
       * <pre>
       * Debug flag to disable publishing metrics to Google servers
       * </pre>
       *
       * <code>bool debug_disable_publishing = 3 [json_name = "debugDisablePublishing"];</code>
       * @param value The debugDisablePublishing to set.
       * @return This builder for chaining.
       */
      public Builder setDebugDisablePublishing(boolean value) {

        debugDisablePublishing_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Debug flag to disable publishing metrics to Google servers
       * </pre>
       *
       * <code>bool debug_disable_publishing = 3 [json_name = "debugDisablePublishing"];</code>
       * @return This builder for chaining.
       */
      public Builder clearDebugDisablePublishing() {
        bitField0_ = (bitField0_ & ~0x00000004);
        debugDisablePublishing_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object saltValue_ = "";
      /**
       * <pre>
       * 192-bit cryptographic salt serialized as a signed decimal string
       * </pre>
       *
       * <code>string salt_value = 4 [json_name = "saltValue"];</code>
       * @return The saltValue.
       */
      public java.lang.String getSaltValue() {
        java.lang.Object ref = saltValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          saltValue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 192-bit cryptographic salt serialized as a signed decimal string
       * </pre>
       *
       * <code>string salt_value = 4 [json_name = "saltValue"];</code>
       * @return The bytes for saltValue.
       */
      public com.google.protobuf.ByteString
          getSaltValueBytes() {
        java.lang.Object ref = saltValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          saltValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 192-bit cryptographic salt serialized as a signed decimal string
       * </pre>
       *
       * <code>string salt_value = 4 [json_name = "saltValue"];</code>
       * @param value The saltValue to set.
       * @return This builder for chaining.
       */
      public Builder setSaltValue(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        saltValue_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 192-bit cryptographic salt serialized as a signed decimal string
       * </pre>
       *
       * <code>string salt_value = 4 [json_name = "saltValue"];</code>
       * @return This builder for chaining.
       */
      public Builder clearSaltValue() {
        saltValue_ = getDefaultInstance().getSaltValue();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 192-bit cryptographic salt serialized as a signed decimal string
       * </pre>
       *
       * <code>string salt_value = 4 [json_name = "saltValue"];</code>
       * @param value The bytes for saltValue to set.
       * @return This builder for chaining.
       */
      public Builder setSaltValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        saltValue_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private int saltSkew_ ;
      /**
       * <pre>
       * Rotation epoch index tracking 28-day intervals since 1970-01-01
       * </pre>
       *
       * <code>int32 salt_skew = 5 [json_name = "saltSkew"];</code>
       * @return The saltSkew.
       */
      @java.lang.Override
      public int getSaltSkew() {
        return saltSkew_;
      }
      /**
       * <pre>
       * Rotation epoch index tracking 28-day intervals since 1970-01-01
       * </pre>
       *
       * <code>int32 salt_skew = 5 [json_name = "saltSkew"];</code>
       * @param value The saltSkew to set.
       * @return This builder for chaining.
       */
      public Builder setSaltSkew(int value) {

        saltSkew_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Rotation epoch index tracking 28-day intervals since 1970-01-01
       * </pre>
       *
       * <code>int32 salt_skew = 5 [json_name = "saltSkew"];</code>
       * @return This builder for chaining.
       */
      public Builder clearSaltSkew() {
        bitField0_ = (bitField0_ & ~0x00000010);
        saltSkew_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object lastSentimentQuestionDate_ = "";
      /**
       * <pre>
       * Date of the last user sentiment prompt (formatted as string)
       * </pre>
       *
       * <code>string last_sentiment_question_date = 6 [json_name = "lastSentimentQuestionDate"];</code>
       * @return The lastSentimentQuestionDate.
       */
      public java.lang.String getLastSentimentQuestionDate() {
        java.lang.Object ref = lastSentimentQuestionDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastSentimentQuestionDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Date of the last user sentiment prompt (formatted as string)
       * </pre>
       *
       * <code>string last_sentiment_question_date = 6 [json_name = "lastSentimentQuestionDate"];</code>
       * @return The bytes for lastSentimentQuestionDate.
       */
      public com.google.protobuf.ByteString
          getLastSentimentQuestionDateBytes() {
        java.lang.Object ref = lastSentimentQuestionDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastSentimentQuestionDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Date of the last user sentiment prompt (formatted as string)
       * </pre>
       *
       * <code>string last_sentiment_question_date = 6 [json_name = "lastSentimentQuestionDate"];</code>
       * @param value The lastSentimentQuestionDate to set.
       * @return This builder for chaining.
       */
      public Builder setLastSentimentQuestionDate(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        lastSentimentQuestionDate_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Date of the last user sentiment prompt (formatted as string)
       * </pre>
       *
       * <code>string last_sentiment_question_date = 6 [json_name = "lastSentimentQuestionDate"];</code>
       * @return This builder for chaining.
       */
      public Builder clearLastSentimentQuestionDate() {
        lastSentimentQuestionDate_ = getDefaultInstance().getLastSentimentQuestionDate();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Date of the last user sentiment prompt (formatted as string)
       * </pre>
       *
       * <code>string last_sentiment_question_date = 6 [json_name = "lastSentimentQuestionDate"];</code>
       * @param value The bytes for lastSentimentQuestionDate to set.
       * @return This builder for chaining.
       */
      public Builder setLastSentimentQuestionDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        lastSentimentQuestionDate_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object lastSentimentAnswerDate_ = "";
      /**
       * <pre>
       * Date of the last user sentiment answer (formatted as string)
       * </pre>
       *
       * <code>string last_sentiment_answer_date = 7 [json_name = "lastSentimentAnswerDate"];</code>
       * @return The lastSentimentAnswerDate.
       */
      public java.lang.String getLastSentimentAnswerDate() {
        java.lang.Object ref = lastSentimentAnswerDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastSentimentAnswerDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Date of the last user sentiment answer (formatted as string)
       * </pre>
       *
       * <code>string last_sentiment_answer_date = 7 [json_name = "lastSentimentAnswerDate"];</code>
       * @return The bytes for lastSentimentAnswerDate.
       */
      public com.google.protobuf.ByteString
          getLastSentimentAnswerDateBytes() {
        java.lang.Object ref = lastSentimentAnswerDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastSentimentAnswerDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Date of the last user sentiment answer (formatted as string)
       * </pre>
       *
       * <code>string last_sentiment_answer_date = 7 [json_name = "lastSentimentAnswerDate"];</code>
       * @param value The lastSentimentAnswerDate to set.
       * @return This builder for chaining.
       */
      public Builder setLastSentimentAnswerDate(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        lastSentimentAnswerDate_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Date of the last user sentiment answer (formatted as string)
       * </pre>
       *
       * <code>string last_sentiment_answer_date = 7 [json_name = "lastSentimentAnswerDate"];</code>
       * @return This builder for chaining.
       */
      public Builder clearLastSentimentAnswerDate() {
        lastSentimentAnswerDate_ = getDefaultInstance().getLastSentimentAnswerDate();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Date of the last user sentiment answer (formatted as string)
       * </pre>
       *
       * <code>string last_sentiment_answer_date = 7 [json_name = "lastSentimentAnswerDate"];</code>
       * @param value The bytes for lastSentimentAnswerDate to set.
       * @return This builder for chaining.
       */
      public Builder setLastSentimentAnswerDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        lastSentimentAnswerDate_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private java.lang.Object lastFeatureSurveyDate_ = "";
      /**
       * <pre>
       * Date of the next scheduled general feature survey (formatted as string)
       * </pre>
       *
       * <code>string last_feature_survey_date = 8 [json_name = "lastFeatureSurveyDate"];</code>
       * @return The lastFeatureSurveyDate.
       */
      public java.lang.String getLastFeatureSurveyDate() {
        java.lang.Object ref = lastFeatureSurveyDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastFeatureSurveyDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Date of the next scheduled general feature survey (formatted as string)
       * </pre>
       *
       * <code>string last_feature_survey_date = 8 [json_name = "lastFeatureSurveyDate"];</code>
       * @return The bytes for lastFeatureSurveyDate.
       */
      public com.google.protobuf.ByteString
          getLastFeatureSurveyDateBytes() {
        java.lang.Object ref = lastFeatureSurveyDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastFeatureSurveyDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Date of the next scheduled general feature survey (formatted as string)
       * </pre>
       *
       * <code>string last_feature_survey_date = 8 [json_name = "lastFeatureSurveyDate"];</code>
       * @param value The lastFeatureSurveyDate to set.
       * @return This builder for chaining.
       */
      public Builder setLastFeatureSurveyDate(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        lastFeatureSurveyDate_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Date of the next scheduled general feature survey (formatted as string)
       * </pre>
       *
       * <code>string last_feature_survey_date = 8 [json_name = "lastFeatureSurveyDate"];</code>
       * @return This builder for chaining.
       */
      public Builder clearLastFeatureSurveyDate() {
        lastFeatureSurveyDate_ = getDefaultInstance().getLastFeatureSurveyDate();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Date of the next scheduled general feature survey (formatted as string)
       * </pre>
       *
       * <code>string last_feature_survey_date = 8 [json_name = "lastFeatureSurveyDate"];</code>
       * @param value The bytes for lastFeatureSurveyDate to set.
       * @return This builder for chaining.
       */
      public Builder setLastFeatureSurveyDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        lastFeatureSurveyDate_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> lastFeatureSurveyDateMap_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetLastFeatureSurveyDateMap() {
        if (lastFeatureSurveyDateMap_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              LastFeatureSurveyDateMapDefaultEntryHolder.defaultEntry);
        }
        return lastFeatureSurveyDateMap_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetMutableLastFeatureSurveyDateMap() {
        if (lastFeatureSurveyDateMap_ == null) {
          lastFeatureSurveyDateMap_ = com.google.protobuf.MapField.newMapField(
              LastFeatureSurveyDateMapDefaultEntryHolder.defaultEntry);
        }
        if (!lastFeatureSurveyDateMap_.isMutable()) {
          lastFeatureSurveyDateMap_ = lastFeatureSurveyDateMap_.copy();
        }
        bitField0_ |= 0x00000100;
        onChanged();
        return lastFeatureSurveyDateMap_;
      }
      public int getLastFeatureSurveyDateMapCount() {
        return internalGetLastFeatureSurveyDateMap().getMap().size();
      }
      /**
       * <pre>
       * Per-feature survey schedule map (feature_name -&gt; next survey date string)
       * </pre>
       *
       * <code>map&lt;string, string&gt; last_feature_survey_date_map = 9 [json_name = "lastFeatureSurveyDateMap"];</code>
       */
      @java.lang.Override
      public boolean containsLastFeatureSurveyDateMap(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetLastFeatureSurveyDateMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getLastFeatureSurveyDateMapMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getLastFeatureSurveyDateMap() {
        return getLastFeatureSurveyDateMapMap();
      }
      /**
       * <pre>
       * Per-feature survey schedule map (feature_name -&gt; next survey date string)
       * </pre>
       *
       * <code>map&lt;string, string&gt; last_feature_survey_date_map = 9 [json_name = "lastFeatureSurveyDateMap"];</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.String> getLastFeatureSurveyDateMapMap() {
        return internalGetLastFeatureSurveyDateMap().getMap();
      }
      /**
       * <pre>
       * Per-feature survey schedule map (feature_name -&gt; next survey date string)
       * </pre>
       *
       * <code>map&lt;string, string&gt; last_feature_survey_date_map = 9 [json_name = "lastFeatureSurveyDateMap"];</code>
       */
      @java.lang.Override
      public /* nullable */
java.lang.String getLastFeatureSurveyDateMapOrDefault(
          java.lang.String key,
          /* nullable */
java.lang.String defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetLastFeatureSurveyDateMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * Per-feature survey schedule map (feature_name -&gt; next survey date string)
       * </pre>
       *
       * <code>map&lt;string, string&gt; last_feature_survey_date_map = 9 [json_name = "lastFeatureSurveyDateMap"];</code>
       */
      @java.lang.Override
      public java.lang.String getLastFeatureSurveyDateMapOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetLastFeatureSurveyDateMap().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearLastFeatureSurveyDateMap() {
        bitField0_ = (bitField0_ & ~0x00000100);
        internalGetMutableLastFeatureSurveyDateMap().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * Per-feature survey schedule map (feature_name -&gt; next survey date string)
       * </pre>
       *
       * <code>map&lt;string, string&gt; last_feature_survey_date_map = 9 [json_name = "lastFeatureSurveyDateMap"];</code>
       */
      public Builder removeLastFeatureSurveyDateMap(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableLastFeatureSurveyDateMap().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
          getMutableLastFeatureSurveyDateMap() {
        bitField0_ |= 0x00000100;
        return internalGetMutableLastFeatureSurveyDateMap().getMutableMap();
      }
      /**
       * <pre>
       * Per-feature survey schedule map (feature_name -&gt; next survey date string)
       * </pre>
       *
       * <code>map&lt;string, string&gt; last_feature_survey_date_map = 9 [json_name = "lastFeatureSurveyDateMap"];</code>
       */
      public Builder putLastFeatureSurveyDateMap(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableLastFeatureSurveyDateMap().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000100;
        return this;
      }
      /**
       * <pre>
       * Per-feature survey schedule map (feature_name -&gt; next survey date string)
       * </pre>
       *
       * <code>map&lt;string, string&gt; last_feature_survey_date_map = 9 [json_name = "lastFeatureSurveyDateMap"];</code>
       */
      public Builder putAllLastFeatureSurveyDateMap(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableLastFeatureSurveyDateMap().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000100;
        return this;
      }

      private java.lang.Object lastOptinPromptVersion_ = "";
      /**
       * <pre>
       * Major/minor version of Android Studio when opt-in was last prompted (e.g. "2024.1")
       * </pre>
       *
       * <code>string last_optin_prompt_version = 10 [json_name = "lastOptinPromptVersion"];</code>
       * @return The lastOptinPromptVersion.
       */
      public java.lang.String getLastOptinPromptVersion() {
        java.lang.Object ref = lastOptinPromptVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastOptinPromptVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Major/minor version of Android Studio when opt-in was last prompted (e.g. "2024.1")
       * </pre>
       *
       * <code>string last_optin_prompt_version = 10 [json_name = "lastOptinPromptVersion"];</code>
       * @return The bytes for lastOptinPromptVersion.
       */
      public com.google.protobuf.ByteString
          getLastOptinPromptVersionBytes() {
        java.lang.Object ref = lastOptinPromptVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastOptinPromptVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Major/minor version of Android Studio when opt-in was last prompted (e.g. "2024.1")
       * </pre>
       *
       * <code>string last_optin_prompt_version = 10 [json_name = "lastOptinPromptVersion"];</code>
       * @param value The lastOptinPromptVersion to set.
       * @return This builder for chaining.
       */
      public Builder setLastOptinPromptVersion(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        lastOptinPromptVersion_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Major/minor version of Android Studio when opt-in was last prompted (e.g. "2024.1")
       * </pre>
       *
       * <code>string last_optin_prompt_version = 10 [json_name = "lastOptinPromptVersion"];</code>
       * @return This builder for chaining.
       */
      public Builder clearLastOptinPromptVersion() {
        lastOptinPromptVersion_ = getDefaultInstance().getLastOptinPromptVersion();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Major/minor version of Android Studio when opt-in was last prompted (e.g. "2024.1")
       * </pre>
       *
       * <code>string last_optin_prompt_version = 10 [json_name = "lastOptinPromptVersion"];</code>
       * @param value The bytes for lastOptinPromptVersion to set.
       * @return This builder for chaining.
       */
      public Builder setLastOptinPromptVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        lastOptinPromptVersion_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:android.analytics.AnalyticsSettings)
    }

    // @@protoc_insertion_point(class_scope:android.analytics.AnalyticsSettings)
    private static final com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings();
    }

    public static com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AnalyticsSettings>
        PARSER = new com.google.protobuf.AbstractParser<AnalyticsSettings>() {
      @java.lang.Override
      public AnalyticsSettings parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AnalyticsSettings> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AnalyticsSettings> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.android.tools.analytics.proto.AnalyticsSettingsProto.AnalyticsSettings getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_analytics_AnalyticsSettings_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_analytics_AnalyticsSettings_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_android_analytics_AnalyticsSettings_LastFeatureSurveyDateMapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_android_analytics_AnalyticsSettings_LastFeatureSurveyDateMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030analytics_settings.proto\022\021android.anal" +
      "ytics\"\370\004\n\021AnalyticsSettings\022\027\n\007user_id\030\001" +
      " \001(\tR\006userId\022\034\n\010opted_in\030\002 \001(\010R\nhasOpted" +
      "In\0228\n\030debug_disable_publishing\030\003 \001(\010R\026de" +
      "bugDisablePublishing\022\035\n\nsalt_value\030\004 \001(\t" +
      "R\tsaltValue\022\033\n\tsalt_skew\030\005 \001(\005R\010saltSkew" +
      "\022?\n\034last_sentiment_question_date\030\006 \001(\tR\031" +
      "lastSentimentQuestionDate\022;\n\032last_sentim" +
      "ent_answer_date\030\007 \001(\tR\027lastSentimentAnsw" +
      "erDate\0227\n\030last_feature_survey_date\030\010 \001(\t" +
      "R\025lastFeatureSurveyDate\022\202\001\n\034last_feature" +
      "_survey_date_map\030\t \003(\0132B.android.analyti" +
      "cs.AnalyticsSettings.LastFeatureSurveyDa" +
      "teMapEntryR\030lastFeatureSurveyDateMap\0229\n\031" +
      "last_optin_prompt_version\030\n \001(\tR\026lastOpt" +
      "inPromptVersion\032?\n\035LastFeatureSurveyDate" +
      "MapEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001" +
      "B;\n!com.android.tools.analytics.protoB\026A" +
      "nalyticsSettingsProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_android_analytics_AnalyticsSettings_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_android_analytics_AnalyticsSettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_analytics_AnalyticsSettings_descriptor,
        new java.lang.String[] { "UserId", "OptedIn", "DebugDisablePublishing", "SaltValue", "SaltSkew", "LastSentimentQuestionDate", "LastSentimentAnswerDate", "LastFeatureSurveyDate", "LastFeatureSurveyDateMap", "LastOptinPromptVersion", });
    internal_static_android_analytics_AnalyticsSettings_LastFeatureSurveyDateMapEntry_descriptor =
      internal_static_android_analytics_AnalyticsSettings_descriptor.getNestedTypes().get(0);
    internal_static_android_analytics_AnalyticsSettings_LastFeatureSurveyDateMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_android_analytics_AnalyticsSettings_LastFeatureSurveyDateMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
